### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ikorich** [libimobiledevice/libimobiledevice#10]
Hello, 
I made a 'pull' and got error on 'make':

Undefined symbols for architecture x86_64:
  "_debug_buffer", referenced from:
      _afc_dispatch_packet in afc.o
      _afc_receive_data in afc.o
      _afc_file_lock in afc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [libimobiledevice.la] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

**Comment by louisir7** [comment]
What mean ?
CCLD   libimobiledevice.la
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libusbmuxd.a(libusbmuxd.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libusbmuxd.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libimobiledevice.la] Erreur 1
make[2]: quittant le répertoire « /root/Downloads/libimobiledevice-master/src »
make[1]: *** [all-recursive] Erreur 1
make[1]: quittant le répertoire « /root/Downloads/libimobiledevice-master »
make: *** [all] Erreur 2

**Comment by qqtester** [comment]
where is trustdialog branch?

**Comment by mexmer** [comment]
trustdialog related stuff is already merged in master

**Comment by qqtester** [comment]
Thanks mexmer, I have got a compile success. The problem is due to apple's upgrade for OS X.
