### ISSUE TITLE
Can not backup in IOS 14

### ISSUE THREAD

**Issue by habreil** [libimobiledevice/libimobiledevice#1001]
The device has been upgraded to ios14.0.
when excute "idevicebackup2 backup xxx".  it will return error like this:
Could not perform backup protocol version exchange, error code -1.

**Comment by nikias** [comment]
Please make sure to use latest code from git. It has been fixed already.

**Comment by habreil** [comment]
> Please make sure to use latest code from git. It has been fixed already.

OK, thanks! I will try it with latest code
