### ISSUE TITLE
Are the services this library accesses supported or unsupported?

### ISSUE THREAD

**Issue by ScottPierce** [libimobiledevice/libimobiledevice#1006]
I noticed on your status page that there are several other services that aren't covered: https://libimobiledevice.org/status/

Where do these services come from? Is communicating with them documented by apple? Is this library doing something supported or unsupported?

**Comment by nikias** [comment]
The services are defined in lockdownd (embedded plist) or through a mounted developer disk image that provides additional services, in /Library/Lockdown/Services/*.plist
None of the services are documented by Apple and have mostly been figured out by dumping the communication between host and device.

**Comment by ScottPierce** [comment]
Thanks
