### ISSUE TITLE
idevicescreenshot fails on iOS 14 beta 5: Could not connect to screenshotr!

### ISSUE THREAD

**Issue by jmagman** [libimobiledevice/libimobiledevice#1015]
```
idevicescreenshot test.png --udid 00008027-001925360106802E
Could not connect to screenshotr!
```

Works on iOS 13.5.1.

**Comment by jmagman** [comment]
Did the service name change?

**Comment by nikias** [comment]
The protocol did change, make sure to update libimobiledevice to latest git code

**Comment by jmagman** [comment]
Should have mentioned I was on idevicescreenshot 1.3.0.  Thanks, will upgrade and try again!

**Comment by yatouxingren** [comment]
How to solve this problem？my idevicescreenshot version is 1.3.0，but the problem remains

**Comment by ilyalychkou** [comment]
> How to solve this problem？my idevicescreenshot version is 1.3.0，but the problem remains
the same issue.

**Comment by nikias** [comment]
1.3.0 is not latest. You need to rebuild from source to get the latest code.

**Comment by Ramia111** [comment]
> 1.3.0 is not latest. You need to rebuild from source to get the latest code.

hello, according to https://github.com/libimobiledevice/libimobiledevice/releases, 1.3.0 is the latest. I am confused. Could you please provide the webpage of the latest code?

**Comment by mexmer** [comment]
@Ramia111 releases are release packages, while latest code is in repository, clone repo and built from code, don't use prepackaged version, which from release date, you can see, is outdated

**Comment by bensh** [comment]
Found this on another bug feed. Someone made a build script.
Kudos to them, worked well for me

mkdir -p limd-build
cd limd-build
curl -o ./limd-build-macos.sh -Ls https://git.io/JEhrV 
bash ./limd-build-macos.sh

**Comment by mexmer** [comment]
@bensh that someone is nikias

**Comment by nikias** [comment]
@bensh @mexmer 🤣
