### ISSUE TITLE
Instructions to install on Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by victoriadrake** [libimobiledevice/libimobiledevice#1019]
I believe the instructions at https://libimobiledevice.org/#get-started for Ubuntu are outdated. To successfully install, I ran:

```bash
sudo apt install libimobiledevice6 usbmuxd libimobiledevice-utils
```

Only afterwards was I able to successfully see device info with `ideviceinfo`.

**Comment by andrei91ro** [comment]
I can confirm that these are the correct commands to install on Ubuntu 20.04.
These should appear on the front page, before any compilation instructions

**Comment by JunCEEE** [comment]
Yes, I think victoriadrake is correct. On this [page](https://libimobiledevice.org/#get-started) for ubuntu, the `libimobiledevice` cannot be found. I guess it should be replaced by `libimobiledevice6`. Maybe someone can get the page updated? @nikias @FunkyM Many thanks.
![image](https://user-images.githubusercontent.com/3163505/119261764-1801ca80-bbd9-11eb-9125-ed17335c8182.png)

**Comment by nikias** [comment]
Updated the page to say `libimobiledevice6`.
