### ISSUE TITLE
need help for my "hello world"

### ISSUE THREAD

**Issue by yuanjifeng** [libimobiledevice/libimobiledevice#1039]
want to complete https://libimobiledevice.org/#example-content-connecting in my raspberrypi.
connect.c:
![微信图片_20200925172230](https://user-images.githubusercontent.com/52353428/94251245-dbe86e00-ff54-11ea-8a51-b09a9c3da3cf.jpg)
gcc error:
![微信图片_20200925172302](https://user-images.githubusercontent.com/52353428/94251286-e73b9980-ff54-11ea-9cb8-4fa9aedaa689.jpg)

how to resolve ?

**Comment by mexmer** [comment]
well that sample is wrong in first place. but if you have any experience with C coding, you should see it and fixit yourself.

**Comment by nikias** [comment]
Line 12 must be `&device` and line 17 `&udid`
Not sure what happened with the markup on the page but we'll get it fixed. Also usually it should be
`#include <libimobiledevice/libimobiledevice.h>`

**Comment by mexmer** [comment]
looks read sample has same problem @nikias

**Comment by nikias** [comment]
Yes I saw that. We'll fix it.

**Comment by yuanjifeng** [comment]
![微信图片_20200925180842](https://user-images.githubusercontent.com/52353428/94255084-4819a080-ff5a-11ea-85c6-60ffa74e7fa0.jpg)
gcc error：
![微信图片_20200925180601](https://user-images.githubusercontent.com/52353428/94255172-68e1f600-ff5a-11ea-9d7e-687c792bd489.jpg)

how to resolve ?

**Comment by nikias** [comment]
I think you should learn basic things about compilation first before attempting to use this. You need to pass the libraries that you want to use:
```
gcc -o connect connect.c -limobiledevice
```

**Comment by yuanjifeng** [comment]
gcc connect.c -limobiledevice-1.0
it works.
thank you very much.

**Comment by nikias** [comment]
FYI the samples on the website are now fixed.
