### ISSUE TITLE
 Find out used storage space on a device with libimobiledevice function

### ISSUE THREAD

**Issue by bricedenice59** [libimobiledevice/libimobiledevice#1046]
Hi libimobiledevice developers,

Is there a way to know the used storage space on a device ? I couldn't find anything interesting in diagnostics lib.
Thanks a lot.

Brice

**Comment by Orbif** [comment]
You can try with this command : `idevicediagnostics mobilegestalt DiskUsage`

**Comment by nikias** [comment]
`ideviceinfo -q com.apple.disk_usage`

**Comment by bricedenice59** [comment]
Thanks both of you for replying so fast.
