### ISSUE TITLE
How can I check if the device baseband are broken

### ISSUE THREAD

**Issue by amzil** [libimobiledevice/libimobiledevice#1054]
Hello,

I use libimobiledevice the get information of an device and I'm looking for a way to baseband issues. 

Thank you for help

**Comment by a-gunter** [comment]
One consistent symptom that I've seen with baseband issues is that the IMEI is missing from the device. Activation fails in this case, as well as restore when attempting to update the baseband.

This probably doesn't encompass all baseband issues, though; it's probably just the most obvious symptom.
