### ISSUE TITLE
FullChargeCapacity is always equal to 100

### ISSUE THREAD

**Issue by XY-Wing** [libimobiledevice/libimobiledevice#1068]
<dict>
		<key>CycleCount</key>
		<integer>425</integer>
		<key>DesignCapacity</key>
		<integer>1751</integer>
		<key>FullChargeCapacity</key>
		<integer>100</integer>
		<key>Status</key>
		<string>Success</string>
	</dict>

I want to get the battery health through 'idevicediagnostics diagnostics', but I can only get the true DesignCapacity. How can I get the true FullChargeCapacity?

**Comment by ZoMinster** [comment]
same problem
