### ISSUE TITLE
idevice_id: error while loading shared libraries: libimobiledevice-1.0.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by psxpetey** [libimobiledevice/libimobiledevice#1081]
idevice_id: error while loading shared libraries: libimobiledevice-1.0.so.6: cannot open shared object file: No such file or directory

**Comment by nikias** [comment]
After installing new libraries, especially to custom locations like `/usr/local`, run `sudo ldconfig`.

**Comment by psxpetey** [comment]
> After installing new libraries, especially to custom locations like `/usr/local`, run `sudo ldconfig`.

putting this in the instructions might save you from the constant questions. I was able to get this working on mint but not the dist I wanted to get it running on
