### ISSUE TITLE
idevicescreenshot does not support ios14.2?

### ISSUE THREAD

**Issue by zhuyuemings** [libimobiledevice/libimobiledevice#1083]
i use idevicescreenshot with iphone 12 mini run with ios14.2 and it returns an error 'Could not connect to screenshotr!'.

**Comment by zhuyuemings** [comment]
libimobiledevice was installed on macOS Big Sur 11.0.1 and Xcode 12.2

**Comment by zhuyuemings** [comment]
i reinstall latest version,and it works

**Comment by elbenavi** [comment]
were you able to solve the error? because that exception throws me too

**Comment by zhuyuemings** [comment]
just install it with --HEAD. that will be ok





------------------ Original ------------------
From: elbenavi ***@***.***&gt;
Date: Fri,Jun 18,2021 3:31 AM
To: libimobiledevice/libimobiledevice ***@***.***&gt;
Cc: ZhuYueMing ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [libimobiledevice/libimobiledevice] idevicescreenshot does not support ios14.2? (#1083)





 
were you able to solve the error? because that exception throws me too
