### ISSUE TITLE
cython3 bindings don't build by default on recent Debian / Ubuntu, which do not have cython

### ISSUE THREAD

**Issue by damonlynch** [libimobiledevice/libimobiledevice#1108]
On Ubuntu 20.10, there is no `cython` package or binary. There is only the `cython3` package and binary. The default configure build step subsequently fails with this warning:

```
checking for cython... no
configure: WARNING: Unable to find 'cython' program. You should look at http://www.cython.org or install your distribution specific cython package.
```

This can be fixed by running `autogen.sh` like this:

`PYTHON=/usr/bin/python3 CYTHON=/usr/bin/cython3 ./autogen.sh`

This step is not clear to those of us who don't code in C / C++. I guess either the build files need to be updated to work on distros that have dropped Python 2, or perhaps the documentation itself could be updated?

**Comment by nikias** [comment]
I pushed commit 09f2332f7d4cd0cc8c4646a63d75a3f037e2b9b2 that will have autoconf also check for `cython3` additionally to `cython`.
