### ISSUE TITLE
Entering recovery mode on iOS 14.6 now needs device to be paired

### ISSUE THREAD

**Issue by dnsBlah** [libimobiledevice/libimobiledevice#1175]
Hi all,

I hope I'm not the only one noticing that devices now has to be paired before sending to recovery?
./ideviceenterrecovery 00008020-000C1C446061002E
Telling device with udid 00008020-000C1C446061002E to enter recovery mode.
ERROR: Could not connect to lockdownd: Invalid HostID (-21)

Is there any way we can sent devices into recovery without pairing?

There is a big chance that this is already the case since iOS14.5

**Comment by nikias** [comment]
See commit 25059d4c7d75e03aab516af2929d7c6e6d4c17de. This was changed with iOS 14.5 already.

**Comment by nikias** [comment]
No way to enter recovery unless with hardware button presses.
