### ISSUE TITLE
I need android example

### ISSUE THREAD

**Issue by tangwanchao** [libimobiledevice/libimobiledevice#1186]
I have successfully run the library on Android, but after connecting the IOS device, usbmuxd_get_device_list tells me that there is no device connection, I don't know what to do, and need your help

**Comment by hcropps** [comment]
@tangwanchao I have the same problem. Did you solve the problem?

**Comment by xanadu-lee** [comment]
The reason is that we need to run usbmuxd

**Comment by PeiNiWan1** [comment]
在android 中无法扫描到usb设备 usbmuxd_get_device_list结果为：-2

**Comment by AiXanadu** [comment]
@PeiNiWan1 因为libusb要进行一些修改。

**Comment by PeiNiWan1** [comment]
> @PeiNiWan1 因为libusb要进行一些修改。
我需要将该库移植到Android平台，但是对于该方向不了解，能否联系你，提供有偿协助，哥

**Comment by AiXanadu** [comment]
@PeiNiWan1 你是哪家公司喔，这涉及到公司机密，可能我无法有效提供帮助。

**Comment by PeiNiWan1** [comment]
个人使用，在校大学生，可以提供学生证明，毕业设计

**Comment by PeiNiWan1** [comment]
> @PeiNiWan1 你是哪家公司喔，这涉及到公司机密，可能我无法有效提供帮助。

个人使用，在校大学生，可以提供学生证明，毕业设计,哥，了解了解 给个方向也行

**Comment by AiXanadu** [comment]
> > @PeiNiWan1 你是哪家公司喔，这涉及到公司机密，可能我无法有效提供帮助。
> 
> 个人使用，在校大学生，可以提供学生证明，毕业设计,哥，了解了解 给个方向也行，实在没办法才来寻求协助的

我只能说这个需要了解NDK，Java，Android，以及C++。才可以弄。个人建议别研究了。
