### ISSUE TITLE
idevicerestore checksum error

### ISSUE THREAD

**Issue by fsinnes** [libimobiledevice/libimobiledevice#1188]
Every time I use ( idevicerestore -l ) I get a checksum verification error. Not sure what to do here.

**Comment by fsinnes** [comment]
specifically getting this 

ERROR: Can't open 'iPhone_4.7_P3_14.7_18G69_Restore.ipsw' for checksum verification

**Comment by demhademha** [comment]
Please report this issue at:
https://github.com/libimobiledevice/idevicerestore

**Comment by fsinnes** [comment]
sorry about that
