### ISSUE TITLE
idevicebackup2 broken on Big Sur 11.5?

### ISSUE THREAD

**Issue by marcinx** [libimobiledevice/libimobiledevice#1189]
Started running into this when trying to run a backup:

```
Started "com.apple.mobilebackup2" service on port 50343.
Could not perform backup protocol version exchange, error code -1
```

It was working fine before updating to Big Sur 11.5. Tried against two devices with iOS 14.7 and one device with iOS 14.2. On all three devices `idevicebackup2` terminates with above error. `ideviceinfo` works fine. Haven't tried other commands.

Any hints? Need more input? If so, which?

**Comment by marcinx** [comment]
Installed libimobiledevice on Catalina 10.15.4 and curiously enough am getting a similar error:
```
Started "com.apple.mobilebackup2" service on port 49417.
Could not perform backup protocol version exchange, error code -1
```

**Comment by mexmer** [comment]
you have most likely installed old version of libimobiledevice trough brew, you need to compile libimobile from source

**Comment by nikias** [comment]
Yes, old version. Please use my script to build everything directly from git. In case you have it installed through homebrew or macports, uninstall them first.
```bash
mkdir -p limd-build
cd limd-build
curl -o ./limd-build-macos.sh -Ls https://git.io/J3kfy
bash ./limd-build-macos.sh
```

**Comment by marcinx** [comment]
Thanks. Yes. It was a brew install. Will try. It was odd that it worked at first and then stopped.
