### ISSUE TITLE
Struggling with mobilesync_start for addressbook synchronization

### ISSUE THREAD

**Issue by MarcoB94** [libimobiledevice/libimobiledevice#1194]
Hey everyone, 
I'm trying to build an addressbook and calendar synchronization locally/via usb and without the use of iCloud. The goal is a script, which fetchs the data from a private calDav and cardDav server and synchronizes them with the respective iPhone services.  

I read a lot of issues and documentation ( e.g. #864 and https://github.com/storoj/libimobiledevice-win32/issues/18 ) , but am struggling to make progress. I'm new to mobile programming, especially iOS - I hope to get some tips and maybe clarification, what I may understand and do wrong.

**For the beginning I'm just trying to read an artifical contact which i created on the iPhone.**

Working on Linux Mint 20, iPhone SE 2016, iOS 14.6, libimobiledevice 1.3.1.
I'm able to use the bash tools like ideviceinfo etc. and getting the correct feedback.

From the info https://github.com/libimobiledevice/libimobiledevice/issues/864#issuecomment-545560349 , I disabled TetheredSync:
![Screenshot from 2021-07-26 15-56-35](https://user-images.githubusercontent.com/28571732/127001161-a95fc2ef-13b5-4262-a728-5dd8fda412bb.png)
Did this with the following code: https://gist.github.com/MarcoB94/515757f86952aa129d18e6afc7eda154

Now as said I'm trying to read the contacts from the iPhone, but getting the following error:
`-7 which is according to the documentation: MOBILESYNC_E_SYNC_REFUSED`
Furthermore the error description of the function returns 
`No Data Store available for data class!`
I am not sure what parameters to give for the data class and the computer_data_class_version and can't find any more useful information and think that this is the problem - that "Contacts" is mainly wrong.
![Screenshot from 2021-07-26 16-24-05](https://user-images.githubusercontent.com/28571732/127005189-f910eaa3-dfda-4f6e-a705-899abcec375f.png)
The complete code is here: https://gist.github.com/MarcoB94/dbb7d10670c1f49fdd67a39e29bfca2d 
At the end, I need to add mobilesync_receive, but first, when this problem is fixed.

Does somebody have any tips for me to correct this and what functions to use for the next steps?

Thank you in advance!
Regards Marco

**Comment by nikias** [comment]
Your output for `com.apple.mobile.tethered_sync` doesn't really look like what @mexmer mention in his comment here: https://github.com/libimobiledevice/libimobiledevice/issues/864#issuecomment-545968966
Does it really show what you pasted above?

**Comment by mexmer** [comment]
afaik keys are case sensitive, and i'm not aware of any change on this.

just tried with ios 14.4 and result is

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Calendars</key>
<dict>
<key>DisableTethered</key>
<false/>
<key>SyncingOS</key>
<string>Windows</string>
</dict>
<key>Contacts</key>
<dict>
<key>DisableTethered</key>
<false/>
<key>SyncingOS</key>
<string>Windows</string>
</dict>
</dict>
</plist>
```

**Comment by MarcoB94** [comment]
I really think I messed up the plist's
![Screenshot from 2021-07-26 18-01-36](https://user-images.githubusercontent.com/28571732/127021192-42c30b33-1f3f-4000-9b89-7ca0f3e2bd19.png)

**Comment by mexmer** [comment]
answer i posted above is from query to com.apple.mobile.tethered_sync
i don't know what sync_data_classes is supposed to show, but to query data classes i use
```
ideviceinfo -q com.apple.mobile.iTunes -k SyncDataClasses
```
answer looks like this
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>Contacts</string>
<string>Calendars</string>
<string>Bookmarks</string>
<string>Mail Accounts</string>
<string>Notes</string>
</array>
</plist>
```
but from my experience only Contacts and Calendars make sense and can be successfully synced. Notes Apple butchered with iOS 11 and cloud notes introduction, Mail Accounts never worked and Bookmarks do not work since introduction of safari bookmark->icloud sync (forgot which ios was that)

**Comment by MarcoB94** [comment]
I think I fixed my problems, thank you for your feedback @mexmer and @nikias : [Code if someone has the same problem](https://gist.github.com/MarcoB94/63b84364f5453b82d07c3a400dd6557a)
![Screenshot from 2021-07-27 13-10-09](https://user-images.githubusercontent.com/28571732/127144566-dd8a0266-c354-4055-a93f-249cdad505d8.png)

My earlier problem is still present:

**!!! I'm not sure what parameters to use for computer_data_class_version, as I don't have one yet! Can someone give me a hint?** (Code below)
Afterwards I hope I will get the synchronization running with the help of the documentation.

The error_description of mobilesync_start returns
` Your computer's software is out of date. Please update and try again! `

After the unsuccessful mobilesync_start I've tried to read the Contacts and it works, I get the following result, I just need to continue to read the phone number and the rest something like [LINK](https://github.com/storoj/libimobiledevice-win32/issues/18#issuecomment-55370704)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>SDMessageProcessChanges</string>
	<string>com.apple.Contacts</string>
	<dict>
		<key>1</key>
		<dict>
			<key>display as company</key>
			<string>person</string>
			<key>last name</key>
			<string>Testnachname</string>
			<key>com.apple.syncservices.RecordEntityName</key>
			<string>com.apple.contacts.Contact</string>
			<key>first name</key>
			<string>Testcontact</string>
		</dict>
	</dict>
	<true/>
	<string>___EmptyParameterString___</string>
</array>
</plist>
```

I use the following Code for generation


```c

#include "stddef.h"
#include "stdio.h"
#include "stdlib.h"
#include <string.h>
#include <libimobiledevice/libimobiledevice.h>
#include <libimobiledevice/mobilesync.h>
#include <plist/plist.h>



int main(void){
/* Unique Device Identifier */
static char *udid = NULL;


/* Device Handle */
idevice_t device = NULL;


mobilesync_client_t ms_client = NULL;
lockdownd_client_t ld_client = NULL;

/* Use the plist format */
plist_t node = NULL;
char *value = NULL;
int err;


/* Try to connect to first USB device */
if (idevice_new_with_options(&device, NULL, IDEVICE_LOOKUP_USBMUX) != IDEVICE_E_SUCCESS) {
  printf("ERROR: No device found!\n");
  idevice_free(device);
  free(udid);
  return -1;
}

/*
if (lockdownd_client_new_with_handshake(device, &ld_client, "mobilesync") != LOCKDOWN_E_SUCCESS) {
  printf("ERROR: Unable to get the lockdownd client.\n");
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  return -1;
}

//char *host_id;
lockdownd_service_descriptor_t port = NULL;
//userpref_get_host_id(&host_id);
err = lockdownd_start_service(ld_client, "com.apple.mobilesync", &port);
if (err != 0) {
  printf("lockdownd_start_service %d, exiting.\n", err);
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  return 0;
}
*/
err = mobilesync_client_start_service(device, &ms_client, "ms_label" );
if (err != 0) {
  printf("mobilesync_client_new %d, exiting.\n", err);  
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  return 0;
}

mobilesync_anchors_t this_anchors = mobilesync_anchors_new ("dev_anchor", "Comp_anchor");
if (err != 0) {
  printf("mobilesync_client_new %d, exiting.\n", err);  
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  mobilesync_anchors_free(this_anchors); 
  return 0;
}


mobilesync_sync_type_t type;
uint64_t device_data_class_version = 0;
char *error_description = NULL;
err = mobilesync_start(ms_client, "com.apple.Contacts", this_anchors, 1, &type , &device_data_class_version, &error_description );
printf("ERROR: Description: mobilesync_start failed: \n  ->  %s! \n", error_description);
printf("device_data_class_version =  %ld! \n", device_data_class_version);
if (err == 0) {
  printf("ERROR mobilesync_start: %d, exiting.\n", err);  
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  mobilesync_anchors_free(this_anchors); 
  return 0;
}



err = mobilesync_get_all_records_from_device(ms_client);
if (err != 0) {
  printf("ERROR get all records: %d, exiting.\n", err);  
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  mobilesync_anchors_free(this_anchors); 
  return 0;
}

plist_t allrecords = NULL;
err = mobilesync_receive(ms_client, &allrecords);
if (err != 0) {
  printf("ERROR reseive: %d, exiting.\n", err);  
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  mobilesync_anchors_free(this_anchors); 
  return 0;
}
/*
err = mobilesync_send_changes(ms_client, &allrecords);
if (err != 0) {
  printf("ERROR reseive: %d, exiting.\n", err);  
  idevice_free(device);
  free(udid);
  mobilesync_client_free(ms_client);
  lockdownd_client_free(ld_client);
  mobilesync_anchors_free(this_anchors); 
  return 0;
}
*/


printf("\n");
printf("/-/-/-/-/-/-/-/-/-/-/-/-\n");
printf("\n");
char *xml_doc = NULL;
uint32_t xml_length;
plist_to_xml(allrecords, &xml_doc, &xml_length);
printf("%s", xml_doc);
free(xml_doc);
printf("\n");
printf("/-/-/-/-/-/-/-/-/-/-/-/-\n");
printf("\n");


/* Cleanup */
idevice_free(device);
free(udid);
mobilesync_client_free(ms_client);
lockdownd_client_free(ld_client);
mobilesync_anchors_free(this_anchors); 
}
```

**Comment by mexmer** [comment]
yes device_data_class_version = 0 is wrong

in my code i use value 106, that was version sent by itunes since version 10 and it seems to work even with latest ios 14
