### ISSUE TITLE
iOS8 "com.apple.mobile.screenshotr" is replaced with the "com.apple.cmio.iOSScreenCaptureAssistant" service

### ISSUE THREAD

**Issue by nadavrub** [libimobiledevice/libimobiledevice#122]
On iOS8 the screenshot service is available no more, rather, apple has introduced the "iOSScreenCaptureAssistant" service, the latter enable full resolution and frame-rate mirroring of the iOS8 device.
On OS-X Yosemite each iOS8 device is exposed as a camera enabling preview & recording of the iOS8 screen using QuickTime.

Not sure how relevant is it for libmobiledevice ( since it use libusbmuxd ), however, Sniffing USB around iOS8, mirroring is done using Endpoint 6(IN) and 5(OUT) of Interface 2 of USB Configuration 5

Adding support for the "iOSScreenCaptureAssistant" is quite essential

**Comment by qdk0901** [comment]
I reverse the iOSScreenCaptureAssistant protocol and make a [demo under ubuntu](https://youtu.be/A9gqzn3XcDM) .
But I have set configuration problem with libusb when I porting this demo to Windows，it will be great if there's a version of usbmuxd that can work under Windows

**Comment by davieds** [comment]
@qdk0901 能否放出demo呢

**Comment by qmfrederik** [comment]
@qdk0901 Yup, it works under Windows as well, if you use a custom driver and usbmuxd on Windows.

Perhaps it would work with a filter driver on top of the Apple driver instead of a completely custom driver; I could get the device to show the 5th configuration but I couldn't send/receive data to the iOSScreenCaptureAssistant using a filter driver.

**Comment by nkubiak** [comment]
@qdk0901 Could you share some code?

**Comment by ketan077** [comment]
@qdk0901 Could you share some code?

**Comment by IntergalacticPenguin** [comment]
Hello, is there any example code, or is it fake? 🤔 I very badly need anything better than [Quick Time + Applescript](https://github.com/IntergalacticPenguin/mobile-toolkit/blob/master/ios/irecord)

**Comment by danielpaulus** [comment]
Hey guys, it is 2019 but anyway, if somebody still cares I created a Repo here:
https://github.com/danielpaulus/quicktime_video_hack
I reverse engineered the whole thing. My first release can dump an h264 file that is playable in VLC but going to an RTP stream from there should be relatively simple.
Also I am currently finishing documentation for the protocol Apple is using, so if you don't like golang, it should be fairly trivial to implement this in whatever language you like :-D

If anyone could help me getting this to work on Windows or Mac I'd appreciate it.
