### ISSUE TITLE
 idevicesetlocation is NOT WORKING for iOS 15

### ISSUE THREAD

**Issue by kavinduwije** [libimobiledevice/libimobiledevice#1221]
Command: idevicesetlocation -u <TYPED UDID> -- <LAT> <LONG>

Device: iPhone 11 Pro 

OS: iOS 15

ERROR: Could not start the simulatelocation service. Make sure a developer disk image is mounted!

**Comment by nikias** [comment]
Hi, the last line tells you what's wrong. Use `ideviceimagmounter` and pass a matching Developer Disk Image (+ signature) to mount it, then `idevicesetlocation` will work. I just tested it on iPhone 13 Pro and it is working as expected.

**Comment by kavinduwije** [comment]
Thanks a lot @nikias. It worked <3
