### ISSUE TITLE
Sync Bookmarks failed

### ISSUE THREAD

**Issue by xdayong** [libimobiledevice/libimobiledevice#1227]
I have a iphone 6 ,ver 14.5
I try to sync Bookmarks ,but mobilesync_start always return MOBILESYNC_E_SYNC_REFUSED.
But in an other iphone 8 ,i can success get Bookmarks infomation.

Some codes are as follows
`

1. 	int iRet = ERR_SUCCESS;
2. 	mobilesync_client_t client;
3. 	mobilesync_error_t syncerr;
4. 	char* type = "Bookmarks";
5. 
6. 	syncerr = mobilesync_client_start_service(device, &client, "com.apple.mobilesync");
7. 	if (syncerr != MOBILESYNC_E_SUCCESS)
8. 	{
9. 		idevice_free(device);
10. 		device = NULL;
11. 		return ERR_OPERATE_ERROR;
12. 	}
13. 
14. 	std::string strdataclass = "com.apple.";
15. 	strdataclass += type;
16. 	std::string strdata_device_anchor = type;
17. 	strdata_device_anchor += "-Device-Anchor";
18. 	mobilesync_anchors_t anchors;
19. 	char dataclass[200] = { 0 };
20. 	char data_device_anchor[200] = { 0 };
21. 	char data_computer_anchor[200] = { 0 };
22. 	uint64_t device_data_class_version;
23. 	char* error_description;
24. 
25. 
26. 	mobilesync_sync_type_t syn_type;
27. 	memcpy(dataclass, strdataclass.c_str(), strdataclass.length());
28. 	memcpy(data_device_anchor, strdata_device_anchor.c_str(), strdata_device_anchor.length());
29. 	time_t time(0);
30. 	strftime(data_computer_anchor, sizeof(data_computer_anchor), "%Y-%m-%d %H:%M:%S +0800", localtime(&time));
31. 
32. 	syncerr = mobilesync_anchors_new(data_device_anchor, data_computer_anchor, &anchors);
33. 	int i = 0;
34. 	Contact contact;
35. 	do
36. 	{
37. 		if (NULL == anchors)
38. 		{
39. 			iRet = ERR_OPERATE_ERROR;
40. 			break;
41. 		}
42. 		**syncerr = mobilesync_start(client, dataclass, anchors, 106, &syn_type, &device_data_class_version, &error_description);**
43. 		if (syncerr != MOBILESYNC_E_SUCCESS)
44. 		{
45. 			iRet = ERR_OPERATE_ERROR;
46. 			break;
47. 		}

`
iphone 6 on line 32 ,syncerr = MOBILESYNC_E_SYNC_REFUSED ,iphone 8 is ok .
How to solver it?

**Comment by yunhailu** [comment]
> > if it returns mobilesync_e_sync_refused, then you didn't configure phone to enable bookmark synchronization with computer
> 
> oh .first ,I run "ideviceinfo -q com.apple.mobile.tethered_sync" have nothing ,then I set Calendars ,Contacts and Bookmarks ,and I can by "ideviceinfo -q com.apple.mobile.tethered_sync" see Calendars and Contacts .Bookmarks doesn't show.
> 
> Is there anything I didn't notice?

Have you resovled the question？I have the same question with you.
