### ISSUE TITLE
Connect wireless device failed with mux_error on Win10

### ISSUE THREAD

**Issue by HackHarry** [libimobiledevice/libimobiledevice#1234]
I use Mingw64 on msys2 env.
I compile libusbmuxd、libplist successfully which are both cloned from [libimobiledevice-win32](https://github.com/libimobiledevice-win32). But when I try to compile lastest version of [libimobiledevice-win32](https://github.com/libimobiledevice-win32/libimobiledevice), I met error. 
The error is:
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/idevice.o: in function `idevice_set_tcp_endpoint':
C:\msys64\home\admin\mingw64\perf-ios\libimobiledevice\src/idevice.c:1166: undefined reference to `usbmuxd_set_tcp_endpoint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/idevice.o: in function `idevice_get_tcp_endpoint':
C:\msys64\home\admin\mingw64\perf-ios\libimobiledevice\src/idevice.c:1175: undefined reference to `usbmuxd_get_tcp_endpoint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../common/.libs/libinternalcommon.a(socket.o): in function `getifaddrs':
C:\msys64\home\admin\mingw64\perf-ios\libimobiledevice\common/socket.c:467: undefined reference to `GetAdaptersAddresses'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\home\admin\mingw64\perf-ios\libimobiledevice\common/socket.c:664: undefined reference to `ConvertLengthToIpv4Mask'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:538: libimobiledevice-1.0.la] Error 1
make[2]: Leaving directory '/home/admin/mingw64/perf-ios/libimobiledevice/src'
make[1]: *** [Makefile:457: all-recursive] Error 1
make[1]: Leaving directory '/home/admin/mingw64/perf-ios/libimobiledevice'
make: *** [Makefile:387: all] Error 2
```

**Comment by HackHarry** [comment]
Hello! After testing, I find that connecting wireless device through usbmuxd is feasible. Why don't use this way? Is it has any potential problems？
```
idevice_new_with_options(&device, udid, IDEVICE_LOOKUP_NETWORK);
device->conn_type = CONNECTION_USBMUXD;
int error = lockdownd_client_new_with_handshake(device, &client, "demo");  // error = 0
```

**Comment by xanadu-lee** [comment]
@HackHarry 
see https://github.com/libimobiledevice/libusbmuxd/pull/121

If you force the modification to CONNECTION_USBMUXD, it is feasible. but windows only.
I submitted an action to repair the WiFi connection on windows, which was not approved.

**Comment by hiepnh0** [comment]
@HackHarry 
Could you please show me the way to get UDID from network?
I checked option: "Show this iPhone when on Wi-fi" and unplugged my iPhone 6s from PC.
Then i run command: idevice_id but the output is empty.
Thanks.

**Comment by HackHarry** [comment]
> @HackHarry Could you please show me the way to get UDID from network? I checked option: "Show this iPhone when on Wi-fi" and unplugged my iPhone 6s from PC. Then i run command: idevice_id but the output is empty. Thanks.

Your phone and computer need to be connected to the same wifi firstly. Besides, you can try to reinstall iTunes.

**Comment by 18002138971** [comment]
@HackHarry 
Hello, how did you install libimobiledevice on win10 and wireless connection?
