### ISSUE TITLE
Who decides what 'tools' are packaged?

### ISSUE THREAD

**Issue by jduncanator** [libimobiledevice/libimobiledevice#124]
After becoming more and more frustrated with debugging network related iOS app's on real devices and not being able to see traffic I decided to research this mythical (or so I thought) `pcapd` service the news had been spamming about. Turns out its already implemented on Mac OSX (`rvictl`) but currently had no implementation for Windows or Linux. 

So I went out and wrote [one](https://github.com/jduncanator/iSniff). This is my first EVER (proper) C program so if there are any obvious errors, please kindly point them out. I'll be reiterating over the code more and more to make it cleaner and nicer to users. I'm also lacking any sort of build scripts (Makefile etc) because I don't know how to make them :stuck_out_tongue_winking_eye: How does one go about making them?

Back to the point. If I were to want to get this packaged in libimobiledevice, would it be the right sort of program you would want to package? And if so, how do I go about getting it merged in? Considering a lot of the other tools distributed with it are debug related tools and I see this as something people may use quite often, I would love to see it distributed with libimobiledevice :smile:

**Comment by jduncanator** [comment]
Hey @FunkyM are you still interested in having this merged in? I'll have some time over the weekend to submit a pull request.

**Comment by FunkyM** [comment]
Yes, of course! I have started integrating it in some branch and fixed an issue in the tool but it wasn't done yet.

**Comment by muuuh** [comment]
+1

**Comment by jduncanator** [comment]
Ha! Glad to hear that. I haven't tried it myself in a long time.

**Comment by nikias** [comment]
@FunkyM we should definitely integrate this. Find your branch and merge it ;)

**Comment by brainrecursion** [comment]
@FunkyM  @jduncanator Do you know if this ever got anywhere? I would be keen to get this working.
