### ISSUE TITLE
How to determine whether faceid is available？

### ISSUE THREAD

**Issue by msk521** [libimobiledevice/libimobiledevice#1251]
I want to use libimobiledevice check faceid is available, does anyone know how to do it? Thank you

**Comment by nikias** [comment]
`idevicediagnostics mobilegestalt PearlIDCapability`

**Comment by msk521** [comment]
@nikias Thank you very much for your reply.it work for me! May I ask you a few more questions? This is my first time to use this. There are too many things I don't know, such as how to compare the camera serial number obtained by AIS assistant with that of the original factory. How to obtain fingerprint serial number and display serial number.
