### ISSUE TITLE
any body know more details about reading this ex factory battery serial number and current battery serial number

### ISSUE THREAD

**Issue by msk521** [libimobiledevice/libimobiledevice#1256]
any body know more details about reading this ex factory battery serial number and current battery serial number？I can pay  for it,Contact me QQ 78728930

**Comment by uncommonthinker** [comment]
@msk521 Did you find this?

**Comment by satyamInstaCash** [comment]
@msk521 @uncommonthinker did anyone found a libimobile device command or any other way to programatically find serial number of camera please help its urgent
