### ISSUE TITLE
 Library not loaded: /usr/local/lib/libimobiledevice-1.0.6.dylib

### ISSUE THREAD

**Issue by kuuu1234** [libimobiledevice/libimobiledevice#1265]
I've been following the macOS instructions and I don't know if I'm doing it wrong or something. https://jkcoxson.github.io/DiOS-Instructions/
<img width="572" alt="Screen Shot 2022-01-14 at 11 52 40 AM" src="https://user-images.githubusercontent.com/97756533/149569548-ee7298d7-a152-4c01-b275-454665a2effc.png">

I also tried this method and nothing happens either, another error, can someone help me out? Running macOS 12.1
<img width="572" alt="Screen Shot 2022-01-14 at 11 56 19 AM" src="https://user-images.githubusercontent.com/97756533/149570087-175b4ba1-34b3-4503-be54-92a36f98a814.png">

I'm basically stuck on on step 4-5

**Comment by nikias** [comment]
Don't follow some random instructions. For macOS I always suggest to use my build script:
```
mkdir -p limd-build
cd limd-build
curl -o ./limd-build-macos.sh -L is.gd/kdT2Nl
bash ./limd-build-macos.sh
```

**Comment by kuuu1234** [comment]
> Don't follow some random instructions. For macOS I always suggest to use my build script:
> 
> ```
> mkdir -p limd-build
> cd limd-build
> curl -o ./limd-build-macos.sh -L is.gd/kdT2Nl
> bash ./limd-build-macos.sh
> ```
> 
> This installs everything with the most recent code in /usr/local by default.

So then what are my next steps? Or if I were to restart what do I do from step one to finish?

**Comment by kuuu1234** [comment]
> Don't follow some random instructions. For macOS I always suggest to use my build script:
> 
> ```
> mkdir -p limd-build
> cd limd-build
> curl -o ./limd-build-macos.sh -L is.gd/kdT2Nl
> bash ./limd-build-macos.sh
> ```
> 
> This installs everything with the most recent code in /usr/local by default.
<img width="572" alt="DB05D3D1-F235-4162-A260-77C3D7027993" src="https://user-images.githubusercontent.com/97756533/150447652-e12384c9-dd53-4b2d-a94a-3b351452321d.png">

Your script did not work. I might be missing files or something. 

The instructions that I saw online was specific and also for AltStore and to download Jit for dolphin or another emulator that required jit I believe.

If you have a FULL set your instructions with links that need any downloading or even a video to download JIT with your script then I would greatly appreciate it.

**Comment by kuuu1234** [comment]
@nikias

**Comment by nikias** [comment]
You have a typo in the curl command. Just copy and paste it.

**Comment by kuuu1234** [comment]
just did, what are the next steps to do? This is for JIT right?

**Comment by kuuu1234** [comment]
I'm not sure what exactly I am installing, is this for being able to use JIT on iOS? I got a few warnings that a version of M4 was found and doesn't support -g? It still went through saying I have to do other things. Is there a link to find the instructions on what to do next?
<img width="1792" alt="Screen Shot 2022-01-23 at 3 08 42 PM" src="https://user-images.githubusercontent.com/97756533/150700015-aab2d2ae-00ff-4f6b-9faa-0b5bc7971e36.png">
<img width="621" alt="Screen Shot 2022-01-23 at 3 09 18 PM" src="https://user-images.githubusercontent.com/97756533/150700022-58131791-771c-4994-ba53-23c3b696f829.png">
Ill wait for your response because I'm not sure what to do next

**Comment by nikias** [comment]
What exactly do you mean with "JIT on iOS"? You are building the host conputer libraries and tools, you won't change anything on the device. I am not sure what you are planning to do exactly, since you never said that.
As for the ifuse question, if unsure say N.

**Comment by kuuu1234** [comment]
I was trying to play a GameCube or wii game on dolphin emulator or gc emulator, it required JIT and that link I put in the first thread has the instructions on how to do it, I was asking help on why that's happening and how to fix it. By any chance do you have a of a work around for the first screenshots? @nikias

**Comment by kuuu1234** [comment]
It's something needed in order to play on the phone, there's an AltStore beta that comes with it pre installed but I don't think it's stable yet

**Comment by nikias** [comment]
The first screenshot only shows warnings, no errors, and the second shows that it actually continued to build. I don't see anything wrong. You should now be able to run `idevicedebug`. Also check if `ideviceinfo` works now.

**Comment by kuuu1234** [comment]
So this will help me with the question I had earlier?? To use jit. I wasn't able to use idevice_id in the first place which is why i came here so now you suggested another script and this should work? Before I select Y how do I reduce it in recovery mode? What is the command? And it says the kernel extension cache has to be regenerated?

**Comment by kuuu1234** [comment]
@nikias

**Comment by nikias** [comment]
@kuuu1234 that question you have to answer is about macFUSE. That's a virtual file system driver and only required if you want to use the `ifuse` tool (https://github.com/libimobiledevice/ifuse). It is not required so you can safely say no here and it will just not build ifuse but the rest.
I am not sure about if the JIT stuff will work; in any case after running my script you can just run all the `idevice*` commands without `./`, so just type `idevice_id` or `idevicedebug` or whatever you need to do it says in the linked tutorial.

**Comment by kuuu1234** [comment]
I'm trying to figure out why I get that error though, I was asking for help on how to get a solution and if anyone knows that can help

**Comment by nikias** [comment]
You need to be more specific. In case you are talking about the "Library not loaded" error, the first comment on this ticket explains it; it tries to find the library in /usr/local/lib while you probably have them extracted somewhere in Downloads. But as the author of the first comment here notes, it won't find libusbmuxd-2.0.6.dylib then. Which is obvious since the tutorial didn't tell you you have to download that too.
That's why I said, run my script, when asked about ifuse, say N, and you will have all conmands ready to use.

**Comment by kuuu1234** [comment]
So once I do your script I should be able to use the first script??

**Comment by kuuu1234** [comment]
@nikias

**Comment by nikias** [comment]
You don't need to @ me, I get an email for every comment made here. After my script you can do what's in their script, just remove the ./ in front of the commands since you now have it installed in a global location.

**Comment by kuuu1234** [comment]
Hey thank you for helping me out. Im on the last step of the link I posted, it saying bundle id not found, do you know if its something I did incorrectly? I tried with ./ and / but seems to not work. I have a screenshot, could you maybe review the steps and see if there was anything I did wrong? Thanks again!
<img width="621" alt="Screen Shot 2022-02-08 at 5 01 35 PM" src="https://user-images.githubusercontent.com/97756533/153096430-e3d6fa59-7188-49fb-9215-7120a940e8c4.png">

**Comment by nikias** [comment]
That doesn't look like a valid bundle identifier to me. Try `ideviceinstaller -l` to see what apps you have installed.

**Comment by mexmer** [comment]
@kuuu1234 it's small letter L, not number 1
use copey & paste next time

**Comment by kuuu1234** [comment]
Here's what I am seeing, anything unusual?
<img width="1122" alt="Screen Shot 2022-02-09 at 11 16 53 AM" src="https://user-images.githubusercontent.com/97756533/153265117-42e7c5b7-5f0d-44c7-acf2-9c8f7205b1c3.png">
<img width="1122" alt="Screen Shot 2022-02-09 at 11 17 19 AM" src="https://user-images.githubusercontent.com/97756533/153265124-d5e7ce2d-f391-4684-bee8-a484dc577474.png">

**Comment by nikias** [comment]
Come on dude, would it be too much to expect you to think a little? The output is completey normal, you need to find the package ID of the dolphin thingy. It is in the screenshot (pro tip: copy the text of the terminal output instead of a screenshot), it's the one that starts with `me.oatmealdome.` - copy the full app id and paste it to the comman you want to run.

Also please understand this is not a DiOS issue tracker, so with issues you should report them to the original project. Thanks for your understanding.

**Comment by kuuu1234** [comment]
Okay thank you ill try that :)
