### ISSUE TITLE
ERROR: "Could not start diagnostics service" with idevicediagnostics restart after restart / device is locked

### ISSUE THREAD

**Issue by kaoh** [libimobiledevice/libimobiledevice#1273]
After acknowledging the access on the device I can execute `idevicediagnostics restart`

But after the reboot, although I can execute successfully `idevice_id`, `idevicediagnostics restart` fails with:

    ERROR: Could not start diagnostics service!

When the device is unlocked again this command works again. I'm using an iPhone 6s. I'm using Ubuntu Focal and have compiled the latest version from master.

**Comment by nikias** [comment]
Several services, including diagnostics and even syslog, only work "AFU" - After First Unlock. Apple is in charge here and we cannot change that behavior.

**Comment by kaoh** [comment]
The summary is then a real remote control is not possible? I' using 'idevicediagnostics restart' to control devices before executing some tests and the devices are in a separate location controlled by the the test controlling server, similar to a device farm.

**Comment by kaoh** [comment]
I found a way for my problem:

"Settings" -> "Touch ID & Passcode" -> "Turn Passcode Off" 

And maybe also "Settings" -> "Display & Brightness" -> "Auto-Lock" -> Set to "Never"

I will try to clone the source code and add a documentation hint about this.

**Comment by kaoh** [comment]
There seem to be only the man pages where this hint could be added. Would it be better to modify the error message? Can it be detected if the device is still locked?

**Comment by nikias** [comment]
I think this is something that needs to be handled for all the tools in some way. `idevicesyslog` already has a detection for it and it actively waits until the device is unlocked; but this is not suitable for the other tools.
I will add something for the other tools.

**Comment by nikias** [comment]
@kaoh A simple way to get a meaningful error message is to use `lockdownd_strerror()`. So in case the device is locked it would print `ERROR: Failed to start service:  Password protected`.
Try this:
```diff
diff --git a/tools/idevicediagnostics.c b/tools/idevicediagnostics.c
index 0e3e66e..bd05403 100644
--- a/tools/idevicediagnostics.c
+++ b/tools/idevicediagnostics.c
@@ -213,10 +213,15 @@ int main(int argc, char **argv)

        /*  attempt to use newer diagnostics service available on iOS 5 and later */
        ret = lockdownd_start_service(lockdown_client, "com.apple.mobile.diagnostics_relay", &service);
-       if (ret != LOCKDOWN_E_SUCCESS) {
+       if (ret != LOCKDOWN_E_INVALID_SERVICE) {
                /*  attempt to use older diagnostics service */
                ret = lockdownd_start_service(lockdown_client, "com.apple.iosdiagnostics.relay", &service);
        }
+       if (ret != LOCKDOWN_E_SUCCESS) {
+               idevice_free(device);
+               printf("ERROR: Failed to start service: %s\n", lockdownd_strerror(ret));
+               goto cleanup;
+       }

        lockdownd_client_free(lockdown_client);
```

**Comment by kaoh** [comment]
Thanks. Yes, this simplifies the error chasing. If you could add this the code this would be helpful.
