### ISSUE TITLE
ideviceinstaller not working if ipa file path contains Chinese characters on windows

### ISSUE THREAD

**Issue by Dantee296** [libimobiledevice/libimobiledevice#1293]
it working totally fine on macos 

ideviceinstaller.exe -i C:\Users\席大大\AppData\apple.ipa -u 46aa83f7a6a3d923e75ba2de26ec9d35163386ae
ERROR: zip_open: C:\Users*席大大*\AppData\apple.ipa: 18*

@qmfrederik @nikias

**Comment by Dantee296** [comment]
@josephgiting  can u try it on your side to see if it works i have tried but it doesnt

@nikias its not libzip even stat() method not working

**Comment by Dantee296** [comment]
@nikias anyupdate ?
also how can i use wmain in ideviceinstaller 

 int wmain(int argc,  wchar_t **argvc)
 
 undefined reference to `wWinMain@16'

**Comment by Dantee296** [comment]
closing ticket , i have resolved the issues it needed modifications in ideviceinstaller to support unicode

```
char * -> wchar_t *
fopen -> _wfopen
zip_open -> zip_open_from_source
main() -> wmain()
```

**Comment by mexmer** [comment]
yes on windows, when compiling app with unicode support you need to use unicode function, ANSI will have issue with unicode symbols, unless you have set unicode as default coding for system ... which usually you not want.
