### ISSUE TITLE
Question:How to get the disk space that each application uses?

### ISSUE THREAD

**Issue by burningc** [libimobiledevice/libimobiledevice#130]
How can I get the space that each application uses?I use the lockdownd_get_value and set the domain argument to be "com.apple.mobile.mobile_application_usage", but it returns nothing.Below is the exhibition on the iphone.
![1](https://cloud.githubusercontent.com/assets/9248282/4642145/8b967f06-5441-11e4-85b8-5ccf737c198c.png)

**Comment by iworkcloud** [comment]
I Add below code,usbmux return:
14:40:35 [0x9d4] <-usbmuxd_recv_timeout(520, 4)
ERROR: instproxy_browse returned -6

plist_array_append_item(plistAttr, plist_new_string("CFBundleIdentifier"));
plist_array_append_item(plistAttr, plist_new_string("StaticDiskUsage"));
plist_array_append_item(plistAttr, plist_new_string("DynamicDiskUsage"));
instproxy_client_options_add(plistOption, "ReturnAttributes", plistAttr, NULL);

**Comment by burningc** [comment]
Maybe the app list info that ios device sends to you is too large so it needs more time to transfer.libimobiledevice has a default timeout.(I forgot this value,maybe 10s or 60s?)

**Comment by mexmer** [comment]
more like disk space count takes too long, so you need longer timeout.

**Comment by alex9wang** [comment]
plist_array_append_item(plistAttr, plist_new_string("CFBundleIdentifier"));
plist_array_append_item(plistAttr, plist_new_string("StaticDiskUsage"));
plist_array_append_item(plistAttr, plist_new_string("DynamicDiskUsage"));
instproxy_client_options_add(plistOption, "ReturnAttributes", plistAttr, NULL);
instproxy_client_options_add(plistOption, "ApplicationType", "User", NULL);
iError = instproxy_browse(instProxy, plistOption, &plistApp);

I have tried. but cannot get applications size.
Would you help me?

**Comment by alex9wang** [comment]
IntPtr clientOptions = instproxy_client_options_new();

            var plistAttr = PlistNative.plist_new_dict();
            PlistNative.plist_array_append_item(plistAttr, PlistNative.plist_new_string("CFBundleIdentifier"));
            PlistNative.plist_array_append_item(plistAttr, PlistNative.plist_new_string("StaticDiskUsage"));
            PlistNative.plist_array_append_item(plistAttr, PlistNative.plist_new_string("DynamicDiskUsage"));
            instproxy_client_options_add(clientOptions, "ReturnAttributes", plistAttr, IntPtr.Zero);
            instproxy_client_options_add(clientOptions, "ApplicationType", "Any", IntPtr.Zero);            

            IntPtr resultPlist;
            InstproxyError returnCode = instproxy_browse(installProxyClient, clientOptions, out resultPlist);
            instproxy_client_options_free(clientOptions);

            XDocument resultXml = LibiMobileDevice.PlistToXml(resultPlist);
            appList = new List<iOSApplication>();
            if (returnCode != InstproxyError.INSTPROXY_E_SUCCESS)
            {
                return returnCode;
            }

            else if (resultPlist == IntPtr.Zero || resultXml == default(XDocument))
            {
                return InstproxyError.INSTPROXY_E_UNKNOWN_ERROR;
            }
