### ISSUE TITLE
idevicebackup2 no longer able to create backup since commit 6cb13f9

### ISSUE THREAD

**Issue by freswa** [libimobiledevice/libimobiledevice#1309]
Before commit 6cb13f9e6d3939930aecf91d8e23d1896a3b92e5 I created dozens of backups successfully with `idevicebackup2 backup MyPhone` where MyPhone is an existing folder in the current working directory. Since said commit, it fails with
```
ERROR: No target backup directory specified.
Usage: idevicebackup2 [OPTIONS] CMD [CMDOPTIONS] DIRECTORY

Create or restore backup in/from the specified directory.
[...]
``` 

I've tried to specify the folder in different ways( `./MyPhone`, `.`), created an empty folder, tried a full backup, also added options and read the docs. No success :/

**Comment by nikias** [comment]
Fixed with 795af998e26894ede2245f6dd4d1ecd85478f4a2.
