### ISSUE TITLE
No able to run the Apps using command idevicedebug -d run "UDID"

### ISSUE THREAD

**Issue by rahul-1485** [libimobiledevice/libimobiledevice#1313]
When i try to run command **idevicedebug -d run com.companyid**  in my device i get below error. It happens with all UDID.

apple@Apples-MBP-2 ~ % idevicedebug -d run com.companyid
working_directory: /private/var/mobile/Containers/Data/Application/1920EBE1-D9A7-4A6B-ADAE-A3DDE7212470

Could not start com.apple.debugserver!
Please make sure to mount the developer disk image first:
  1) Get the iOS version from `ideviceinfo -k ProductVersion`.
  2) Find the matching iPhoneOS DeveloperDiskImage.dmg files.
  3) Run `ideviceimagemounter` with the above path.

I run the above steps image is mounted but issue is same.

IOS version i am using is 15.0

idevicedebug version 1.3.0

![imageedit_1_4835590776](https://user-images.githubusercontent.com/78218864/167793367-06e5b690-f00f-4e58-bc34-c9f551dca3cb.jpg)

**Comment by mexmer** [comment]
run 
```
idevicemounter -l
```
to see if developer image is really mounted, also keep in mind, you need to mount proper version of developer image. like developer image for iOS 14 will not work with iOS15 and vice versa.
also make sure you use latest version of libimobile (complied from github source), if you working with ios14 or ios15 devices.

**Comment by rahul-1485** [comment]
Hi @mexmer  i have installed Xcode 13.2.1 and install ideviceinstaller 1.1.1 but when i run idevicemounter -l it shows below error 

zsh: command not found: idevicemounter

<img width="583" alt="Screenshot 2022-05-11 at 8 10 37 PM" src="https://user-images.githubusercontent.com/78218864/167876963-4a2c86ff-37cf-4bbb-a785-83e596ef47b0.png">

Can you please guide.

**Comment by nikias** [comment]
@rahul-1485 that is a typo, it's called `ideviceimagemounter`. The version 1.3.0 you seem to have is certainly not the latest code, so you would have to build it yourself. Since you are on macOS, this is super easy to do that:
```
mkdir -p limd-build;
cd limd-build;
curl -o ./limd-build-macos.sh -L https://is.gd/3TMOiY ;
bash ./limd-build-macos.sh
```

**Comment by rahul-1485** [comment]
thanks @nikias i am able to launch the App now.
