### ISSUE TITLE
how involved would it be to support music sync with DBVersion 5?

### ISSUE THREAD

**Issue by porterjamesj** [libimobiledevice/libimobiledevice#133]
The website mentions that music sync is not supported for devices with DBVersion > 4. I have a new `IPad4,4`, a strong desire to not use iTunes to manage it, and a couple weeks of free time before starting a new job. I'd be happy to help implement support for DBVersion 5 assuming that this wouldn't be a ludicrously difficult undertaking and someone can point me to the right code to peer at / any legwork that's been done on this already.

**Comment by alonpeer** [comment]
Is there any chance of getting support for DBVersion 5? 
I assume that having DBVersion is the reason for why my iPhone doesn't appear in the device list in Banshee (I have libimobiledevice and ifuse installed).
