### ISSUE TITLE
[question] Is it possible to reset iPad's ID using libimobiledevice?

### ISSUE THREAD

**Issue by yurivict** [libimobiledevice/libimobiledevice#1351]
Apple's servers link iPad's ID to AppleID.
Is it possible to change iPad's ID using libimobiledevice?

Thanks,
Yuri

**Comment by truonggiang0710** [comment]
No, we can not do it via libimobiledevice.

**Comment by yurivict** [comment]
```libimobiledevice``` can't do it, but is it doable in general through the same interface?

**Comment by nikias** [comment]
No.
