### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by haasn** [libimobiledevice/libimobiledevice#1363]
As of 2022 this software is literally the only way you can sanely interact with an iDevice from a Linux desktop. Its true value is practically immeasurable.

That being said, do you have any plans on accepting donations of any form?

**Comment by Schlaubischlump** [comment]
You can already donate via PayPal: 

https://www.paypal.com/donate?token=nAj8FMg00QneOJJLWbpYZ0cKddGAqyv507zvNoD4_Y6TNPkLNGOHVxwV8N5bylOL7LCE6ul2W4MMFKuT

You can find the link at the official website. https://libimobiledevice.org/#resources

**Comment by haasn** [comment]
Thanks, I must have missed it, it's not very visible IMHO.
