### ISSUE TITLE
iOS16.0 cannot install developer plugin

### ISSUE THREAD

**Issue by xanadu-lee** [libimobiledevice/libimobiledevice#1364]
I upgraded a device from 15.6 to 16.0 and then the program that installed the developer plugin did not work successfully.

~~~
D:\win32>ideviceimagemounter.exe -u 00008110-001628DA1EDB801E -d D:\win32\DeveloperDiskImage.dmg
Uploading D:\win32\DeveloperDiskImage.dmg
done.
Mounting...
Error: ImageMountFailed
[libusbmuxd] usbmuxd_send: Error 0 when sending: No error

D:\win32> 
~~~

**Comment by cczhr** [comment]
Try turning on developer mode
![image](https://user-images.githubusercontent.com/20502238/190963746-a029a971-65dd-4a3f-82d4-b2bdc4f50ee6.png)

**Comment by mexmer** [comment]
did you enable developer mode on your device?
without developer mode enabled, developer mode doesn't work.

check following gist, but read discussion bellow, because code is not "perfect"
https://gist.github.com/nikias/262bd709c1651e0139eb9e3a2e2d33f4

**Comment by xanadu-lee** [comment]
I mean, developer images can be uploaded. But can't mount.
So, there are no developer options on the device.

**Comment by mexmer** [comment]
if you debugging ios 16.1 you need to use 16.1 image from Xcode beta
also yes, uploading developer image works, because it's done trough AFC service, but mounting requires DEVELOPER mode enabled

**Comment by mexmer** [comment]
i have posted fixed gist from nikias
https://gist.github.com/mexmer/5c9dc1220a9d028d017d1eaa76fe8df2
compile it and use
```
idevicedevmodectl showmenu
```
to show developer options in settings on device (under privacy)
then togle developer mode on - it will restart device
then you need to confirm developer mode after device unlock
and that's it, you should see in settings it's on

**Comment by xanadu-lee** [comment]
I think I get it.
I have successfully displayed the developer mode option on the device through the tutorial you sent.
Thank u.

**Comment by mexmer** [comment]
while i understand it's security measure, this new setting is just pain ...

**Comment by xanadu-lee** [comment]
You're right, it's really painful.
Some functions that could have been used are now castrated.
