### ISSUE TITLE
The confusion while getting idevices color using (ideviceinfo)

### ISSUE THREAD

**Issue by Habibullah-pythoner** [libimobiledevice/libimobiledevice#1391]
When I use ideviceinfo on iPad, I get
(DeviceColor: black) exactly what I want

But when I try it on iPhone 6, I get the following:
(DeviceColor: #e1e4e3)

and when I try iPhone 11, I get:
(DeviceColor: 1)

Is there a way to get only one type of output (the color name would be nice, eg. Black, Midnight Green...), instead of all these different and confusing results
even a way to convert these outputs to the brand's English color name would be nice too (as mentioned eg. Black, Silver, Gold....)

**Comment by mexmer** [comment]
these values are supplied by device, so whatever apple written there is there.

**Comment by Habibullah-pythoner** [comment]
so any source to know what these values mean?
so I can convert them manually

**Comment by mexmer** [comment]
to be honest, i have no idea, you would need to look around internet.
ideviceinfo (you could also run ```ideviceinfo -x``` to get xml output, as was received from device) only returns what device sent, nothing less, nothing more, it doesn't interpret values

you can referer to this thread from past, where they were asking same question
https://github.com/libimobiledevice/libimobiledevice/issues/818

**Comment by Habibullah-pythoner** [comment]
understandable, so let's think outside the box
is there a way to decode the color from, I don't know, maybe serial number, imei or maybe model number?

**Comment by nikias** [comment]
Check https://www.theiphonewiki.com/wiki/Models - every color has its own model number.

**Comment by Habibullah-pythoner** [comment]
Right, I did check on that site, I even wrote all of the phones section model numbers, but after some test, I realized that the site lacks a lot of model numbers.
Not much accurate data
