### ISSUE TITLE
Issue with Iphone 6s

### ISSUE THREAD

**Issue by Akami-Slayer** [libimobiledevice/libimobiledevice#1392]
Hi
I've been trying to recover a device, iphone 6s (already recover another one just fine) but keep getting this error, does anyone knows what it means?
`Found device in Recovery mode
Identified device as n61ap, iPhone7,2
Extracting BuildManifest from IPSW
Product Version: 12.5.6
Product Build: 16H71 Major: 16
INFO: device serial number is F17P2US0G5MC
Device supports Image4: true
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
################################ [ WARNING ] #################################

You are about to perform an ERASE restore. ALL DATA on the target device
will be IRREVERSIBLY DESTROYED. If you want to update your device without
erasing the user data, hit CTRL+C now and restart without -e or --erase
command line switch.
If you want to continue with the ERASE, please type YES and press ENTER.
##############################################################################

YES
Checking IPSW for required components...
All required components found in IPSW
Using cached filesystem from '/home/akami/Downloads/iPhone_4.7_12.5.6_16H71_Restore/038-87263-049.dmg'
Found ECID 656219868735526
Getting ApNonce in recovery mode... e2 6b 3e 36 0a 83 f1 57 11 ca 0b 3e 1d 43 6f b7 66 f7 ef 2e
Trying to fetch new SHSH blob
Getting SepNonce in recovery mode... 4c c0 ee 2b 7d 03 4c ee aa 2a 75 6c b5 a1 90 c3 e6 8e 0e 82
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Extracting iBEC.n61.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (731534 bytes)...
Recovery Mode Environment:
iBoot build-version=iBoot-4513.270.14
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2xiphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12334 bytes)...
Extracting 038-87170-059.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (9681 bytes)...
ramdisk-size=0x10000000
Extracting 038-87170-059.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (91715275 bytes)...
Extracting DeviceTree.n61ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (125714 bytes)...
Extracting kernelcache.release.iphone7...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (14069209 bytes)...
Waiting for device to enter restore mode...
About to restore device...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device f5d74fa2c1fb70260c51bd1c37520fc0f722e1a6 has successfully entered restore mode
Hardware Information:
BoardID: 6
ChipID: 28672
UniqueChipID: 656219868735526
ProductionMode: true
Starting FDR listener thread
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.n61.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2xiphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2xiphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2xiphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2xiphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2xiphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2xiphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1334iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.n61ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting recoverymode@1334~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.n61.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Extracting sep-firmware.n61.RELEASE.im4p...
Personalizing IMG4 component RestoreSEP...
Extracting sep-firmware.n61.RELEASE.im4p...
Personalizing IMG4 component SEP...
Sending NORData now...
ERROR: Unable to receive message from FDR 0x559c29cc16c0 (-2). 0/2 bytes
ERROR: Unable to send NORImageData data
ERROR: Unable to send NOR data
ERROR: Unable to successfully restore device
ERROR: Could not read data (-256). Aborting.
ERROR: Unable to restore device`

Thanks in advance

**Comment by nikias** [comment]
No need to double post an issue.
