### ISSUE TITLE
idevicedebug run incorrectly eats any parameters after the bundle ID if they look like switches

### ISSUE THREAD

**Issue by zaphodikus** [libimobiledevice/libimobiledevice#1409]
The parsing of the parameters in idevicedebug seems to think anything that looks like a switch after the run command is not intended for the target app.
idevicedebug -u (some-iphone-id) run mydomain.myapp.appname Arg0 Arg1

works just fine, but if your apps args are switches, the parsign parses them even if that appear after the 'run' command

idevicedebug -u (some-iphone-id) run mydomain.myapp.appname -someflag value 
ends up not passing -someflag value to the target app at all because of the leading '-', quoting does not help, the tool eats the parameter and only passes 'value' through in this case.

Tool should stop reading args once it has the bundle id I think.

**Comment by nikias** [comment]
That's because it uses getopt. Pass a `--` as argument and it will stop processing anything starting with a `-`.

**Comment by zaphodikus** [comment]
Aha, that helps. Thank you. It must have been a long time since I saw anyone use this trick, it's not common knowledge, but as far I'm concerned that fixes the issue for me as long as someone else can see this answer.

Happy to close, adding '--' after the bundle ID solves it.
