### ISSUE TITLE
Help needed fetch serialnumber in DFU

### ISSUE THREAD

**Issue by dnsBlah** [libimobiledevice/libimobiledevice#146]
Hi all,

I'm having an special device that puts device in DFU
The thing is, I wonder how I can get the serial number of the device now.

All I can find now is:
 Apple Mobile Device (DFU Mode):

          Product ID: 0x1227
          Vendor ID: 0x05ac  (Apple Inc.)
          Version: 0.00
          Serial Number: CPID:7000 CPRV:11 CPFM:03 SCEP:01 BDID:00 ECID:00022D3C10981026 IBFL:1C SRTG:[iBoot-1992.0.0.1.19]
          Speed: Up to 480 Mb/sec
          Manufacturer: Apple Inc.
          Location ID: 0x14100000 / 14
          Current Available (mA): 500
          Current Required (mA): 500

Anyone any idea ?

p.s. its an iPhone6

**Comment by nikias** [comment]
This is not related to libimobiledevice. Closing.

**Comment by FunkyM** [comment]
Just an idea. Perhaps it would be advised to send/donate such a "cable" to the libimobiledevice team...

**Comment by nikias** [comment]
I really like that idea :)
