### ISSUE TITLE
Handle leak when using threads on Windows

### ISSUE THREAD

**Issue by MCE-KobyBo** [libimobiledevice/libimobiledevice#147]
On windows, thread_create returns a HANDLE to the new thread. This handle should be closed using CloseHandle when it's not needed anymore. Since this is not currently done in libimobiledevice, it means that the HANDLE of each created thread is leaked.  I suggest adding "thread_close" which will do it on WIN32.

As a side note, when using Visual Studio, it's better to use _beginthreadex, rather than CreateThread, when using CRT functions (for proper per thread data initialization & cleanup).

**Comment by FunkyM** [comment]
Should be fixed in git master HEAD. Please report.
