### ISSUE TITLE
Error -38 (MC Protected) - Supervision identity cert ignored?

### ISSUE THREAD

**Issue by skulldoggery** [libimobiledevice/libimobiledevice#1470]
Hopefully user error here... 

Running Ubuntu 23.04 on a laptop for mobile testing/recovery purposes. Latest build of `libimobiledevice`

I have:

- an DEP enrolled, MDM managed iOS device
-  a supervision identity cert, added to the MDM

The same device pairs successfully with a Mac host, with the supervision identity cert in Keychain and using Apple Configurator/Console. 

The same cert has been added to the Linux host, but both before doing so and afterward, calling `ideviceinfo` returns a lockdown error of `-38`.  The device ID and name can be interrogated successfully using `idevice_id`

Is there anything obvious I'm missing? 

## Update 1
More evidence suggesting the error is me. :3 

When exporting the supervision identity from Apple Configurator, a `.der` (private key) and `.crt` file are generated.

The `.crt` is "self-signed" (owner & issuer match), but attempting to verify with `openssl` fails to validate the local issuer. 

I'll try generating a new supervision identity, using the existing private key, see if that helps.

## Update 2

Seems to this was user error after all. 

For testing purposes, took another angle and tried out `go-ios`, since the pair function allows for specifying a p12 file. 

 The private key stored in the `.der` file wasn't playing nice with `openssl pkcs12` to export due to encoding, so I copied out the base64 pkey to a new file, and everything went swimmingly from there.

**Comment by skulldoggery** [comment]
> Sorry to bump this older issue, I'm having the same issue, did you ever get this to work? How could you add the supervision certificate to lockdownd?

Hmm... Let me go back and look! I'll get back to you! 

The supervision identity is added by your MDM of choice, either Apple Configurator or another product. You would need to create your own, I can share those steps if needed. But the phone would need to be managed/supervised, a personal device should not need any of that

**Comment by xcbjky** [comment]
What methods are there to bypass this policy? MDM does not allow the phone to pair with iTunes, returning MC Protect (-38).
