### ISSUE TITLE
Running Instruments Automation without Xcode

### ISSUE THREAD

**Issue by Jonahss** [libimobiledevice/libimobiledevice#149]
I'm interested in running Instruments on a Linux host. I'm more than happy to contribute the code for this myself but don't know where to start. Any pointers or past work done on this would be appreciated.

Maybe @FunkyM could explain how this was done at Mirell?

**Comment by saikrishna321** [comment]
+1 i'm looking for the same.

**Comment by qmfrederik** [comment]
Hi @Jonahss, @konobi , @saikrishna321 ,

In case you haven't been able to reach Mirell & you're still looking for a similar solution, we've developed a way to run Instruments using libimobiledevice on Linux/Windows.

If you're interested, contact me through GitHub or at info@quamotion.mobi .

Frederik.

**Comment by swiftleigh** [comment]
Has anyone figured this out?

**Comment by saikrishna321** [comment]
@qmfrederik yah the community is very interested in this.. can you please provide some links or code that would help us run instruments on minux/windows 

this would be really really help-full

**Comment by saikrishna321** [comment]
@imurchie

**Comment by swiftleigh** [comment]
I have tried to contact Mirell but no answer :(

**Comment by qmfrederik** [comment]
@saikrishna321, @imurchie - just to be clear, what we have is a commercial offering that allows you to run UIAutomation (currently not XCUITest) scripts on an iOS device from a Linux/Windows PC. If you're interested in that, ping me & we can discuss further.
