### ISSUE TITLE
Unable to get device information Like serial number and battery information.

### ISSUE THREAD

**Issue by AKT04** [libimobiledevice/libimobiledevice#1541]
I am unable to get device information like serial number and battery information when i am connecting multiple devices (Same Model device i.e. iPhone 13).

**Comment by ekscrypto** [comment]
You should be able to get the information you need from `lockdownd_get_value()` requesting domain = NULL and key = NULL and/or `SerialNumber`.  Look for the dictionary value `SerialNumber` in the response.  

For the battery level, this post indicates you can get it from diagnostic information.  It's likely in some other burried domain/value key pair but I do not know which one. https://github.com/libimobiledevice/libimobiledevice/issues/1095
