### ISSUE TITLE
How to backup a part of idevice

### ISSUE THREAD

**Issue by paradisepi** [libimobiledevice/libimobiledevice#156]
Hello,
I need backup only sms or contact of my iphone. But mobilebackup2  is full backup.
Please help me some hint to do it!

Thanks.

**Comment by mexmer** [comment]
you can't do partial backup, it doesn't have such option. backup to icloud is incremental, after full backup only changes uploaded. unless you delete your icloud backup, then it will again do full.

similar works with local backup, if you have local backup present, it will backup only changes, unless you force full backup.

**Comment by mexmer** [comment]
Cloud on/off just enables or didables backup from your idevice to your icloud account. Backup to icloud is done periodically (not sure how often), and also whenever you are upgrading ios. If you have icloud backup on. You can also do icloud backup manualy from your idevice.
