### ISSUE TITLE
master fails to build with libressl 3.9.1

### ISSUE THREAD

**Issue by Un1q32** [libimobiledevice/libimobiledevice#1560]
The lastest git commit uses functions that were removed in libressl 3.9.1 resulting in a failed build

**Comment by nikias** [comment]
Would be helpful to get some output so I can work around the functions that have been removed

**Comment by orbea** [comment]
I didn't notice this issue before now, but this should fix at least some of the issues?

https://github.com/libimobiledevice/libimobiledevice/pull/1561
https://github.com/libimobiledevice/libimobiledevice/pull/1562

**Comment by Un1q32** [comment]
> I didn't notice this issue before now, but this should fix at least some of the issues?
> 
> #1561 #1562

Those are the functions I had issues with, I'll try to build with those patches

**Comment by Un1q32** [comment]
The build works with those 2 patches

**Comment by orbea** [comment]
@Un1q32 This should be fixed now in the master branch?

**Comment by Un1q32** [comment]
yes, master builds now
