### ISSUE TITLE
ideviceinfo shows wrong productType

### ISSUE THREAD

**Issue by Lohithlee** [libimobiledevice/libimobiledevice#1571]
i currently have iPhone13, when i give 'ideviceinfo  | grep  'ProductType'' command it returns as iPhone14 and same goes with other models
it always returns one model ahead. kindly help on this.
ideviceinfo 1.3.0 is version i am using

**Comment by nikias** [comment]
That's not a bug, the ProductType is not the model name.

**Comment by Lohithlee** [comment]
ProductType: iPhone12,1
above is the return for productType, could you please explain what it is provided that the connected phone was iPhone11

**Comment by nikias** [comment]
https://theapplewiki.com/wiki/IPhone_11
see "InternalName"

https://ipsw.me/iPhone12,1/info
see "Identifier"

it's just how Apple named them internally...

**Comment by mexmer** [comment]
as nikias said, it's internal product identification apple gave it, there are many sites, where you can search by that name (including apple support). you can also check this gist
https://gist.github.com/adamawolf/3048717
or if you interested also in apple computers and not just mobile devices (for example MacBookAir1,1 is returned for macbook air 13" from 2008) check this site
https://everymac.com/

**Comment by Lohithlee** [comment]
> as nikias said, it's internal product identification apple gave it, there are many sites, where you can search by that name (including apple support). you can also check this gist https://gist.github.com/adamawolf/3048717 or if you interested also in apple computers and not just mobile devices (for example MacBookAir1,1 is returned for macbook air 13" from 2008) check this site https://everymac.com/

thanks a lot
