### ISSUE TITLE
How to exit recovery mode to normal mode

### ISSUE THREAD

**Issue by Neil-0609** [libimobiledevice/libimobiledevice#1576]

**Comment by diamond261** [comment]
whta model are your iPad/iPhone?

**Comment by Neil-0609** [comment]
> Whta model are your iPad/iPhone?

iPhone13 Pro

**Comment by nikias** [comment]
Have you tried `irecovery -n` ?

**Comment by Neil-0609** [comment]
> Have you tried `irecovery -n` ?

It works, thanks
