### ISSUE TITLE
Backup Failed (Error Code 205)

### ISSUE THREAD

**Issue by trenchcoatjedi** [libimobiledevice/libimobiledevice#1582]
Ubuntu 24.04
iPhone SE (2022) on iOS 15.6.1

> $ idevice_id --version
> idevice_id 1.3.0
> $ idevicebackup2 -v
> idevicebackup2 1.3.0
> $ idevicepair -v
> idevicepair 1.3.0

Backup always fails as follows:

> idevicebackup2 backup --full -d /path-to-backup-directory
> Backup directory is "/path-to-backup-directory"
> Started "com.apple.mobilebackup2" service on port 61680.
> Negotiated Protocol Version 2.1
> Reading Info.plist from backup.
> Starting backup...
> Enforcing full backup from device.
> Backup will be unencrypted.
> Requesting backup from device...
> Incremental backup mode.
> Sending '00008030-001D35093EF2402E/Status.plist' (189 Bytes)
> Sending '00008030-001D35093EF2402E/Manifest.plist' (0 Bytes)
> ErrorCode 205: Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).
> Received 0 files from device.
> Backup Failed (Error Code 205).

**Comment by mexmer** [comment]
your manifest file is empty (in your log you can see, it says 0 bytes).
seem you have unfinished/broken backup stored in your computer, just do backup to different folder, or delete folder with unfinished backup.

**Comment by trenchcoatjedi** [comment]
Working perfectly now. Many thanks!
