### ISSUE TITLE
it's a typo? for iidevicebtlogger_CFLAGS

### ISSUE THREAD

**Issue by liu6x6** [libimobiledevice/libimobiledevice#1593]
https://github.com/libimobiledevice/libimobiledevice/blob/2a0a6d57df3791419dfcda070d9ba6189f518bd5/tools/Makefile.am#L38C1-L39C1

iidevicebtlogger_CFLAGS = $(AM_CFLAGS)
idevicebtlogger_LDFLAGS = $(top_builddir)/common/libinternalcommon.la $(AM_LDFLAGS)

Hi look like there are 2 'i' here , it's a typo?

**Comment by mexmer** [comment]
looks like one. you can just fork it and propose direct change.

**Comment by nikias** [comment]
Already fixed: 42f25532bd98a3ffe361e719f9c51fb05573deb3
