### ISSUE TITLE
Building error on Windows

### ISSUE THREAD

**Issue by h3artbl33d** [libimobiledevice/libimobiledevice#1614]
Following the instructions, building `libimobiledevice` fails on Windows:

```
notification_proxy.c:35:18: error: implicit declaration of function 'Sleep'; did you mean 'sleep'? [-Wimplicit-function-declaration]
```

I have fixed this by making the suggested edit - but you might want to be aware of this.

**Comment by nikias** [comment]
That's not the right fix. It lacks an include. I fixed it with c60d70c.
