### ISSUE TITLE
can not backup with idevicebackup2

### ISSUE THREAD

**Issue by gdteng** [libimobiledevice/libimobiledevice#168]
I can not backup iphone4 with ios 7.  With the error "Could not perform backup protocol version exchange, error code -6" . If  Commented Out  the related code
/*
double local_versions[2] = {2.0, 2.1};
double remote_version = 0.0;
err = mobilebackup2_version_exchange(mobilebackup2, local_versions, 2, &remote_version);
		if (err != MOBILEBACKUP2_E_SUCCESS) {
			printf("Could not perform backup protocol version exchange, error code %d\n", err);
			cmd = CMD_LEAVE;
			goto checkpoint;
}
*/
then with the error
“Error reading status (MBErrorDomain/103). Underlying error: Multi status at path "0a9f1eb97b5b6b2a69fa1624d8542e5b4056eb0b/Status.plist" (MBErrorDomain/1).”。

If i copy the files(status.plist,manifest.plist,manifest.mbdb)to the directory of backup,then idevicebackup2 can successfully backup the iphone.

Any help would be appreciated.

**Comment by hawking2013** [comment]
This error occurs because of endianness mismatch when exchange binary data with the device.

**Comment by XuQingsong** [comment]
And how to fix it @hawking2013 ?

**Comment by hawking2013** [comment]
I just set  LITTLE_ENDIANESS macro before compile on windows then this error gone.

**Comment by gdteng** [comment]
Thanks for your reply.I have already solved this proplem.

**Comment by RonnieLLL** [comment]
@gdteng  
Hi! now I have similar problems.
I can not backup iPad mini with ios 8.1.2.
But there had same problems, error "Could not perform backup protocol version exchange, error code -6" . 
/*
double local_versions[2] = {2.0, 2.1};
double remote_version = 0.0;
err = mobilebackup2_version_exchange(mobilebackup2, local_versions, 2, &remote_version);
if (err != MOBILEBACKUP2_E_SUCCESS) {
printf("Could not perform backup protocol version exchange, error code %d\n", err);
cmd = CMD_LEAVE;
goto checkpoint;
}
*/
the 'err ==  MOBILEBACKUP2_E_NO_COMMON_VERSION'
How do you solve this problem, many thanks!

**Comment by 1714146** [comment]
how to fix it @hawking2013 ?

**Comment by 1714146** [comment]
how to fix it @gdteng
