### ISSUE TITLE
No package 'libusbmuxd' found

### ISSUE THREAD

**Issue by bpinaya** [libimobiledevice/libimobiledevice#181]
On Ubuntu 14.04 for IOs 8 guys, please help. When I try to install libusbmuxd the same error appears but with different packages.

**Comment by cepages** [comment]
I had the same problem and I fixed downloading the `libusbmuxd` from https://github.com/libimobiledevice/libusbmuxd when I tried to install it following the steps in the readme I had to do the same with `libplist` https://github.com/libimobiledevice/libplist

After installing everything the installation of `libusbmuxd` seems to work.

My ubuntu version is: `14.04 LTS`
