### ISSUE TITLE
INSTPROXY_COMMAND_TYPE_ASYNC

### ISSUE THREAD

**Issue by xdeng** [libimobiledevice/libimobiledevice#182]
Install Uninstall Archive RemoveArchive Upgrade  

All of them are asynchronous   

Why does it take the callback function to do？？？？

installation_proxy.c 665 line

**Comment by FunkyM** [comment]
I don't understand your question. The callback function is optional and can be used to track the status of each of the operations. This is explained in the API reference documentation.
The API is closely based on how the protocols work.

**Comment by xdeng** [comment]
I was wrong      So I closed the
