### ISSUE TITLE
idevicebackup2 ErrorCode 212 Unable to backup until Setup is finished

### ISSUE THREAD

**Issue by mjkokid** [libimobiledevice/libimobiledevice#187]
This error usally happen with iOS 8.1.2, 8.2. Using idevicebackup2 to backup iPhone 5 (8.2), it was failed, repeat 3-4 time it backuped success.
  libimobiledevice 1.1.7
  libplist 1.12
  libusbmuxd 1.0.10

**Comment by mjkokid** [comment]
Started "com.apple.mobilebackup2" service on port 49225.
Negotiated Protocol Version 2.1
Reading Info.plist from backup.
Starting backup...
Backup will be unencrypted.
Requesting backup from device...
Incremental backup mode.
Backup Start..................
ErrorCode 212: Unable to backup until Setup is finished (MBErrorDomain/212)
Received 0 files from device.
Backup Failed (Error Code 212).

**Comment by Louti** [comment]
Hello,

This happens when your device is still not setup or stuck in the setup screen (where you select the language, activation, passcode, ....) 

Cheers

**Comment by nikias** [comment]
@Louti 100% correct. Closing.
