### ISSUE TITLE
`idevicedebug run` prints "Segmentation fault" when given an invalid/uninstalled app id

### ISSUE THREAD

**Issue by greg-dennis** [libimobiledevice/libimobiledevice#211]
To repro:
  idevicedebug run my.nonsense.App

**Comment by progressnerd** [comment]
Here's a small patch to improve the situation, I inserted the following onto line [315 of idevicedebug.c](https://github.com/libimobiledevice/libimobiledevice/blob/master/tools/idevicedebug.c#L315).
```
if (!path) {
	fprintf(stderr, "Invalid bundle identifier: %s\n", bundle_identifier);
	goto cleanup;
}
```

For extra credit, we could use the instproxy_client to actually grab the list of installed bundle ids and print them out.

**Comment by nikias** [comment]
Fixed in git
