### ISSUE TITLE
Turning off wifi on iPhone through command line tool

### ISSUE THREAD

**Issue by harish2304** [libimobiledevice/libimobiledevice#217]
Can we turn off the wifi in iPhone by using libmobiledevice tool.Is it possible?
Anyhelp is appreciated.

Thanks
Harish

**Comment by qianguozheng** [comment]
I believe it can. but how to do it, i have no idea

**Comment by jevinskie** [comment]
idevicediagnostics shutdown

**Comment by harish2304** [comment]
i don't want to shut down the device, just want to toggle wifi ..

**Comment by mexmer** [comment]
there is no command to toggle wifi afaik
it's only possible trough settings (on device ui)

**Comment by shermanericSF** [comment]
I created this.  It uses networksetup.  I know it could be cleaner.  hope it helps!
https://gist.github.com/shermanericSF/9dac47f0a8d804011d08

**Comment by tarrenj** [comment]
shermanicSF,

So I'd have to run this on the device I wanted to change the network
setting on, right?  I can't connect my iDevice to a computer, and run this
on there to change the settings on the iDevice?

On Tue, Sep 1, 2015 at 6:15 PM, shermanericSF <notifications@github.com>
wrote:

> I created this. It uses networksetup. I know it could be cleaner. hope it
> helps!
> https://gist.github.com/shermanericSF/9dac47f0a8d804011d08
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libimobiledevice/libimobiledevice/issues/217#issuecomment-136879205>
> .
>



-- 
Jake Tarren
jake.tarren@gmail.com
(804) 385-5019

**Comment by shermanericSF** [comment]
right.  This assumes you set up your host desktop up for internet sharing.  Then, on your device you pick this access point.  I would also forget other nearby devices.  The connection shaping happens downstream on the host instead of directly on the device, but if set up correctly has the same effect.

**Comment by FunkyM** [comment]
Not really. There are ways to do it but nothing straightforward like an on/off command.
