### ISSUE TITLE
idevicebackup2 doesn't work with iOS 9

### ISSUE THREAD

**Issue by xavo95** [libimobiledevice/libimobiledevice#235]
after updating to iOS 9, idevicebackup2 restore gets stuck at manifest.mbdb upload. Then it loops in to the 'Device isn't ready' annoying message

**Comment by nikias** [comment]
It works with iOS 9, I just tested it (again, I actually already knew it works). I assume something is wrong with your backup database. I would be helpful to get output from `idevicesyslog` while you try to restore the backup. Just run it on another terminal.

**Comment by xavo95** [comment]
okey i will do it as soon as i can. thanks to help

**Comment by xavo95** [comment]
sorry i fixed it, it was the sh*t iCloud. Removed account and going.

Thanks for help and sorry for inconveniences.
