### ISSUE TITLE
com.apple.mobilebackup2 could not start

### ISSUE THREAD

**Issue by k1priest** [libimobiledevice/libimobiledevice#266]
Hello, i was trying to do the bypass trick with backups but when i try to restore the backup it gives me this error:
"could not start service com.apple.mobilebackup2".
Thank you!
PS: im on windows 8 btw.

**Comment by girlMP** [comment]
BUMP... Also want to know how to fix the com.apple.mobilebackup2 error

**Comment by trejo08** [comment]
Also I'm trying to fix that error, if someone knows how to fix it please tell me.

Thanks

**Comment by LetsUnlockiPhone** [comment]
you need to activate your device first
com.apple.mobilebackup wont start till your device pass activation

**Comment by nikias** [comment]
Not a bug in libimobiledevice. Closing.
