### ISSUE TITLE
idevicecrashreport.c flipped sign?

### ISSUE THREAD

**Issue by codegoddesskh** [libimobiledevice/libimobiledevice#270]
https://github.com/libimobiledevice/libimobiledevice/blob/master/tools/idevicecrashreport.c#L408

Should ```(attempts > 10)``` be ```(attempts <= 10)```?

(If so, it looks like this never reads for the ping message, but presumably the safe harbor copy happens quickly enough that it doesn't matter.)

**Comment by FerencYAO** [comment]
too 傻

2015年12月16日星期三，Kelly Heffner Wilkerson <notifications@github.com> 写道：

**Comment by nikias** [comment]
Fixed in master. Thanks for reporting!
