### ISSUE TITLE
ERROR: Could not connect to lockdownd, error code -5

### ISSUE THREAD

**Issue by divyum** [libimobiledevice/libimobiledevice#276]
Hi,
None of the `libimobileidevice` commands work with this error. I am facing this error on ios 9. I tried to reboot the device but didn't help. 
As per the source -5 code is LOCKDOWN_E_SSL_ERROR.
I even tried to change time of device to my mac (OS X) time but still facing the issue.

I am using libimobiledevice-1.2.0

**Comment by mexmer** [comment]
this error comes from wrong pairing information.
you need to redo pairing with your phone first.

**Comment by divyum** [comment]
Thanks. It helped :+1:

**Comment by templatetuners** [comment]
i'm getting this error "ERROR: Could not connect to lockdownd, error code -5" on iOS 9.2. Paired with the phone with idevicepair pair and got SUCCESS: Paired with device 76ac1f724a6bd1e80ba55509f9ff4faa099d398f but still error -5
using libi 1.2.0 latest version. any help?

**Comment by templatetuners** [comment]
@VasilijSviridov you can try [https://mega.nz/#!V0dUAQqT!CBca69kGYpGQObiKuO1LU9ROqnXakThp5a0-8Y3Svfw](url) - works for me

**Comment by VasilijSviridov** [comment]
Do you have similar for mac osx users ?

**Comment by templatetuners** [comment]
[https://mega.nz/#!RhtUwLJB!pNyM7lLEStfiDdsl0CRhXMZnE6sTrgPD12mUqRZBnuU](url) New Updated LibiMobileDevice [iDeviceRestore] Compiled - OS X

**Comment by VasilijSviridov** [comment]
Thank you so much will test it
Cheers

**Comment by VasilijSviridov** [comment]
@templatetuners  could you tell steps how you compile libimobile* for using tls instead of ssl ?

**Comment by burakbozyigit** [comment]
Hey there i am still getting this error on Mac OSX. Do you have any idea to solve this permanently?
I've installed package via npm.

**Comment by nikias** [comment]
1.2.0 is not the latest, you need the latest code from git. lockdown error -5 means SSL error. You need to link against a working version of OpenSSL, the one from MacPorts works fine. Also, there is no need in using ```idevicepair``` because macOS stock usbmuxd will pair the device for you and the idevicetools should just work.

**Comment by burakbozyigit** [comment]
Thanks for the answer @nikias ! 
I also apologize for being an impatient man as after my comment, I upgraded related package and get rid of the problem. 
Thanks again and sorry for impatient behaviour.

**Comment by crummy** [comment]
I see this issue on Mac with iOS10 devices, after a `brew install libimobiledevice`. Fixed with `brew install --HEAD libimobiledevice` (you may have to unlink first).

**Comment by TiagoGomesDesign** [comment]
Thanks @crummy! That work for me
