### ISSUE TITLE
Any domain or keys to check jailbroken status just like "com.apple.fmip" to check find my iphone?

### ISSUE THREAD

**Issue by jackczhang** [libimobiledevice/libimobiledevice#281]
Is there any domains or keys to check if the device jailbroken?
Just like com.apple.fmip key IsAssociated to check "find my iphone"?

**Comment by mexmer** [comment]
you can check if there is afc2 service running (but this is optional), you can also check if ssh port is open (either 22 or 2222), but that's also optional.

afaik none of jailbreaks offers some aditional service, and they rather try to be hidden.

also another test (for jailbreak) is to try to install selfsigned application. jailbreak is primarily for allowing installation of nonstore application (eg. disables signature validity check) - imo this one is most reliable.

**Comment by daniel-bluesea** [comment]
@mexmer thanks for your reply.
by selfsigned application do you mean signed with my developer signature?

**Comment by mexmer** [comment]
yes, for example. jailbroken device will accept developer signed package even if it's not on list of testing devices.

**Comment by daniel-bluesea** [comment]
cool, i'll check this out
thanks
