### ISSUE TITLE
idevicedebug can't start the app when the device is in sleep

### ISSUE THREAD

**Issue by umutuzgur** [libimobiledevice/libimobiledevice#282]
When this happens idevicedebug fails to understand that the app failed to open. So the process doesn't exit but still waits. When this command is run while the device is in the sleep state, the app opens up and then dies immediately. However if you run the command when the device is awake everything works. Here is the device log when this happens

Feb 18 10:45:07 iPad syslogd[22] <Notice>: ASL Sender Statistics
Feb 18 10:45:07 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
     for armv7.
Feb 18 10:45:07 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: Connecting to com.apple.debugserver service...
Feb 18 10:45:07 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: Got a connection, waiting for process information for launching or attaching.
Feb 18 10:45:07 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: Sending AppProxy info: sequence no: 275, GUID: 58D9D172-A6D0-42AC-B0C3-BF6B2E718B87.
Feb 18 10:45:07 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Error>: error: Unrecognized event type: .  Ignoring.
Feb 18 10:45:07 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: About to launch process for bundle ID: com.testobject.waker
Feb 18 10:45:08 iPad SpringBoard[48] <Warning>: [MPUSystemMediaControls] Enabling lock screen media controls updates for screen turning on.
Feb 18 10:45:08 iPad backboardd[63] <Notice>: [HID] [MT] MTSimpleHIDManager::setPropertyInternal detection mode: 255->6 (deferring until bootloaded)
Feb 18 10:45:08 iPad sharingd[31] <Notice>: 10:45:08.206 : Tethering: Identifier needs fixing
Feb 18 10:45:08 iPad backboardd[63] <Notice>: [HID] [MT] MTSimpleHIDManager::setPropertyInternal detection mode: 6->3 
Feb 18 10:45:08 iPad backboardd[63] <Notice>: [HID] [MT] MTSimpleHIDManager::deviceDidBootload device bootloaded
Feb 18 10:45:08 iPad backboardd[63] <Notice>: [HID] [MT] MTSimpleHIDManager::setPropertyInternal detection mode: 3->3 
Feb 18 10:45:08 iPad SpringBoard[48] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Feb 18 10:45:09 iPad kernel[0] <Notice>: xpcproxy[2129] Container: /private/var/mobile/Containers/Data/Application/DB425ED8-194F-46E0-9C58-5FE3F278748A (sandbox)
Feb 18 10:45:09 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: In completion handler, got pid for bundle id, pid: 2129.
Feb 18 10:45:09 iPad SpringBoard[48] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb 18 10:45:09 iPad SpringBoard[48] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb 18 10:45:09 iPad SpringBoard[48] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb 18 10:45:09 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: error: failed to launch process /Developer/usr/bin/debugserver: unknown error.
Feb 18 10:45:09 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: 1 +0.000000 sec [0850/1107]: error: ::read ( -1, 0x1f2189ec, 18446744069414585344 ) => -1 err = Bad file descriptor (0x00000009)
Feb 18 10:45:09 iPad com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.51.1
    [2128] <Warning>: Exiting.
Feb 18 10:45:09 iPad assertiond[64] <Warning>: Unable to get entitlements for client task. Error: Error Domain=NSPOSIXErrorDomain Code=3 "No such process"
Feb 18 10:45:09 iPad assertiond[64] <Notice>: Failed to get cs_flags, error=3
Feb 18 10:45:09 iPad SpringBoard[48] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb 18 10:45:09 iPad SpringBoard[48] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb 18 10:45:09 iPad SpringBoard[48] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Feb 18 10:45:09 iPad assertiond[64] <Notice>: SecTaskLoadEntitlements failed error=3 cs_flags=ffffffff, task->pid_self=-1
Feb 18 10:45:09 iPad com.apple.xpc.launchd[1](UIKitApplication:com.testobject.waker[0xdbd6][2129]) <Notice>: Service exited due to signal: Killed: 9
Feb 18 10:45:09 iPad assertiond[64] <Notice>: SecTaskCopyDebugDescription: debugserver[2128]
Feb 18 10:45:10 iPad assertiond[64] <Warning>: Unable to get entitlements for client task. Error: Error Domain=NSPOSIXErrorDomain Code=3 "No such process"
Feb 18 10:45:10 iPad assertiond[64] <Warning>: Entitlement com.apple.backboardd.debugapplications required to use kern_return_t _BKAppWatchdogXXAddAssertionForProcess(mach_port_t, pid_t, mach_port_t, audit_token_t)
Feb 18 10:45:10 iPad SpringBoard[48] <Warning>: Application 'UIKitApplication:com.testobject.waker[0xdbd6]' exited abnormally via signal.

**Comment by guillermochica** [comment]
Hi, I have a similar problem. Did you fixed it?
