### ISSUE TITLE
iPhone USB Tethering really need pairing

### ISSUE THREAD

**Issue by mikesumsun** [libimobiledevice/libimobiledevice#299]
I am working on iPhone usb  tethering,when reading ipheth driver,we can find the program ipheth-pair,
but in ubuntu,I can't find any program like this,is it the necessary of using ipheth-pair or idevicepair  to pair the current pc with iphone?

**Comment by MarcusXie** [comment]
But after paired with iPhone on Ubuntu at first time, you don't to pair again?

**Comment by MarcusXie** [comment]
iPhone USB Tethering really need pairing.
idevicepair need permission everytime, and ipheth-pair only nedd at first time.
