### ISSUE TITLE
Could ideviceinfo get some information about sim locked or carrier locked status?

### ISSUE THREAD

**Issue by jackczhang** [libimobiledevice/libimobiledevice#300]
Cloud ideviceinfo get some information about sim locked or carrier locked status?
Just like get the info about find my iphone?

**Comment by Kanong017** [comment]
sim卡锁的话,不知道你说的是那种,如果是网络锁,就只能靠建索引来判断,好像没有直接的方法
如果是sim卡的pin锁,可以得到

**Comment by daniel-bluesea** [comment]
@jackczhang did you manage to understand @Kanong017 response?

**Comment by nikias** [comment]
The only thing ideviceinfo can do is this:
```
ideviceinfo -k SIMStatus
```
If the device has a sim lock it should print ```kCTSIMSupportSIMStatusOperatorLocked```.
If the SIM is supported and ready to use it will print ```kCTSIMSupportSIMStatusReady```. Just check for yourself.

**Comment by daniel-bluesea** [comment]
SIMStatus returns the status of the currently inserted SIM card.
the carrier sim lock is a **device** status, can we get the device carrier sim lock status without the need of switching SIM cards?

**Comment by nikias** [comment]
I don't know of any way to query this information, sorry.

**Comment by daniel-bluesea** [comment]
some sites & forums claim that by using Apple GSX account and producing some kind of report you can get this (carrier sim lock) status along side with other device information.

some of this report information can be retrieved by using ideviceinfo, so i hoped that carrier sim lock status also can be retrieved by it..

**Comment by nikias** [comment]
Still, AFAIK, there is no lockdown domain or key that would allow you to get this info. GSX is out of the scope of libimobiledevice.
