### ISSUE TITLE
Cannot open shared library libmobiledevice.so.4

### ISSUE THREAD

**Issue by mrPsycho** [libimobiledevice/libimobiledevice#31]
hello, 
i'm using linux mint and tried to install new libmobiledevice

installation was without errors, but i can't use anything:
"error while loading shared libraries: libmobiledevice.so.4: cannot open shared object file: No such file or directory"

Where i should look for it? 

i checked /usr/local/lib - and there i can see  libmobiledevice.so.4 and libmobiledevice.so.4.0.1 

installation was in /usr/local

**Comment by matteyeux** [comment]
This command worked for me, thank you 
`export LD_LIBRARY_PATH=/usr/local/lib`
