### ISSUE TITLE
Any domain or keys to check battery charge cycle count?

### ISSUE THREAD

**Issue by jackczhang** [libimobiledevice/libimobiledevice#319]
Hi, is there any domain or keys to check battery charge cycle count in ideviceinfo?

**Comment by Kanong017** [comment]
ideviceinfo read cycles are not supported
If you need to buy the relevant code, you can contact me mail 820957570@qq.com

**Comment by hadess** [comment]
The answer was to run: `idevicediagnostics diagnostics`
