### ISSUE TITLE
[SOLVED] Unable to start syslog with iOS 10 on Windows

### ISSUE THREAD

**Issue by rcmpayne** [libimobiledevice/libimobiledevice#325]
ERROR: Could not start service com.apple.syslog_relay.
Could not start logger for udid 860e4312********75442b0ec351

iOS 9.3.2 is working fine

**Comment by rcmpayne** [comment]
updating new logs with debug enabled

15:08:25 service.c:143 service_send(): ERROR: sending to device failed.
15:08:25 property_list_service.c:142 internal_plist_send(): ERROR: sending to device failed.
15:08:25 service.c:163 service_receive_with_timeout(): could not read data
15:08:25 lockdown.c:267 lockdownd_stop_session(): LOCKDOWN_E_PLIST_ERROR
15:08:25 service.c:85 service_client_factory_start_service(): Could not create a lockdown client.
ERROR: Could not start service com.apple.syslog_relay.

Could not start logger for udid 4e8e93bd2a401c34e3d0d257de07af5d624521c6


full log: http://pastebin.com/JNkapx9t

**Comment by Kanong017** [comment]
The same problem, I do not know how to resolve

**Comment by nikias** [comment]
You need to recompile with latest libimobiledevice code for it to work.

**Comment by rcmpayne** [comment]
fixed with new libs  made a copy here if anyone wants  https://github.com/rcmpayne/libimobiledevice-Compiled-Windows

**Comment by mushtaque87** [comment]
What about MAC .. I have the same problem in MAC ..

**Comment by guyromb** [comment]
I have the same issue on OS X 10 + iOS 10. Any suggestions how to fix it? I use the latest version 1.2.0

**Comment by jonathancochran** [comment]
+1

**Comment by nikias** [comment]
Please please. Before reporting an issue compile the latest code from git. Thanks.

**Comment by ngalin** [comment]
Hi, just compiled the latest code, and get the same error (using iOS10):
ERROR: Could not start service com.apple.syslog_relay.
Could not start logger for udid a3***etcetc

**Comment by johnavink** [comment]
I installed using brew:

brew install -v --fresh automake autoconf libtool wget libimobiledevice
brew install -v --HEAD --fresh --build-from-source ideviceinstaller

I get the same error on Mac OS X 10.11.6 and iOS 9.3.5.

> idevicesyslog
ERROR: Could not start service com.apple.syslog_relay.
Could not start logger for udid b685************6a99

**Comment by johnavink** [comment]
I have solved my issue:

> sudo chmod 777 /var/db/lockdown

**Comment by JanC** [comment]
Hi
same issue for me.
> Please please. Before reporting an issue compile the latest code from git. Thanks.

I did 
- `brew install -v --fresh automake autoconf libtool wget libimobiledevice`
- `brew install -v --HEAD --fresh --build-from-source ideviceinstaller`
- `sudo chmod 777 /var/db/lockdown`

:/

**Comment by jpjodoin** [comment]
@JanC:
I had the same issue. This did the trick
brew install -v --HEAD --fresh --build-from-source libimobiledevice

**Comment by jacinzhang** [comment]
@JanC  I don't have `/var/db/lockdown` file on my iPhone.

**Comment by mbektchiev** [comment]
I tried installing `libimobiledevice` for the first time today, but got the `ERROR: Could not start service com.apple.syslog_relay.`. I'm not sure what had gone wrong, but this is what fixed it for me:

```
brew uninstall -f libimobiledevice ideviceinstaller usbmuxd
brew install -v --HEAD --fresh --build-from-source usbmuxd libimobiledevice ideviceinstaller
```

**Comment by Nisim761** [comment]
> brew install -v --HEAD --fresh --build-from-source libimobiledevice

Tried that (the "--fresh" flag seems to be invalid) - didn't work.

**Comment by scugn1zz0** [comment]
@Nisim761 I did exactly what @mbektchiev said in the previous comment, just without `--fresh` (because I got invalid flag as well) and everything worked like a charm 🤩

**Comment by ankitguptatest** [comment]
> Hi
> same issue for me.
> 
> > Please please. Before reporting an issue compile the latest code from git. Thanks.
> 
> I did
> 
> * `brew install -v --fresh automake autoconf libtool wget libimobiledevice`
> * `brew install -v --HEAD --fresh --build-from-source ideviceinstaller`
> * `sudo chmod 777 /var/db/lockdown`
> 
> :/

Getting below error with this command: 

Error: invalid option: --fresh

**Comment by ankitguptatest** [comment]
Remove data in /var/db/lockdown directory worked for me:

-> cd /var/db/lockdown
-> rm -rf *

**Comment by jackie-d** [comment]
> I tried installing `libimobiledevice` for the first time today, but got the `ERROR: Could not start service com.apple.syslog_relay.`. I'm not sure what had gone wrong, but this is what fixed it for me:
> 
> ```
> brew uninstall -f libimobiledevice ideviceinstaller usbmuxd
> brew install -v --HEAD --fresh --build-from-source usbmuxd libimobiledevice ideviceinstaller
> ```

Give this men a medal
