### ISSUE TITLE
Can skip set up activation via libimobiledevice ?

### ISSUE THREAD

**Issue by truonggiang0710** [libimobiledevice/libimobiledevice#330]
I have an iPhone 5 that just restore to 9.3.2.
I'm very lazy. So I want to active my iPhone with skip all set up ( same as Apple configurator 2 ). 
Can libimobiledevice do that ?
Please help me when you have free time!

Thanks a lot !

**Comment by truonggiang0710** [comment]
Can anybody help me, please ? I just want to skip Language screen and Region screen.
Please drop me some information when you're free.
Thanks a lot !

**Comment by FunkyM** [comment]
No, libimobiledevice can not currently do it although it is possible. I also doubt that you are lazy.

**Comment by truonggiang0710** [comment]
Hi ! In some case, laziness will make the world better !
Thanks a lot for your response !

**Comment by iOSShohrab** [comment]
@truonggiang0710 did you able to get any solution for this?

**Comment by truonggiang0710** [comment]
@iOSShohrab Yes, I find out !

**Comment by iamluosm** [comment]
Hi man, how did you do that ?

**Comment by truonggiang0710** [comment]
@iamluosm sorry. But I don't have permisson to show it for you here. Please contact to me over email dotruonggiang88@gmail.com

**Comment by Roger-mazheng** [comment]
hi man,how did you du that? can you tell me?  i need the solution.

**Comment by yunhailu** [comment]
> hi man,how did you du that? can you tell me? i need the solution.

Have you solved this problem?

**Comment by mroger-tech** [comment]
> > hi man,how did you du that? can you tell me? i need the solution.
> 
> Have you solved this problem?


Yes,i did it,try the following code.


lockdownd_client_t lockdown = NULL;
	lockdownd_error_t ret = LOCKDOWN_E_UNKNOWN_ERROR;

	if (LOCKDOWN_E_SUCCESS != (ret = lockdownd_client_new_with_handshake(device, &lockdown, "skipsetup"))) {
		printf("ERROR: Could not connect to lockdownd, error code %d\n", ret);
		result = -3;
		goto cleanup;
	}

	if (lockdownd_set_value(lockdown, "com.apple.international", "Locale", plist_new_string("zh_CN")) == LOCKDOWN_E_SUCCESS) {
		printf("set Locale [zh_CN]\n");
	}
	if (lockdownd_set_value(lockdown, "com.apple.international", "Language", plist_new_string("zh-Hans")) == LOCKDOWN_E_SUCCESS) {
		printf("set Language [zh-Hans]\n");
	}
	if (lockdownd_set_value(lockdown, "com.apple.purplebuddy", "SetupDone", plist_new_bool(1)) == LOCKDOWN_E_SUCCESS) {
		printf("set SetupDone [true]\n");
	}
	if (lockdownd_set_value(lockdown, "com.apple.purplebuddy", "SetupFinishedAllSteps", plist_new_bool(1)) == LOCKDOWN_E_SUCCESS) {
		printf("set SetupFinishedAllSteps [true]\n");
	}
	if (lockdownd_set_value(lockdown, "com.apple.purplebuddy", "ForceNoBuddy", plist_new_bool(1)) == LOCKDOWN_E_SUCCESS) {
		printf("set ForceNoBuddy [true]\n");
	}
	else {
		printf("ERROR:set ForceNoBuddy failed\n");
		result = -4;
		goto cleanup;
	}

**Comment by Lbywer** [comment]
> > > > hi man,how did you du that? can you tell me? i need the solution.
> > > 
> > > 
> > > Have you solved this problem?
> > 
> > 
> > Yes,i did it,try the following code.
> > lockdownd_client_t lockdown = NULL; lockdownd_error_t ret = LOCKDOWN_E_UNKNOWN_ERROR;
> > ```
> > if (LOCKDOWN_E_SUCCESS != (ret = lockdownd_client_new_with_handshake(device, &lockdown, "skipsetup"))) {
> > 	printf("ERROR: Could not connect to lockdownd, error code %d\n", ret);
> > 	result = -3;
> > 	goto cleanup;
> > }
> > 
> > if (lockdownd_set_value(lockdown, "com.apple.international", "Locale", plist_new_string("zh_CN")) == LOCKDOWN_E_SUCCESS) {
> > 	printf("set Locale [zh_CN]\n");
> > }
> > if (lockdownd_set_value(lockdown, "com.apple.international", "Language", plist_new_string("zh-Hans")) == LOCKDOWN_E_SUCCESS) {
> > 	printf("set Language [zh-Hans]\n");
> > }
> > if (lockdownd_set_value(lockdown, "com.apple.purplebuddy", "SetupDone", plist_new_bool(1)) == LOCKDOWN_E_SUCCESS) {
> > 	printf("set SetupDone [true]\n");
> > }
> > if (lockdownd_set_value(lockdown, "com.apple.purplebuddy", "SetupFinishedAllSteps", plist_new_bool(1)) == LOCKDOWN_E_SUCCESS) {
> > 	printf("set SetupFinishedAllSteps [true]\n");
> > }
> > if (lockdownd_set_value(lockdown, "com.apple.purplebuddy", "ForceNoBuddy", plist_new_bool(1)) == LOCKDOWN_E_SUCCESS) {
> > 	printf("set ForceNoBuddy [true]\n");
> > }
> > else {
> > 	printf("ERROR:set ForceNoBuddy failed\n");
> > 	result = -4;
> > 	goto cleanup;
> > }
> > ```
> 
> Hello @mroger-tech , does this make sense for iOS16.4+ devices ? As far as checked - no, may be you have some ideas about how to bypass Setup app on latest iOS versions?

hello, when i try this for iOS 14+ devices? its failed. do you have any idea with this. best glad.

**Comment by ScottPierce** [comment]
@mroger-tech Have you gotten this working for iphone 16+?
