### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by cbowns** [libimobiledevice/libimobiledevice#340]
The last release of libimobiledevice was 1.2.0 in January of 2015, which is 26 very important commits behind HEAD. Can you tag a new release? (This will let me submit a PR to `homebrew` to take this newer version; if it's just built from HEAD, it's a separate release process.)

**Comment by FunkyM** [comment]
Closing as version [1.3.0](/libimobiledevice/libimobiledevice/releases/tag/1.3.0) has been released.
