### ISSUE TITLE
why the backup always do the force full-backup?

### ISSUE THREAD

**Issue by lianzisong** [libimobiledevice/libimobiledevice#366]
in fact ,I don't use the source code on the github . 
but the backup indeed can be successful .
and I don't set the "ForceFullBackup" option , everytime the backup in full-backup mode.
the snapshot folder can always has thousands files in it.

here is the question ,:
how the ios device decide which files to upload to the file to PC?  the time or sth else?
please help me. thanks.

**Comment by mexmer** [comment]
not sure about io10, but in elder ioses phone downloads manifest.mdbd from PC as first step of backup, i suspect it compares timestamps and hashes of files, then sends differential backup, unless full is requested.

if you delete existing backup folder (or manifest file), full will always be done.
