### ISSUE TITLE
[lockdown] Error: saving pair record failed: -22

### ISSUE THREAD

**Issue by MarcusXie** [libimobiledevice/libimobiledevice#367]
I'm trying to port libimobiledevice and usbmuxd to a specific android platform.
a few problems happens.

Now when usbmuxd detected the Apple device, 
1. And trying perform [idevicepair pair] failed.
2. and error log:  **D/libusbmuxd(  234): usbmuxd_save_pair_record: Error: saving pair record failed: -22**
3. then print [SUCCESS: Paired with device c1ab1f256*******************dca377ca308] .
4. and no 40bit.plist generated.

any hint? thanks.

**Comment by mexmer** [comment]
saving pair record failed means, that usbmuxd doesn't have write access to directory, where you define it should save pairing data,

it can be either permission issue, or simply that directory doesn't exists.

**Comment by MarcusXie** [comment]
I modified as Ubuntu do, and problem solved.
Issue close.

**Comment by joeasy** [comment]
I have same problem on android platform, could you please kindly tell me how to solve this problem "usbmuxd_save_pair_record: Error: saving pair record failed: -22".

**Comment by MarcusXie** [comment]
I do it as ubuntu do, which is different from android(I think).
You could run "apt-get source usbmuxd" such thing, to get the source code from ubuntu.
apt-get source libimobiledevice and libusbmuxd2 maybe.
