### ISSUE TITLE
usbmuxd_send: Error -1 when sending: Broken Pipe after iOS 10 Update

### ISSUE THREAD

**Issue by sdcinglis** [libimobiledevice/libimobiledevice#375]
Not sure if this is directly related to the update or just coincidental but every time I try to run idevicesyslog I get:

`usbmuxd_send: Error -1 when sending: Broken pipe`

**Comment by JohanDegraeve** [comment]
same here with iOS 10

**Comment by hgcncn** [comment]
My iPhone6(iOS10.1) is with the same problem.
iPhone5(iOS8.3) is ok.

**Comment by samrocketman** [comment]
What version of libimobiledevice are you using?  I'm using the latest master (see compile instructions I wrote down at https://gist.github.com/samrocketman/70dff6ebb18004fc37dc5e33c259a0fc).  I don't have any more problems with iOS 10 after compiling the latest master.
