### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by kirb** [libimobiledevice/libimobiledevice#380]
The latest release of libimobiledevice is 1.2.0, released almost 2 years ago now. This release [no longer works](https://github.com/libimobiledevice/libimobiledevice/issues?utf8=%E2%9C%93&q=could%20not%20connect%20to%20lockdownd) with recent iTunes releases. Package managers tend to only release updates for a package when upstream does a release, especially Homebrew which heavily distinguishes between "released" (what you get by default) and "unreleased" (what you get by using `--HEAD`).

Is it possible that we could see a new release in the near future, and possibly, regular-ish releases following that?

**Comment by Iragne** [comment]
+1

**Comment by michalstefanowski** [comment]
+1

**Comment by domesticmouse** [comment]
+1

**Comment by ledinhphuong** [comment]
Yes, please

**Comment by txaj** [comment]
+1

This also prevents Debian from packaging a working release.

(Duplicates #340)

**Comment by TheElectronWill** [comment]
definitely +1 !

**Comment by songhaonangit** [comment]
+1

**Comment by andbene72** [comment]
+1

**Comment by inspectionsbybob** [comment]
+1

**Comment by songhaonangit** [comment]
+1

**Comment by TheElectronWill** [comment]
@nikias Any plan to do it?

**Comment by nikias** [comment]
@TheElectronWill yes soonish

**Comment by jespinal** [comment]
+1

I'm trying to reach a recently updated (2016-10-30 20:45:00) iPhone 6s+ and get this on Ubuntu MATE 16.04.1:

GnuTLS error: Error in the pull function.
ERROR: Could not connect to lockdownd, error code -5

Unfortunately there's no package update until a new release is available.

**Comment by songhaonangit** [comment]
+1

**Comment by nicolassan** [comment]
+1

**Comment by cooloutac** [comment]
+1

**Comment by andreeppinghaus** [comment]
+1

**Comment by exa-soft** [comment]
+1

**Comment by rafaelescrich** [comment]
+1

**Comment by gso** [comment]
+1

**Comment by itishenko** [comment]
+1

**Comment by TheElectronWill** [comment]
@nikias gentle reminder :-)

**Comment by Frederick888** [comment]
Grrrrr.... the AUR version hasn't been update for quite long, either... +1...

**Comment by TheElectronWill** [comment]
For those who need the lastest libimobiledevice, here are some helpful links:

- [M. Salbaba's Ubuntu PPA](https://launchpad.net/~martin-salbaba/+archive/ubuntu/ppa+libimobiledevice)
It isn't completely up to date with the upstream libimobiledevice, but it should be enough for working properly with iOS 10. (I haven't tested it since I don't use Ubuntu).
- [My script to build an RPM package of the upstream version](https://github.com/RPM-Outpost/libimobiledevice)
I've made a shell script that downloads the latest (unreleased) version of libimobiledevice and create a ready-to-use RPM package.

**Comment by AlexJinsin** [comment]
#188 --HEAD can fix -21

**Comment by jrmhaig** [comment]
Yes, `--HEAD` fixes it because that is installing from the current head on Github. This is generally not a good thing to do as you could end up with unexpected changes. However, in this case it is the only option until there is a new release.

**Comment by samrocketman** [comment]
For those who can't wait for a release, I've published a guide of how I built libimobiledevice for myself on GNU/Linux.  Perhaps you may benefit.  https://gist.github.com/samrocketman/70dff6ebb18004fc37dc5e33c259a0fc

**Comment by supermarin** [comment]
Seriously, please get this released

**Comment by wbob** [comment]
including this one, I count 7 "new release" threads to date (#631 #585 #456 #405 #401 #340), being testament to the importance of the library. I just noticed [libimobiledevice.org](https://www.libimobiledevice.org/) has a donate button with a customizable message. Though I guess most current distributions will now package from a git commit, I think it's a way to show appreciation and make your voices heard.

**Comment by FunkyM** [comment]
Closing as version [1.3.0](/libimobiledevice/libimobiledevice/releases/tag/1.3.0) has been released.
