### ISSUE TITLE
restore apps

### ISSUE THREAD

**Issue by daniel-bluesea** [libimobiledevice/libimobiledevice#381]
@nikias @FunkyM is it planed for libimobiledevice to support restore applications (transfer purchased) as itunes does?

**Comment by nikias** [comment]
This doesn't work anymore as of iOS 9 (or was it 8?). Apple removed the 'Archive' functionality from installation proxy.

**Comment by daniel-bluesea** [comment]
i think i mixed up 2 separated issues (restore applications & transfer purchased).
any way i think you can close this issue because a more detailed discussion is available at: https://github.com/libimobiledevice/libimobiledevice/issues/343
