### ISSUE TITLE
ERROR: Could not connect to lockdownd, error code -19

### ISSUE THREAD

**Issue by romainlouvet** [libimobiledevice/libimobiledevice#391]
When I execute command `idevicesdiagnostics restart` I have:

`ERROR: Could not connect to lockdownd, error code -19`

iPhone 6+ / iOS 8.4.1 / iTunes 12.5.1.24
If I restart manually my device I have same error

**Comment by romainlouvet** [comment]
`brew install libimobiledevice --HEAD` resolve my problem 👍

**Comment by Thiagu100** [comment]
Try this, 
sudo chmod -R 777 /var/db/lockdown/

**Comment by crummy** [comment]
@Thiagu100 After running that command, I get `ERROR: Could not connect to lockdownd, error code -5`

**Comment by ltpquang** [comment]
> Try this,
> sudo chmod -R 777 /var/db/lockdown/

This doesn't work, since `/var/db/lockdown/` is owned by `_usbmuxd`

```
drwx------   15 _usbmuxd _usbmuxd   480 Nov 10 14:19 lockdown
```

**Comment by camic** [comment]
ideviceinfo
ERROR: Could not connect to lockdownd: Pairing dialog response pending (-19)

ls -l /var/lib/lockdown/
total 16
-rw-r--r-- 1 usbmux plugdev 9401 Mar  4 09:55

this is latest libmobile device on debian bullseye latest

**Comment by Geczy** [comment]
```
pi@raspberrypi:~ $ sudo chmod -R 777 /var/lib/lockdown
pi@raspberrypi:~ $ ideviceinfo
ERROR: Could not connect to lockdownd: Pairing dialog response pending (-19)
```

how do i fix it?

**Comment by mexmer** [comment]
message is selfeplaining, there is dialog on your ios device that ask you to confirm trust/pairing with computer, untill you confirm dialog on device, it will not continue.

**Comment by Geczy** [comment]
yeah my bad 😂 saw the msg after i unlocked the phone
