### ISSUE TITLE
warnings showed during build the project

### ISSUE THREAD

**Issue by qqtester** [libimobiledevice/libimobiledevice#397]
![image](https://cloud.githubusercontent.com/assets/16013057/19231166/119c4418-8f0b-11e6-9978-9211e33b1b59.png)

any idea for this? guys.

**Comment by mexmer** [comment]
deprecated methods, that were replaced with new ones in new version of SSL.
it will need code update, but for now, you can ignore them.

**Comment by qqtester** [comment]
@mexmer ,ok. I got it. thx. 
could you take a look at #383 , after build success. run idevice_id -l. the message showed as the screenshot.
