### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by zx2c4** [libimobiledevice/libimobiledevice#401]
The most recent release of libimobiledevice doesn't work with the latest devices. Please make a release so we can have it in distros.

**Comment by LinuxDonald** [comment]
https://github.com/libimobiledevice/libimobiledevice/issues/380

https://github.com/libimobiledevice/libimobiledevice/issues/340

**Comment by zx2c4** [comment]
Welp, can this happen?

**Comment by songhaonangit** [comment]
+1

**Comment by FunkyM** [comment]
Closing as version [1.3.0](/libimobiledevice/libimobiledevice/releases/tag/1.3.0) has been released.
