### ISSUE TITLE
Anyway to install new IPCC file by libimobiledevice ?

### ISSUE THREAD

**Issue by quangnhut123** [libimobiledevice/libimobiledevice#411]
Now i need to test something with new ipcc file for my current network. But i wonder how to install it by my C# tool via this lib ?
Thanks

**Comment by nikias** [comment]
ideviceinstaller can install ipcc.

**Comment by quangnhut123** [comment]
But ideviceinstaller can work without iTunes and work with IOS 10 ?

**Comment by nikias** [comment]
of course. it uses libimobiledevice: https://github.com/libimobiledevice/ideviceinstaller

**Comment by nikias** [comment]
Just make sure you're using the latest code from git.

**Comment by quangnhut123** [comment]
I see ideviceinstaller need some dependencies like : libimobiledevice, libplist, libzip
So how to i can compile with latest code from git in Visual Studio 2015 to make an exe and dll work in windows ?

**Comment by nikias** [comment]
Of course it has dependencies! How would it work without libimobiledevice if it's using libimobiledevice? Visual Studio building is not supported. I mean, you can try it but it will probably fail. Building with MinGW works just fine.

**Comment by quangnhut123** [comment]
MinGW i hear that name before but it can build whole this project by checkout and build to exe or dll can run on windows ?

**Comment by nikias** [comment]
You can build all required libraries and tools with MinGW.
