### ISSUE TITLE
idevicebackup2: get_uuid writing past allocated memory

### ISSUE THREAD

**Issue by schuylerdaddy** [libimobiledevice/libimobiledevice#412]
A simple bug I wanted to point out for you guys.  A char* is allocating 32 bytes and then writing a null terminator at byte 33.

![image](https://cloud.githubusercontent.com/assets/7709596/19935022/3e87d4d0-a0de-11e6-93cc-069c6fa65d32.png)

**Comment by nikias** [comment]
Whoopsie. Fixed with commit https://github.com/libimobiledevice/libimobiledevice/commit/8c37b9ca13211c197f3452356b73114c39f549fd

**Comment by schuylerdaddy** [comment]
NP!

**Comment by samrocketman** [comment]
I am amused :-D
