### ISSUE TITLE
if (operation_ok && mb2_status_check_snapshot_state(backup_directory, udid, "finished")) == Backup Successful ???

### ISSUE THREAD

**Issue by xdeng** [libimobiledevice/libimobiledevice#419]
in  idevicebackup2.c   2278  line

if (operation_ok && mb2_status_check_snapshot_state(backup_directory, udid, "finished")) {
						PRINT_VERBOSE(1, "Backup Successful.\n");

in  idevicebackup2.c   499 line

if  "Status.plist"  file does not exist   mb2_status_check_snapshot_state  return default val  -1;

**Comment by xdeng** [comment]
in idevicebackup2.c 499 line         int ret = -1;  change   int ret = 0;   ?

**Comment by nikias** [comment]
Oh wow. Good catch. Fixed: https://github.com/libimobiledevice/libimobiledevice/commit/c7f24a92f29180b50c0d92df34310f2179ba24cb
