### ISSUE TITLE
The latest libplist make idevicerestore errors [ipsw_get_latest_fw: ERROR: Can't find MobileDeviceSoftwareVersionsByVersion dict in version data]

### ISSUE THREAD

**Issue by jackczhang** [libimobiledevice/libimobiledevice#423]
The latest libplist make idevicerestore errors [ipsw_get_latest_fw: ERROR: Can't find MobileDeviceSoftwareVersionsByVersion dict in version data]

**Comment by nikias** [comment]
https://github.com/libimobiledevice/libplist/issues/80
