### ISSUE TITLE
Libimobiledevice causes the virtual machine to crash

### ISSUE THREAD

**Issue by onesecurity** [libimobiledevice/libimobiledevice#428]
When installed on the libimobiledevice, the use of USB will lead to the collapse of the virtual machine.

![image](https://cloud.githubusercontent.com/assets/1908897/20860920/659b22b8-b9be-11e6-91df-161ea02561d2.png)

VMware Fusion encountered an error and has shut down the virtual machine.

**Comment by nikias** [comment]
I doubt that it's libimobiledevice. It must be something else. Check the VMware logs on what caused the machine to freeze.
