### ISSUE TITLE
ideviceprovision should be able to remove all provisioning profiles

### ISSUE THREAD

**Issue by oclbdk** [libimobiledevice/libimobiledevice#434]
# Impact

This will make it much easier to manage provisioning profiles and ensure that signatures are correct

Developers may want to clear all old provisioning profiles to validate that their new provisioning profiles are correct -- iOS only validates the provisioning profile embedded in an app if none of the installed ones work

Sometimes it can be inconvenient to retrieve the UUID (e.g. https://github.com/libimobiledevice/libimobiledevice/issues/432), and it's tedious to run `ideviceprovision list`, parse out the UUID's, then run `ideviceprovision remove` on each of them

# Fix

This is the relevant source file: https://github.com/libimobiledevice/libimobiledevice/blob/master/tools/ideviceprovision.c

Some options for how this could work:

## 1) Add a new command

```
ideviceprovision remove-all
```

This makes it more explicit and more difficult to do accidentally

## 2) Add a special case to remove all of them if there are no parameters

```
ideviceprovision remove
```

This makes it consistent with `ideviceprovision copy`

**Comment by nikias** [comment]
Cool idea. I updated the code: https://github.com/libimobiledevice/libimobiledevice/commit/d936514291c0f65ecb0448f3a4aad1b40517f468
