### ISSUE TITLE
Undefined symbols for architecture

### ISSUE THREAD

**Issue by jjtny1** [libimobiledevice/libimobiledevice#44]
I was installing libimobledevice on my mac when i encountered this error:

Undefined symbols for architecture x86_64:
  "_debug_buffer", referenced from:
      _afc_dispatch_packet in afc.o
      _afc_receive_data in afc.o
      _afc_file_lock in afc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [libimobiledevice.la] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

I have searched and searched but can not find a solution. Can anyone please help?

**Comment by jflow** [comment]
I seem to be having a similar issue about undefined symbols on x86_64 for OS X 10.11
Errors:
Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      _internal_idevice_deinit in idevice.o
      _idevice_connection_enable_ssl in idevice.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libimobiledevice.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
