### ISSUE TITLE
[help] compile error in macOS 10.12.1 using latest libimobiledevice code

### ISSUE THREAD

**Issue by krisdyZJU** [libimobiledevice/libimobiledevice#440]
I search in the history issues list, not found the similar error log like mine.

error code below when I try to execute 'make' in libimobiledevice folder:

> Making all in common
make[2]: Nothing to be done for `all'.
Making all in src
  CCLD     libimobiledevice.la
Undefined symbols for architecture x86_64:
  "_plist_access_path", referenced from:
      _instproxy_client_get_path_for_bundle_identifier in installation_proxy.o
  "_plist_array_append_item", referenced from:
      _device_link_service_version_exchange in device_link_service.o
      _device_link_service_disconnect in device_link_service.o
      _device_link_service_send_ping in device_link_service.o
      _device_link_service_send_process_message in device_link_service.o
      _file_relay_request_sources_timeout in file_relay.o
      _instproxy_append_current_list_to_result_cb in installation_proxy.o
      _instproxy_lookup in installation_proxy.o
      ...
  "_plist_array_get_item", referenced from:
      _device_link_service_version_exchange in device_link_service.o
      _device_link_service_get_message in device_link_service.o
      _device_link_service_receive_process_message in device_link_service.o
      _lockdownd_get_sync_data_classes in lockdown.o
      _instproxy_append_current_list_to_result_cb in installation_proxy.o
      _mobilesync_start in mobilesync.o
      _mobilesync_finish in mobilesync.o
      ...
  "_plist_array_get_size", referenced from:
      _device_link_service_version_exchange in device_link_service.o
      _device_link_service_get_message in device_link_service.o
      _device_link_service_receive_process_message in device_link_service.o
      _instproxy_status_get_current_list in installation_proxy.o
      _mobilebackup_send_restore_complete in mobilebackup.o
      _plist_dict_print_to_stream in libinternalcommon.a(utils.o)
      _plist_array_print_to_stream in libinternalcommon.a(utils.o)
      ...
  "_plist_copy", referenced from:
      _device_link_service_send_process_message in device_link_service.o
      _device_link_service_receive_process_message in device_link_service.o
      _lockdownd_get_value in lockdown.o
      _lockdownd_do_pair in lockdown.o
      _lockdownd_activate in lockdown.o
      _lockdownd_build_start_service_request in lockdown.o
      _instproxy_browse_with_callback in installation_proxy.o
      ...
  "_plist_dict_get_item", referenced from:
      _lockdown_check_result in lockdown.o
      _lockdownd_query_type in lockdown.o
      _lockdownd_get_value in lockdown.o
      _lockdownd_start_session in lockdown.o
      _lockdownd_do_pair in lockdown.o
      _lockdownd_do_start_service in lockdown.o
      _lockdownd_build_start_service_request in lockdown.o
      ...
  "_plist_dict_new_iter", referenced from:
      _plist_dict_print_to_stream in libinternalcommon.a(utils.o)
  "_plist_dict_next_item", referenced from:
      _plist_dict_print_to_stream in libinternalcommon.a(utils.o)
  "_plist_dict_remove_item", referenced from:
      _lockdownd_do_pair in lockdown.o
  "_plist_dict_set_item", referenced from:
      _lockdownd_stop_session in lockdown.o
      _plist_dict_add_label in lockdown.o
      _lockdownd_query_type in lockdown.o
      _lockdownd_get_value in lockdown.o
      _lockdownd_set_value in lockdown.o
      _lockdownd_remove_value in lockdown.o
      _lockdownd_pair in lockdown.o
      ...
  "_plist_free", referenced from:
      _idevice_connection_enable_ssl in idevice.o
      _device_link_service_version_exchange in device_link_service.o
      _device_link_service_disconnect in device_link_service.o
      _device_link_service_send_ping in device_link_service.o
      _device_link_service_send_process_message in device_link_service.o
      _device_link_service_receive_process_message in device_link_service.o
      _lockdownd_stop_session in lockdown.o
      ...
  "_plist_from_bin", referenced from:
      _internal_plist_receive_timeout in property_list_service.o
      _webinspector_receive_with_timeout in webinspector.o
      _userpref_read_pair_record in libinternalcommon.a(userpref.o)
      _plist_read_from_filename in libinternalcommon.a(utils.o)
  "_plist_from_xml", referenced from:
      _internal_plist_receive_timeout in property_list_service.o
      _userpref_read_pair_record in libinternalcommon.a(userpref.o)
      _plist_read_from_filename in libinternalcommon.a(utils.o)
  "_plist_get_bool_val", referenced from:
      _lockdownd_start_session in lockdown.o
      _lockdownd_do_start_service in lockdown.o
      _mobilesync_receive_changes in mobilesync.o
      _plist_node_print_to_stream in libinternalcommon.a(utils.o)
  "_plist_get_data_val", referenced from:
      _lockdownd_get_device_public_key_as_key_data in lockdown.o
      _sbservices_get_icon_pngdata in sbservices.o
      _sbservices_get_home_screen_wallpaper_pngdata in sbservices.o
      _screenshotr_take_screenshot in screenshotr.o
      _webinspector_receive_with_timeout in webinspector.o
      _pair_record_get_item_as_key_data in libinternalcommon.a(userpref.o)
      _plist_node_print_to_stream in libinternalcommon.a(utils.o)
      ...
  "_plist_get_date_val", referenced from:
      _plist_node_print_to_stream in libinternalcommon.a(utils.o)
  "_plist_get_key_val", referenced from:
      _plist_node_print_to_stream in libinternalcommon.a(utils.o)
  "_plist_get_node_type", referenced from:
      _device_link_service_get_message in device_link_service.o
      _device_link_service_send_process_message in device_link_service.o
      _plist_dict_add_label in lockdown.o
      _lockdown_check_result in lockdown.o
      _lockdownd_query_type in lockdown.o
      _lockdownd_start_session in lockdown.o
      _lockdownd_do_pair in lockdown.o
      ...
  "_plist_get_real_val", referenced from:
      _mobilebackup2_version_exchange in mobilebackup2.o
      _plist_node_print_to_stream in libinternalcommon.a(utils.o)
  "_plist_get_string_val", referenced from:
      _device_link_service_get_message in device_link_service.o
      _lockdown_check_result in lockdown.o
      _lockdownd_query_type in lockdown.o
      _lockdownd_get_device_udid in lockdown.o
      _lockdownd_get_device_name in lockdown.o
      _lockdownd_start_session in lockdown.o
      _lockdownd_do_pair in lockdown.o
      ...
  "_plist_get_uint_val", referenced from:
      _device_link_service_version_exchange in device_link_service.o
      _lockdownd_do_start_service in lockdown.o
      _instproxy_status_get_error in installation_proxy.o
      _instproxy_status_get_percent_complete in installation_proxy.o
      _instproxy_status_get_current_list in installation_proxy.o
      _sbservices_get_interface_orientation in sbservices.o
      _mobilesync_start in mobilesync.o
      ...
  "_plist_new_array", referenced from:
      _device_link_service_version_exchange in device_link_service.o
      _device_link_service_disconnect in device_link_service.o
      _device_link_service_send_ping in device_link_service.o
      _device_link_service_send_process_message in device_link_service.o
      _file_relay_request_sources_timeout in file_relay.o
      _instproxy_browse in installation_proxy.o
      _instproxy_lookup in installation_proxy.o
      ...
  "_plist_new_bool", referenced from:
      _lockdownd_pair in lockdown.o
      _instproxy_client_options_add in installation_proxy.o
      _create_process_changes_message in mobilesync.o
      _mobilesync_actions_add in mobilesync.o
      _mobilebackup_request_restore in mobilebackup.o
      _internal_diagnostics_relay_action in diagnostics_relay.o
  "_plist_new_data", referenced from:
      _lockdownd_pair_record_to_plist in lockdown.o
      _mobile_image_mounter_upload_image in mobile_image_mounter.o
      _mobile_image_mounter_mount_image in mobile_image_mounter.o
      _webinspector_send in webinspector.o
      _pair_record_set_item_from_key_data in libinternalcommon.a(userpref.o)
  "_plist_new_dict", referenced from:
      _lockdownd_stop_session in lockdown.o
      _lockdownd_query_type in lockdown.o
      _lockdownd_get_value in lockdown.o
      _lockdownd_set_value in lockdown.o
      _lockdownd_remove_value in lockdown.o
      _lockdownd_pair in lockdown.o
      _lockdownd_start_session in lockdown.o
      ...
  "_plist_new_real", referenced from:
      _mobilebackup2_version_exchange in mobilebackup2.o
  "_plist_new_string", referenced from:
      _device_link_service_version_exchange in device_link_service.o
      _device_link_service_disconnect in device_link_service.o
      _device_link_service_send_ping in device_link_service.o
      _device_link_service_send_process_message in device_link_service.o
      _lockdownd_stop_session in lockdown.o
      _plist_dict_add_label in lockdown.o
      _lockdownd_query_type in lockdown.o
      ...
  "_plist_new_uint", referenced from:
      _device_link_service_version_exchange in device_link_service.o
      _mobile_image_mounter_upload_image in mobile_image_mounter.o
      _mobilesync_start in mobilesync.o
      _mobilebackup2_send_status_response in mobilebackup2.o
      _restored_start_restore in restore.o
  "_plist_to_bin", referenced from:
      _internal_plist_send in property_list_service.o
      _webinspector_send in webinspector.o
      _userpref_save_pair_record in libinternalcommon.a(userpref.o)
      _plist_write_to_filename in libinternalcommon.a(utils.o)
  "_plist_to_xml", referenced from:
      _internal_plist_send in property_list_service.o
      _plist_write_to_filename in libinternalcommon.a(utils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libimobiledevice.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

the environment situation of my mac:

> macOS Sierra 10.12.1
XCode version: 8.2

bash profile related:

> export libplist_CFLAGS='-I/usr/local/opt/libplist/include'
export libplist_LIBS='-L/usr/local/opt/libplist/lib'
export libplistmm_CFLAGS='-I/usr/local/opt/libplist/include'
export libplistmm_LIBS='-L/usr/local/opt/libplist/lib'
export CFLAGS='-I/usr/local/opt/openssl/include'
export LDFLAGS='-L/usr/local/opt/openssl/lib'

Can anyone met this problem before, any help is appreciated, thanks!

**Comment by krisdyZJU** [comment]
my openssl version is : OpenSSL 1.0.2h

**Comment by krisdyZJU** [comment]
@nikias @FunkyM 
really sorry to bother you, but can you pls help to take a look, thanks

**Comment by mexmer** [comment]
your build is missing libplist. did you run configure, and did it find libplist?

**Comment by krisdyZJU** [comment]
@mexmer yes, I run ./autogen.sh before I run make, and it can find libplist and libplistmm both: 

> .....
checking for libplist... yes
checking for libplistmm... yes
...........
Configuration for libimobiledevice 1.2.1:
-------------------------------------------

  Install prefix: .........: /usr/local
  Debug code ..............: no
  Python bindings .........: no
  SSL support backend .....: OpenSSL

  Now type 'make' to build libimobiledevice 1.2.1,
  and then 'make install' for installation.

**Comment by krisdyZJU** [comment]
Fixed now.
Previously, I use brew to install libplist. I just uninstall libplist and compile it from scratch using source code, and it works now.
So I just close it, thanks all.
