### ISSUE TITLE
get problem with afc_receive_data() function

### ISSUE THREAD

**Issue by perfectplug** [libimobiledevice/libimobiledevice#45]
I build libimobiledevice in windows 32bit with VS2008 ,when I build the afccheck.c and ideviceinstaller.c , I mean the program can run ,but It failed when the afc_receive_data() function called .
the error information below:
internal_plist_receive_timeout>>received 334 bytes
afc_lock>>Locked
afc_dispatch_packet>>doin things the old way
afc_dispatch_packet>>packet length = 66
service_send>>sending 40 bytes
afc_dispatch_packet>>packet data follows
service_send>>sending 26 bytes
internal_connection_receive_timeout>>ERROR: usbmuxd_recv_timeout returned -11 (Resource temporarily unavailable)
service_receive_with_timeout>>could not read data
afc_receive_data>>Just didn't get enough.
afc_file_open>>Didn't get any further data
afc_unlock>>Unlocked
Write operation failed
afc_lock>>Locked

is the afc_receive_data ,It can not receive data ,Is the send packet wrong in windows?

need some help ,

![tkg _ 3 7y64eb 6_nu wi](https://f.cloud.github.com/assets/6176495/1831239/c669567e-7384-11e3-9e82-9e68537ab37b.jpg)

**Comment by iponurovskiy** [comment]
Hello! I have faced with the same problem with afc_receive_data working on Windows. Could you tell how did you manage to solve it, please?
