### ISSUE TITLE
ERROR: Could not connect to lockdownd, error code -21

### ISSUE THREAD

**Issue by yangbiao01** [libimobiledevice/libimobiledevice#450]
Who has encountered this problem？ help me, thank you!

**Comment by codivilian** [comment]
i have and i don't know how to fix :/

**Comment by yangbiao01** [comment]
I have this problem in ubuntu14.04,and Solvedd in ubuntu 16.04.1

**Comment by AlexJinsin** [comment]
i have this problem  mac 10.12.3

**Comment by mathieujobin** [comment]
I have this problem with ubuntu 18.04
