### ISSUE TITLE
Use this framwork in OSX project

### ISSUE THREAD

**Issue by kapil0408** [libimobiledevice/libimobiledevice#459]
I want to use this library in my Mac project (OSX). not using by this terminal.
is it possible?

Thanks

**Comment by kapil0408** [comment]
Any comment on this please.

**Comment by nikias** [comment]
Of course, if you link against it like it works with any other library...

**Comment by kapil0408** [comment]
Please some link or idea...

**Comment by samrocketman** [comment]
How about sharing your code that doesn't work?

**Comment by nikias** [comment]
@samrocketman I think he doesn't know how to link against libraries in general.
@kapil0408 please search on stackoverflow/google/whatever how to integrate libraries into an xcode project, this issue tracker is for bugs, not howtos.

**Comment by kapil0408** [comment]
@samrocketman I don't have any idea how to do that. i am just using above link
