### ISSUE TITLE
Can't Backup my IOS10 device use idevicebackup2.exe

### ISSUE THREAD

**Issue by luosiding123** [libimobiledevice/libimobiledevice#468]
Backup directory is "E:\bak"
ERROR: Could not connect to lockdownd, error code -5

**Comment by onesecurity** [comment]
I met the same problem, did you solve it?

**Comment by azerg** [comment]
compile libimobiledevice from latest sources. Dont use 1.2.0 this fixed same error for me yesterday

**Comment by luosiding123** [comment]
@onesecurity  I have solved it just like azerg told me，compile it from latest sources

**Comment by Kanong017** [comment]
email me 820957570@qq.com

**Comment by samrocketman** [comment]
@luosiding123 please close this issue since compiling latest sources fixes your issue.

**Comment by nikias** [comment]
It works fine, I tested it compiled with mingw on Windows using a 10.3.1 device. No issues.
