### ISSUE TITLE
application sizes

### ISSUE THREAD

**Issue by daniel-bluesea** [libimobiledevice/libimobiledevice#469]
iTunes displays the application sizes (either by get info for each app or at the device's app list),
can it be done using libimobiledevice?

**Comment by Kanong017** [comment]
of course can

I simply said the order to get

**Instproxy_client_options_new
Instproxy_client_options_add
Plist_array_append_item (return_attributes, plist_new_string ("StaticDiskUsage"))
Plist_array_append_item (return_attributes, plist_new_string ("DynamicDiskUsage"))
Plist_dict_set_item (opts, "ReturnAttributes", return_attributes)**

Next
Instproxy_browse

**Comment by daniel-bluesea** [comment]
i missed that part at the ideviceinstaller (i had some trouble to compile and run its last versions).
thanks!
