### ISSUE TITLE
Info: What are some of the unknown domains like "com.apple.fmip" that can be used with ideviceinfo

### ISSUE THREAD

**Issue by nemecence90** [libimobiledevice/libimobiledevice#470]
Where to find and test these domains from, is there a repo for that? Or a list?

**Comment by FunkyM** [comment]
On question, there is no repository for that and does not need to be.
Apple defines which ones exist and we're glad to add new ones people find (by PR) into ideviceinfo.

Asides:
This is not a support forum, it is intended to discuss technical issues and changes.
Please use the Mailing-List, Google Group or StackOverflow for general discussion.
Good Luck! :four_leaf_clover:

**Comment by nemecence90** [comment]
Ok thanks!
