### ISSUE TITLE
ideviceinstaller not available

### ISSUE THREAD

**Issue by onesecurity** [libimobiledevice/libimobiledevice#472]
root@ubuntu:~# ideviceinstaller -l -o xxxxxxxxxx
GnuTLS error: Error in the pull function.
Could not connect to lockdownd. Exiting.

How is this problem solved?

**Comment by crummy** [comment]
Can you post more information about your environment? For example, OS version, iOS version, how you built ideviceinstaller, etc?

**Comment by nikias** [comment]
@crummy you are right, this information is missing.
@onesecurity this will work with latest code from git.
