### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by GorooJ** [libimobiledevice/libimobiledevice#473]
$ make
/Applications/Xcode8.2.app/Contents/Developer/usr/bin/make  all-recursive
Making all in common
  CC       debug.lo
In file included from debug.c:36:
../src/idevice.h:30:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[2]: *** [debug.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by mexmer** [comment]
install openssl development package
if you have it already isntalled, then you don't have properly set path to include files.

also use search function, this question has been asked, and replied multiple times.,
