### ISSUE TITLE
Prepare / Skip Activation Screen , via libimobildevice

### ISSUE THREAD

**Issue by Dantee296** [libimobiledevice/libimobiledevice#477]
<img width="505" alt="screen shot 2017-03-14 at 7 45 54 pm" src="https://cloud.githubusercontent.com/assets/25308637/23906190/15602872-08ef-11e7-8f9f-8fa18ff53e22.png">

# Hy guys Kindly Check the Attached image
i m doing it programmeticly using cfg-util (Apple utility comes with apple configurator) 
i want to do the same operation using libimobildevice 
if any one can help me with , Service name , parameters  any help / hint would be help full,
i have looked in idevicesyslog , but found nothing

Thanks in Advance...
@nikias  looking forward for ur responce :) Cheers

**Comment by Dantee296** [comment]
@nikias any help on this :)

**Comment by crummy** [comment]
You managed to skip the preparation screen with cfgutil? Can you provide instructions on this? I've been looking for such a solution for a while: http://apple.stackexchange.com/questions/259821/restore-ios-default-settings-without-user-interaction

**Comment by Dantee296** [comment]
@crummy  yes we are doing it using 
https://gist.github.com/FredCox3/0617eba0818a3ba957b7
but i wanna implement my own that why i wanted to ask @nikias

**Comment by crummy** [comment]
In my experience with cfgutil there are some screens that refuse to skip (I used `--skip-all` and some, like wifi and the "welcome to iPhone screen", where still present).

I was hoping for a solution that would allow me to, entirely automated, instruct a device to reset to a fresh (or prepared) state where it ends up on the home screen, ready to be interacted with.

**Comment by jackczhang** [comment]
@Dantee296 @crummy Do U get the solution in windows?

**Comment by crummy** [comment]
No, I have not found any way to skip all initial setup screens on an iOS device.

**Comment by jackczhang** [comment]
Is there some tool like cfgutil in windows?

**Comment by mexmer** [comment]
Nope, apple had such tool, but they discontinued it and doesn't work from ios6 onwards
