### ISSUE TITLE
I keep getting set a breakpoint in malloc_error_break to debug Abort trap: 6

### ISSUE THREAD

**Issue by yaphatak** [libimobiledevice/libimobiledevice#478]
I get this when install from master `brew install libimobiledevice --HEAD`
whole message looks like this 
`idevice_id(26172,0x7fff72a26000) malloc: *** error for object 0x7fb548d07d70: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

**Comment by nikias** [comment]
This is probably due to the use of OpenSSL 1.1.0 or later. I just merged pull request #494 which addresses the issue. If the problem persists, feel free to reopen the ticket.
