### ISSUE TITLE
总是error code -19和-21怎么回事？

### ISSUE THREAD

**Issue by lizhaode** [libimobiledevice/libimobiledevice#479]
我的设备是6S Plus IOS 9.3.5

只有idevice_id -l和ideviceinfo -s这两个命令正常，其他的任何命令都会报标题上的错误，有没有人遇到过？

**Comment by AlexJinsin** [comment]
@lizhaode -19 是授权问题 手机上点确认； 如果有-21的话建议卸载原来的
用下面命令安装下
brew install --HEAD libimobiledevice
我是这么解决的

**Comment by lizhaode** [comment]
@AlexJinsin 
感谢，我这样也可以了

**Comment by reaniwen** [comment]
This issue has been solved, and should be closed.
