### ISSUE TITLE
openssl not found (but it is installed)

### ISSUE THREAD

**Issue by vinipachecov** [libimobiledevice/libimobiledevice#485]
![image](https://cloud.githubusercontent.com/assets/2838834/24424143/eab366f6-13d5-11e7-8ced-4219f1a246c7.png)
Hi, I'm trying to compile the lib but somehow it is not working. 

![image](https://cloud.githubusercontent.com/assets/2838834/24424175/0bae5c44-13d6-11e7-9c2e-b1d9a02f1fe8.png)
 As you can see I have openssl installed, at least the system is telling me. I'm using Deepin Linux, how do I proceed?

**Comment by nikias** [comment]
Install the development packages.

**Comment by samrocketman** [comment]
`libssl-dev`
