### ISSUE TITLE
Help, i need to find the way to fix it 

### ISSUE THREAD

**Issue by OsukaS** [libimobiledevice/libimobiledevice#488]
Hi, i'm working on a Iphone 6s, but when i try tu use any idevice, it send me an error code -5, and the worst problem is that i'm working now o Windows O.S., Please someone help me 
![image](https://cloud.githubusercontent.com/assets/26902443/24662608/2b22914a-191b-11e7-9c65-694be3adff65.png)

**Comment by reaniwen** [comment]
It seems to be something wrong with your SSL? Have you tried to reinstall Open SSL?

**Comment by nikias** [comment]
Another perfect example of how not to report an issue. How did you get the binaries? Did you compile them on your own? If you downloaded them somewhere they might be outdated.
Closing since the report is too unspecific. Nobody can really help you if you don't provide any useful information.
