### ISSUE TITLE
How I can check icloud activation status by libimobiledevice ?

### ISSUE THREAD

**Issue by amzil** [libimobiledevice/libimobiledevice#499]
Hello,

how I want to know if I can get information about icloud activation status from usb by libimobiledevice tools? if not,have the another method for extract information from apple products by cmd line ?

Ubuntu 16.04

**Comment by JohnChain** [comment]
I get this error code too
Anyone can help on this ?

ERROR: Could not connect to lockdownd, error code -21

env:
MacOS 10.12.4

**Comment by iamluosm** [comment]
@JohnChain I remember I just Run this command line ```ideviceimagemounter```
