### ISSUE TITLE
idevicebackup2 errorcode -6

### ISSUE THREAD

**Issue by Kanong017** [libimobiledevice/libimobiledevice#500]
how to fix it?
pls help me

**Comment by samrocketman** [comment]
As noted in #468, you need to compile the latest sources.  This is not a bug because it has been fixed in master.

**Comment by Kanong017** [comment]
@samrocketman I was using the latest version of the compiler, or error code -6

**Comment by nikias** [comment]
duplicate of #490 and #491

**Comment by samrocketman** [comment]
@Kanong017 subscribe to #490 for updates.
