### ISSUE TITLE
iOS 11 idevicescreenshot not working

### ISSUE THREAD

**Issue by pranavv** [libimobiledevice/libimobiledevice#512]
iOS 11 idevicescreenshot not working its retuning ,ERROR: Could not connect to lockdownd, error code -3, any idea of when iOS 11 support will be launched

**Comment by nikias** [comment]
Have you tried with this patch: https://github.com/libimobiledevice/libimobiledevice/issues/510#issuecomment-307375896

**Comment by VasilijSviridov** [comment]
@nikias could you provide how to install solution you mentioned ? is it possible to install it with brew ?

**Comment by nikias** [comment]
Closing, since ```idevicescreenshot``` works fine with iOS 11, with the patch I supplied. See #510 for updates.

**Comment by VasilijSviridov** [comment]
this worked for me on iOS 9,10,11 https://github.com/imkira/mobiledevice 
thank you for help @nikias 

Cheers
