### ISSUE TITLE
USB Reverse Internet Tethering

### ISSUE THREAD

**Issue by iamluosm** [libimobiledevice/libimobiledevice#514]
Hi.
Can I share my iMac's internet access to iPhone via USB lightning cable use this lib ?
Do you have the same requirement ?
Any solution ?
Thanks

**Comment by iamluosm** [comment]
Nobody knows ? come on, man.

**Comment by nikias** [comment]
Doesn't work.

**Comment by vigossjjj** [comment]
I also want to create a  connection from iOS device to PC's local server via USB cable....
What's new now?

**Comment by mexmer** [comment]
nothing new, this is not supported
