### ISSUE TITLE
Circular reference error with libusbmuxd while building

### ISSUE THREAD

**Issue by fwd079** [libimobiledevice/libimobiledevice#518]
Hi, I downloaded git repositories for ifuse, libusbmuxd and libimobiledevice.
ifuse built successfully.

But for both libusbmuxd and libimobiledevice, the autogen.sh fails, complaining the other bit is not there. So you cannot run autogen.sh for either libusbmuxd or libimobiledevice.

Please can someone guide me how to build these? Thanks.

OS: Ubuntu 16.04 64 bit

**Comment by nikias** [comment]
No need to double post here and on the usbmuxd project.
Your problem is that you confuse usbmuxd with libusbmuxd. libusbmuxd does not require libimobiledevice but usbmuxd does. Hence build in the following order:
- libplist
- libusbmuxd
- libimobiledevice
- usbmuxd

**Comment by fwd079** [comment]
Okay, thanks. I will try it and let you know.

**Comment by fwd079** [comment]
Thanks @nikias  all is installed successfully, now I'll go and check what to do next.
