### ISSUE TITLE
idevicebackup2 v1.1.5 not detecting plists in backup directory

### ISSUE THREAD

**Issue by slo-sleuth** [libimobiledevice/libimobiledevice#52]
Successful backup of iPad1 with iOS 5.1.5 with Ubuntu 13.10.  However, cannot get backup info, restore, or unback.

$ /usr/bin/idevicebackup2 info affa3e6e312e30374f771f9ad81ac61a########/
ErrorCode 4: No such file or directory at path "affa3e6e312e30374f771f9ad81ac61a########/Status.plist" (MBErrorDomain/4)

$ sudo /usr/bin/idevicebackup2 restore affa3e6e312e30374f771f9ad81ac61a########/
ERROR: Backup directory "affa3e6e312e30374f771f9ad81ac61a########/" is invalid. No Info.plist found for UDID affa3e6e312e30374f771f9ad81ac61a########.

$ /usr/bin/idevicebackup2 unback affa3e6e312e30374f771f9ad81ac61a########/
Backup directory is "affa3e6e312e30374f771f9ad81ac61a########/"
Started "com.apple.mobilebackup2" service on port 49463.
Negotiated Protocol Version 2.1
Starting to unpack backup...
ErrorCode 205: Error reading backup properties (MBErrorDomain/205). Underlying error: No such file or directory at path "affa3e6e312e30374f771f9ad81ac61a########/Manifest.plist" (MBErrorDomain/4).
The files can now be found in the "_unback_" directory.
Unback Successful.

$ ls affa3e6e312e30374f771f9ad81ac61a########/_._
affa3e6e312e30374f771f9ad81ac61a########/Info.plist
affa3e6e312e30374f771f9ad81ac61a########/Manifest.mbdb
affa3e6e312e30374f771f9ad81ac61a########/Manifest.plist
affa3e6e312e30374f771f9ad81ac61a########/Status.plist

**Comment by tarrenj** [comment]
Point idevicebackup2 to the directory you're UUID folder is in.

So let's say your affa3e6e312e30374f771f9ad81ac61a########/ directory is in ~, then the command would be:
$ idevicebackup2 backup ~/
