### ISSUE TITLE
Can not active device on iOS 11 beta

### ISSUE THREAD

**Issue by truonggiang0710** [libimobiledevice/libimobiledevice#521]

**Comment by crummy** [comment]
Can you talk a little more about what you've tried and the behaviour you're seeing?

**Comment by truonggiang0710** [comment]
tks @crummy . I posted here https://github.com/libimobiledevice/libideviceactivation/issues/23

**Comment by samrocketman** [comment]
@truonggiang0710 Ok, please close this since it is a duplicate.
