### ISSUE TITLE
 How I can get icloud activation status by libimobiledevice ?

### ISSUE THREAD

**Issue by amzil** [libimobiledevice/libimobiledevice#531]
Hello,

I want to know if I can get information about icloud activation status from usb by libimobiledevice tools? 

Ubuntu 16.04

**Comment by truonggiang0710** [comment]
@amzil  libimobiledevice responses cloud status when you activate device.

**Comment by amzil** [comment]
@truonggiang0710, thank you for your responce , but how I can check if the device have icloud activated or not?
I have already tested "ideviceinfos"  after and before deleting my device from icloud. but I have the same results.

**Comment by truonggiang0710** [comment]
@amzil Check activation response and break out to return if your device has icloud.

**Comment by daniel-bluesea** [comment]
@truonggiang0710 your suggestion requires a SIM card inserted to the device.
how can we check activation lock status with a wiped/erased device?

btw, ideviceinfo -q com.apple.fmip -k IsAssociated returns always false when device is in setup wizard after wipe/erase

@amzil did you find your answer? :)

**Comment by amzil** [comment]
yes, perfect thank you daniel-bluesea.

**Comment by amzil** [comment]
@daniel-bluesea how I can then know if the 'Trust This Computer' message alert  is apparent on the device and not confirmed.

**Comment by daniel-bluesea** [comment]
@amzil did you manage to activation lock status for device with no sim card? if so please share :)

**Comment by amzil** [comment]
hello @daniel-bluesea, yes , please try  ideviceinfo -q com.apple.fmip -k IsAssociated work under ubuntu linux

**Comment by nikias** [comment]
Keep in mind this doesn't work if the device has been wiped clean while activation lock is still enabled.

**Comment by amzil** [comment]
@nikias tkx for your response, so how i can verify icloud activation status in this case ?

**Comment by nikias** [comment]
When you try to activate you will get a prompt for iCloud credentials. And you will need a sim card inserted.

**Comment by nikias** [comment]
@daniel-bluesea correct.
