### ISSUE TITLE
Enable LocationServices Remotely via Libimobiledevice

### ISSUE THREAD

**Issue by Dantee296** [libimobiledevice/libimobiledevice#534]
-Suspected Services-

com.apple.locationd 
com.apple.MapsSupport

Property : LocationServicesEnabled  
Values :  1 or 0

i tried to Start Service  " com.apple.locationd " and it not starting it
i tried to set value 
lockdownd_error_t  lerr = lockdownd_set_value(lockdown, "com.apple.locationd", "LocationServicesEnabled", plist_new_real(1));

not working either 
kindly Help me with this
@nikias

**Comment by mexmer** [comment]
you have not posted, what error you got, when trying to start service.

mind not all services can be started remotely, or might require provisioning profile (like some services are only available for developers when debuging in xcode, but not for public)

**Comment by Dantee296** [comment]
i m gonna try it after mounting developer image
ll let u know what it says.

you have any idea about enabling Location services remotely
Thanks

**Comment by mexmer** [comment]
start service doesn't return anything except success or failure, and in case of success also socket for connection.

not sure, what you mean by empty plist then.

as for starting these services itself, no i don't have any knowledge about them, so i don't know, what proper parameters or request are.

**Comment by xdeng** [comment]
not support LocationServicesEnabled ???

**Comment by Dantee296** [comment]
No , @xdeng do you hv any research on this ?
