### ISSUE TITLE
Unable to make on Fedora 24

### ISSUE THREAD

**Issue by letsflyak** [libimobiledevice/libimobiledevice#540]
trying to install 1.0.7 and im getting this error if someone can point me in right direction?

[root@wolf libimobiledevice-1.0.7]# make
make  all-recursive
make[1]: Entering directory '/home/letsfly/ilibmobile/libimobiledevice-1.0.7'
Making all in src
make[2]: Entering directory '/home/letsfly/ilibmobile/libimobiledevice-1.0.7/src'
  CC     idevice.lo
idevice.c: In function 'usbmux_event_cb':
idevice.c:40:26: error: 'usbmuxd_device_info_t {aka const struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
  ev.uuid = event->device.uuid;
                          ^~~~
                          udid
In file included from /usr/include/string.h:634:0,
                 from idevice.c:24:
idevice.c: In function 'idevice_get_device_list':
idevice.c:113:44: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   newlist[newcount++] = strdup(dev_list[i].uuid);
                                            ^
idevice.c:113:44: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   newlist[newcount++] = strdup(dev_list[i].uuid);
                                            ^
idevice.c:113:44: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   newlist[newcount++] = strdup(dev_list[i].uuid);
                                            ^
idevice.c:113:44: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   newlist[newcount++] = strdup(dev_list[i].uuid);
                                            ^
idevice.c:113:44: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   newlist[newcount++] = strdup(dev_list[i].uuid);
                                            ^
idevice.c:113:44: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   newlist[newcount++] = strdup(dev_list[i].uuid);
                                            ^
idevice.c:113:44: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   newlist[newcount++] = strdup(dev_list[i].uuid);
                                            ^
idevice.c: In function 'idevice_new':
idevice.c:162:12: warning: implicit declaration of function 'usbmuxd_get_device_by_uuid'; did you mean 'usbmuxd_get_device_by_udid'? [-Wimplicit-function-declaration]
  int res = usbmuxd_get_device_by_uuid(uuid, &muxdev);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
            usbmuxd_get_device_by_udid
In file included from /usr/include/string.h:634:0,
                 from idevice.c:24:
idevice.c:165:31: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   phone->uuid = strdup(muxdev.uuid);
                               ^
idevice.c:165:31: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   phone->uuid = strdup(muxdev.uuid);
                               ^
idevice.c:165:31: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   phone->uuid = strdup(muxdev.uuid);
                               ^
idevice.c:165:31: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   phone->uuid = strdup(muxdev.uuid);
                               ^
idevice.c:165:31: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   phone->uuid = strdup(muxdev.uuid);
                               ^
idevice.c:165:31: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   phone->uuid = strdup(muxdev.uuid);
                               ^
idevice.c:165:31: error: 'usbmuxd_device_info_t {aka struct <anonymous>}' has no member named 'uuid'; did you mean 'udid'?
   phone->uuid = strdup(muxdev.uuid);
                               ^
idevice.c: At top level:
idevice.c:549:173: error: unknown type name 'gnutls_retr_st'; did you mean 'gnutls_retr2_st'?
 s, const gnutls_pk_algorithm_t * sign_algos, int sign_algos_length, gnutls_retr_st * st)
                                                                     ^~~~~~~~~~~~~~
                                                                                                                                                                             gnutls_retr2_st
idevice.c: In function 'idevice_connection_enable_ssl':
idevice.c:592:2: warning: implicit declaration of function 'gnutls_certificate_client_set_retrieve_function'; did you mean 'gnutls_certificate_set_retrieve_function'? [-Wimplicit-function-declaration]
  gnutls_certificate_client_set_retrieve_function (ssl_data_loc->certificate, internal_cert_callback);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gnutls_certificate_set_retrieve_function
idevice.c:592:78: error: 'internal_cert_callback' undeclared (first use in this function); did you mean 'internal_ssl_cleanup'?
 ertificate_client_set_retrieve_function (ssl_data_loc->certificate, internal_cert_callback);
                                                                     ^~~~~~~~~~~~~~~~~~~~~~
                                                                              internal_ssl_cleanup
idevice.c:592:78: note: each undeclared identifier is reported only once for each function it appears in
In file included from idevice.c:31:0:
idevice.c: At top level:
debug.h:47:29: warning: inline function 'debug_plist_real' declared but never defined
 G_GNUC_INTERNAL inline void debug_plist_real(const char *func,
                             ^~~~~~~~~~~~~~~~
debug.h:46:29: warning: inline function 'debug_buffer_to_file' declared but never defined
 G_GNUC_INTERNAL inline void debug_buffer_to_file(const char *file, const char *data, const int length);
                             ^~~~~~~~~~~~~~~~~~~~
debug.h:45:29: warning: inline function 'debug_buffer' declared but never defined
 G_GNUC_INTERNAL inline void debug_buffer(const char *data, const int length);
                             ^~~~~~~~~~~~
debug.h:40:29: warning: inline function 'debug_info_real' declared but never defined
 G_GNUC_INTERNAL inline void debug_info_real(const char *func,
                             ^~~~~~~~~~~~~~~
make[2]: *** [Makefile:409: idevice.lo] Error 1
make[2]: Leaving directory '/home/letsfly/ilibmobile/libimobiledevice-1.0.7/src'
make[1]: *** [Makefile:405: all-recursive] Error 1
make[1]: Leaving directory '/home/letsfly/ilibmobile/libimobiledevice-1.0.7'
make: *** [Makefile:310: all] Error 2

**Comment by nikias** [comment]
You are trying to build a really outdated version that was released several years ago. Why don't you use the latest code from git? Then you will have a version that actually works...
