### ISSUE TITLE
Read DeviceEnsureColor iPod Touch 5 !

### ISSUE THREAD

**Issue by truonggiang0710** [libimobiledevice/libimobiledevice#542]
Hello,

I have an iPod touch 5. I ran 
`ideviceinfo -k DeviceEnclosureColor` and it returned
`sparrow`
I checked at apple web but sparrow color not exist.
I don't know what means sparrow color ?
Please help me explain ! 
Thanks a lot !

**Comment by Dantee296** [comment]
u wont find sparrow or any other Hex Enclosure color on Apple web.
you ll have to map it on ur own
its more like a SpaceGray.
so lets say 
if (enclousrecolor == "sparrow"){return "space gray");

**Comment by truonggiang0710** [comment]
Thanks a lot @Dantee296 !

**Comment by Dantee296** [comment]
Your Welcome :)

**Comment by Dantee296** [comment]
You can close this issue now
