### ISSUE TITLE
is there any way to simulate Touch ID on ios??

### ISSUE THREAD

**Issue by ketan077** [libimobiledevice/libimobiledevice#563]

**Comment by Kanong017** [comment]
Impossible

**Comment by ketan077** [comment]
can I access device via tcp port forwarding without usbmuxd???

**Comment by nikias** [comment]
No.

**Comment by ketan077** [comment]
so i can't access ios device remotely via port forwarding  right??

**Comment by ketan077** [comment]
but we can access usbmuxd forwarding remotely but it will show you all devices not particularly

**Comment by nikias** [comment]
I don't know what you want to achieve. usbmuxd allows you to open a connection to an open port on the device. Maybe you want to use iproxy? Check out the man page for that please.

**Comment by ketan077** [comment]
I want to access ios device remotely from another Mac or Linux using
forwarding usbmuxd packet

On 20-Sep-2017 10:07 PM, "Nikias Bassen" <notifications@github.com> wrote:

I don't know what you want to achieve. usbmuxd allows you to open a
connection to an open port on the device. Maybe you want to use iproxy?
Check out the man page for that please.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libimobiledevice/libimobiledevice/issues/563#issuecomment-330909558>,
or mute the thread

**Comment by ketan077** [comment]
Anyway I will do it myself
