### ISSUE TITLE
idevicebackup2 backup -- ErrorCode 104: Error removing snapshot directory

### ISSUE THREAD

**Issue by bucktaiwan** [libimobiledevice/libimobiledevice#58]
It seems backup is almost finished. But, removing snapshot has trouble and cause backup failed. The followings are print out from console.

[==================================================] 100% Finished
Moving 128 files
[==================================================] 100% Finished
Moving 15 files
[==================================================] 100% Finished
Moving 1 file
[==================================================] 100% Finished
Moving 1 file
[==================================================] 100% Finished
[==================================================] 100% Finished
Removing 1 file
Could not remove 'tmp/origin_1/3479d2dacfc1dd6b673a49ca1be89611913a64ec/Snapshot': Directory not empty (39)
[==================================================] 100% Finished
ErrorCode 104: Error removing snapshot directory (MBErrorDomain/104). Underlying error: Directory not empty (MBErrorDomain/100).
Received 9069 files from device.
Backup Failed (Error Code 104).

Here is another device with same trouble. Attach Status.plist for reference:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>UUID</key>
    <string>84006397-D01C-4608-9DE2-D496A06FBE87</string>
    <key>IsFullBackup</key>
    <true/>
    <key>Version</key>
    <string>2.4</string>
    <key>BackupState</key>
    <string>new</string>
    <key>Date</key>
    <date>1983-02-10T20:44:20Z</date>
    <key>SnapshotState</key>
    <string>removing</string>
</dict>
</plist>

Appreciate  for any feedback.

**Comment by unhammer** [comment]
Just saw this one myself, twice in a row so it's definitely not that I'm changing anything while it's running.

Does this error only happen after everything has been copied over and idevicebackup2 is cleaning up, or are there still files that will not be copied over because this error occurred?

**Comment by corsac-s** [comment]
@unhammer which version do you have / on which distribution, and which iOS version is it?

I'm experiencing the same this on Debian sid with libimobildevice 1.2.0+dfsg-3.2 with iOS 11.1.1, but not when I'm using a version built myself from the git. It'd be nice to have a point release of libimobiledevices including the fixes in master.

**Comment by unhammer** [comment]
> `Version: 1.2.0+dfsg-3.1ubuntu1`

so I was one point behind your `1.2.0+dfsg-3.2`; last tested on Xubuntu 17.04
