### ISSUE TITLE
What software is used to open this project ?

### ISSUE THREAD

**Issue by 3208287103** [libimobiledevice/libimobiledevice#580]
I would like to open these projects(libimobiledevice/libusbmuxd...) in my computer, who knows how to operate it ? What software is used to open this project ? Hi, @nikias @FunkyM ,can you help me ? Thank you very much !

**Comment by 3208287103** [comment]
Doesn't anyone know about this QUESTION ?

**Comment by nikias** [comment]
You need a terminal and installed build environment (compiler, autoconf, automake, etc.) All the packages you need are mentioned in the readme.
