### ISSUE TITLE
How to get if device has been setup or not?

### ISSUE THREAD

**Issue by Mradr** [libimobiledevice/libimobiledevice#583]
I understand the error when backing up it gives "ErrorCode 212: Unable to backup until Setup is finished (MBErrorDomain/212)" but my question is how can I look this up on my own using deviceinfo? 

The idea is that I want to know if the device has finish setup or at the desktop. I guess I could always run the backup command wait about 9 lines in and Ctrl - C out of there, but it would be handy to know if it is pass setup or not.

Not sure of it's a bug or not - but I thought deviceinfo -k was design to show "all" items under the -q, but I am not able to get anything when doing just -k alone (well errors out)

**Comment by Dantee296** [comment]
Hint : Purplebuddy

**Comment by Mradr** [comment]
Thanks I see it. I simple overlook it when I was going down the list :))
