### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by hdante** [libimobiledevice/libimobiledevice#585]
Hello, I’m forwarding this request:

https://bugs.archlinux.org/task/56227

We’d like a new version release because latest one is not working with gnutls+ios 11. The new release would push many fixes downstream to the distros.

**Comment by hdante** [comment]
Hello ?

**Comment by kaihendry** [comment]
Please make a release. Or maybe I need to start using Gentoo.

**Comment by FunkyM** [comment]
Closing as version [1.3.0](/libimobiledevice/libimobiledevice/releases/tag/1.3.0) has been released.
