### ISSUE TITLE
cannot find <cstddef> file in plist/node.h Xcode

### ISSUE THREAD

**Issue by akshay2604** [libimobiledevice/libimobiledevice#593]
I am running a react native project and found this error during build. It maybe a problem with my xcode settings but i am not sure. Any insights on why this error may come up during build? 
![image](https://user-images.githubusercontent.com/20161828/33164509-273e8840-d059-11e7-8edb-8c8a99d1a788.png)

here is the stack trace
![image](https://user-images.githubusercontent.com/20161828/33171351-c3e56bb0-d071-11e7-8661-a0d706f33154.png)

**Comment by akshay2604** [comment]
Closing as not relevant in this repo. opened [here] https://github.com/libimobiledevice/libplist/issues/112

**Comment by bfontaine** [comment]
How did you fix the issue?

**Comment by AngleZhou** [comment]
Same error happened when local compiling libimobiledevice. Also want to know the solution.
