### ISSUE TITLE
Small memory leak

### ISSUE THREAD

**Issue by Blefish** [libimobiledevice/libimobiledevice#599]
Hi

There is a small memory leak at this line:
https://github.com/libimobiledevice/libimobiledevice/blob/b7feed9f5a62833c1df3f503fd3693e2ed2e4738/src/lockdown.c#L712

p_version should be freed.

**Comment by nikias** [comment]
Fixed with commit 344729536e49d6a98aa05d76a3637856748911cd. Thanks for reporting!
