### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [libimobiledevice/libimobiledevice#615]
How to compile libimobiledevice i need help

**Comment by samrocketman** [comment]
If you're asking about how to compile on Linux or Mac OS X then refer to this gist -> https://gist.github.com/samrocketman/70dff6ebb18004fc37dc5e33c259a0fc

**Comment by vladut123** [comment]
How to compile otachecker-master

**Comment by vladut123** [comment]
Disable iphone charging when connected to macbook

**Comment by vladut123** [comment]
How to compile libimobiledevice on mac

**Comment by vladut123** [comment]
How to compile img4tool on windows 10

**Comment by nikias** [comment]
Please stop asking random questions. otachecker and img4tool are completely different projects.

**Comment by FunkyM** [comment]
Closing as duplicate of #620.
