### ISSUE TITLE
How to get WiFi IP?

### ISSUE THREAD

**Issue by renatorodrigues** [libimobiledevice/libimobiledevice#65]
`ideviceinfo` returns a big amount of information, including `WiFiAddress`. But instead of returning the IP, it returns the MAC Address. Is there any way to return de IP of the device?

**Comment by juhlila** [comment]
@FunkyM and how to do that?

**Comment by KorranForce** [comment]
@juhlila If your iOS device is in the same local network as your computer (connected to the same Wi-Fi or iOS device is connected to your Mac's shared network as example) then device name (returned by 'ideviceinfo -k DeviceName' command or in device's Settings->General->About) is resolved to ip. Resolving can be done by 'nslookup $(ideviceinfo -k DeviceName)' command (as example). Device name must contain only characters that are correct for url ('my-i-device' as example).

**Comment by leonnfang** [comment]
If the device and the pc are not in the same network, is there a way to find the IP address?

**Comment by liangwu** [comment]
> @juhlila If your iOS device is in the same local network as your computer (connected to the same Wi-Fi or iOS device is connected to your Mac's shared network as example) then device name (returned by 'ideviceinfo -k DeviceName' command or in device's Settings->General->About) is resolved to ip. Resolving can be done by 'nslookup $(ideviceinfo -k DeviceName)' command (as example). Device name must contain only characters that are correct for url ('my-i-device' as example).

if it has unicode characters, how could i use it to lookup? url-encoding does not work
