### ISSUE TITLE
idevice_free()  doesn't  really free the memory 

### ISSUE THREAD

**Issue by jimwan** [libimobiledevice/libimobiledevice#652]
`
    if (LOCKDOWN_E_SUCCESS != (ldret = simple ?
                               lockdownd_client_new(device, &client, "ideviceinfo"):
                               lockdownd_client_new_with_handshake(device, &client, "ideviceinfo"))) 

{
        fprintf(stderr, "ERROR: Could not connect to lockdownd, error code %d\n", ldret);
        idevice_free(device);
        if(device)
        {
            NSLog(@"OK");
        }
        else{
            NSLog(@"no");
        }
        return NO;
    }
`

the result is print "OK", so this means the device is not free up after call idevice_free.

**Comment by nikias** [comment]
This is not correct. If you free() something the underlying memory is freed but the pointer address is still in your variable (device). This is not a leak.
