### ISSUE TITLE
Use file_relay_client_new() but return FILE_RELAY_E_MUX_ERROR

### ISSUE THREAD

**Issue by lantimes** [libimobiledevice/libimobiledevice#657]
Hi there,
I try to use file_relay_client_new(idevice_t device, lockdownd_service_descriptor_t service, file_relay_client_t *client), but it return FILE_RELAY_E_MUX_ERROR.
Does anyone know what happened and how to use it.
In my code, the lockdownd_start_service() was already successful.

**Comment by nikias** [comment]
Starting with iOS 8, file relay is no longer usable.
