### ISSUE TITLE
IOS 11.3 idevicediagnostics ioregentry not work

### ISSUE THREAD

**Issue by Zronel** [libimobiledevice/libimobiledevice#660]
Hello,
When I try to idevicediagnostics ioregentry AppleARMPMUCharger on iPhone 8 ,  ios 11.3 is not work.
But on  iPhone 6 puls ios 10.3 is work.

**Comment by Blefish** [comment]
This is not an issue with imobiledevice. However you need to use AppleSmartBattery for iPhone 8 and later.

**Comment by Zronel** [comment]
@Blefish It has been resolved，thank you

**Comment by linpeifei** [comment]
> This is not an issue with imobiledevice. However you need to use AppleSmartBattery for iPhone 8 and later.

How do you know the [KEY] is AppleSmartBattery? And Where could I find the KEY list?
