### ISSUE TITLE
How can I get a trust dialog.

### ISSUE THREAD

**Issue by iDalink** [libimobiledevice/libimobiledevice#672]
I am using idevicesyslog, but I can not fetch a trust dialog automatically.  Is trust dialog trigger by idevicesyslog command or a certain function? How can I trigger a trust dialog where iPhone connect to computer?

**Comment by mexmer** [comment]
trust dialog is shown, when device is doing pairing operation, it has nothing with syslog (except you need to be paired, to retrieve syslog).

do pair (using idevicepair), then syslog

**Comment by iDalink** [comment]
YES, I found the point just now. Thaks for your answer.
