### ISSUE TITLE
ERROR: Could not connect to lockdownd, error code -2

### ISSUE THREAD

**Issue by Anonyvius** [libimobiledevice/libimobiledevice#673]
Hey, just installed libimobiledevice on my raspberrypi 3 running an kali linux arm image, . The problem now is everytime i type like `ideviceinfo` i´m gettin this error `ERROR: Could not connect to lockdownd, error code -2` but when i use the `ideviceinfo -s` option its working. Any idea how to fix this?

Found this solution by @moofnbg: 

> This solved the problem for me:

> brew uninstall libimobiledevice
brew install --HEAD libimobiledevice

but i cant get bre to work, because just gettin this error:

> Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

but i don´t know how to run brew as an non-root user without creating an new account using `adduser`

Let me know if you have any idea how to fix this.

- Anonyvius

**Comment by walkjivefly** [comment]
@Anonyvius you might have a distro-installed, wrong, version of one of the pre-reqs on your machine. I had this problem with linux Mint 17.3. I can't remember which one it was, possibly libplist or (lib)usbmuxd. apt/synaptic wouldn't let me remove the distro-supplied version without completely lobotomising the install. I ended up building a Linux From Scratch system to be sure it was free from crap and then compiling all the latest github masters. The result was a fully working libimobiledevice etc.
