### ISSUE TITLE
How to get the screenshot in windows? And how to mount the developer disk image in windows?

### ISSUE THREAD

**Issue by jackczhang** [libimobiledevice/libimobiledevice#686]
idevicescreenshot.exe->A mounted developer disk image is required on the device, otherwise
the screenshotr service is not available.
ideviceimagemounter.exe->ideviceimagemounter.exe [OPTIONS] IMAGE_FILE IMAGE_SIGNATURE_FILE
How can i get the image_file and image_signature_file in windows?

**Comment by jackczhang** [comment]
resolved, close.

**Comment by Maciejszuchta** [comment]
Can You tell me how you resolved this issue?

![image](https://user-images.githubusercontent.com/12434636/105480648-4d87bd00-5ca6-11eb-84dd-5849b969c76c.png)
Im experiencing following error.
