### ISSUE TITLE
How to bypass language screen and region screen at activation process (skip assistant set up) ?

### ISSUE THREAD

**Issue by truonggiang0710** [libimobiledevice/libimobiledevice#690]
Hi @nikias , apple configurator 2 can skip language and region over prepare device.
How can we do that ?

**Comment by truonggiang0710** [comment]
@jduranc , you can use apple configurator on MAC. But I need help to do it on linux.

**Comment by aymenim** [comment]
If I remember correctly you can set the locale and region  using `lockdownd_set_value` after activation and the pages won't show up  on the welcome screen.

**Comment by jduranc** [comment]
Hi @aymenim ,

I already try doing that with no luck, I'm not sure if this could be done with the preboard service added by @nikias a few months ago.

**Comment by a-gunter** [comment]
`lockdownd_set_value` with the domain of `com.apple.international` will allow you to set Language / Locale.

Valid language & locale IDs: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
