### ISSUE TITLE
LCD's QR Code extraction with libimobiledevice

### ISSUE THREAD

**Issue by elisardofelix** [libimobiledevice/libimobiledevice#696]
I'm trying to obtain the information in the QR Code printed on the LCD 's chip as you can see in the image below.

Anyone know any domain key or IOClass that have this information?

![image](https://user-images.githubusercontent.com/23348947/44825426-8e17a500-abd8-11e8-8ec5-dda682b4be11.png)

**Comment by abdulzeedo** [comment]
May I know the purpose of knowing that?
