### ISSUE TITLE
UDID format change with iPhone XS

### ISSUE THREAD

**Issue by umutuzgur** [libimobiledevice/libimobiledevice#701]
Hi there,

With the release of iPhone XS and XS Max, the iPhone udid format changed it became this value of 25 digits with the hyphen in between. Most of the command line tools have the udid length check which is 40. These are not valid anymore. We should come up with a strategy to handle this case. Maybe removing these checks would be good solution.

Thanks a lot.

**Comment by kazzmir** [comment]
I have locally removed all the checks in the idevice* tools for the 40 char limit, and my system works fine.

**Comment by enotsen** [comment]
@kazzmir Curious if you can share the steps you took to reach this resolution? Thank you!

**Comment by kazzmir** [comment]
Edit the libimobiledevice/tools/*.c files, such as idevicesyslog.c and comment out the check for 40 chars.

```
    else if (!strcmp(argv[i], "-u") || !strcmp(argv[i], "--udid")) {
            i++;
            // comment out the strlen() != 40 check
            if (!argv[i] /*|| (strlen(argv[i]) != 40)*/ ) {
                print_usage(argc, argv);
                return 0;
            }
            udid = strdup(argv[i]);
            continue;
        }
```
And do this for all the .c files, then rebuild libimobiledevice with make.

**Comment by nikias** [comment]
Yes I will do exactly that; removing the length check alltogether seems like the best choice. Either way, usbmuxd won't return a device if the udid is invalid :)
