### ISSUE TITLE
idevicescreenshot is broken with iOS 12 iPhone XS Max

### ISSUE THREAD

**Issue by umutuzgur** [libimobiledevice/libimobiledevice#702]
Hi there,

There is nothing to fix with this issue on the libimobiledevice side because there are crash reports with Screenshotr that comes from the Developer Image. I just wanted to report this so people are aware that there is an issue with the iOS Developer Image release.

**Comment by kazzmir** [comment]
Xcode also has issues getting screenshots with Xs max.

**Comment by mexmer** [comment]
you need to wait, until apple releases new xcode that will work with new iphones. it's similar issue, like with iPhone X, they released iPhone X before xcode, leading to various issues.
