### ISSUE TITLE
When i do "make"

### ISSUE THREAD

**Issue by MastroGeppetto14** [libimobiledevice/libimobiledevice#713]
make  all-recursive
make[1]: Entering directory '/home/pi/Downloads/libimobiledevice-master'
Making all in common
make[2]: Entering directory '/home/pi/Downloads/libimobiledevice-master/common'
  CC       socket.lo
  CC       thread.lo
  CC       debug.lo
  CC       userpref.lo
  CC       utils.lo
  CCLD     libinternalcommon.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/pi/Downloads/libimobiledevice-master/common'
Making all in src
make[2]: Entering directory '/home/pi/Downloads/libimobiledevice-master/src'
  CC       idevice.lo
idevice.c: In function ‘idevice_connection_enable_ssl’:
idevice.c:724:2: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
  SSL_CTX *ssl_ctx = SSL_CTX_new(TLSv1_method());
  ^~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from idevice.c:39:
/usr/include/openssl/ssl.h:1612:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
  CC       service.lo
  CC       property_list_service.lo
  CC       device_link_service.lo
  CC       lockdown.lo
  CC       afc.lo
  CC       file_relay.lo
  CC       notification_proxy.lo
  CC       installation_proxy.lo
  CC       sbservices.lo
  CC       mobile_image_mounter.lo
  CC       screenshotr.lo
  CC       mobilesync.lo
  CC       mobilebackup.lo
  CC       house_arrest.lo
  CC       mobilebackup2.lo
  CC       misagent.lo
  CC       restore.lo
  CC       diagnostics_relay.lo
  CC       heartbeat.lo
  CC       debugserver.lo
  CC       webinspector.lo
  CC       mobileactivation.lo
  CC       syslog_relay.lo
  CCLD     libimobiledevice.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/pi/Downloads/libimobiledevice-master/src'
Making all in include
make[2]: Entering directory '/home/pi/Downloads/libimobiledevice-master/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/pi/Downloads/libimobiledevice-master/include'
Making all in tools
make[2]: Entering directory '/home/pi/Downloads/libimobiledevice-master/tools'
  CC       idevice_id-idevice_id.o
  CCLD     idevice_id
../src/.libs/libimobiledevice.so: undefined reference to `usbmuxd_save_pair_record_with_device_id'
collect2: error: ld returned 1 exit status
Makefile:653: recipe for target 'idevice_id' failed
make[2]: *** [idevice_id] Error 1
make[2]: Leaving directory '/home/pi/Downloads/libimobiledevice-master/tools'
Makefile:456: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/Downloads/libimobiledevice-master'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2

I use Raspberry pi3 with stretch 
Anyone can help me?

**Comment by dnsBlah** [comment]
Did you already try the autogen.sh --disable-openssl
?

**Comment by MastroGeppetto14** [comment]
i installer the library with apt-get install 
and so i use command from cmd
