### ISSUE TITLE
ERROR: Could not connect to lockdownd, error code -2, macOS 10.13.4, latest libimobiledevice

### ISSUE THREAD

**Issue by yuzhidi** [libimobiledevice/libimobiledevice#722]
should I update my macOS
I have execute:
brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller

![ideviceinfo](https://user-images.githubusercontent.com/6584807/46808193-55094d80-cd9e-11e8-9645-a7ae6983af6e.png)
![usbmuxd](https://user-images.githubusercontent.com/6584807/46808213-5fc3e280-cd9e-11e8-8829-114983c74093.png)
![libmobile](https://user-images.githubusercontent.com/6584807/46808222-63f00000-cd9e-11e8-9c2a-59ba8d9c2474.png)

I delete the /var/db/lockdownd

![ls_var_db_lockdownd](https://user-images.githubusercontent.com/6584807/46808293-96016200-cd9e-11e8-8e96-2ac3ba7725f0.png)

**Comment by aliimran** [comment]
I am facing this issue ever since I updated to libimobiledevice version 1.2.0_3
