### ISSUE TITLE
ideviceinfo returns ProductType iPhone8,2 however idevicerestore detects iPhone7,2

### ISSUE THREAD

**Issue by pubsocent** [libimobiledevice/libimobiledevice#724]
ideviceinfo returns the following information:
...
ProductName: iPhone OS\nProductType: iPhone8,2\nProductVersion: 11.4\n
...

for that reason, I used the following restore command:
idevicerestore iPhone_5.5_11.4.1_15G77_Restore.ipsw -e -d -u <device_id>

I get the following response:
Code: 255
NOTE: using cached version data\nFound device in Recovery mode\nIdentified device as n61ap, iPhone7,2\nExtracting BuildManifest from IPSW\n

Reading data from version.xml\nopening device 05ac:1281...\nSetting to configuration 1\nSetting to interface 0:0\nopening device 05ac:1281...\nSetting to configuration 1\nSetting to interface 0:0\nERROR: Could not make sure this firmware is suitable for the current device. Refusing to continue.\n

I then try the restore command with the corresponding file for iPhone7,2
idevicerestore iPhone_4.7_11.4.1_15G77_Restore.ipsw -e -d -u ....
which works fine.

Any reason why ideviceinfo and idevicerestore for the same device detects different ProductType ?

**Comment by nikias** [comment]
Well what does ideviceinfo show for HardwareModel? That is the string used by libirecovery to figure out what device it is. Do you have a 6s plus or a 6?

**Comment by pubsocent** [comment]
ideviceinfo shows N66AP while idevicerestore shows n61ap
This is a iPhone 6s Plus.
