### ISSUE TITLE
how to get ios device cpu, memory, io usage, network traffic

### ISSUE THREAD

**Issue by yuzhidi** [libimobiledevice/libimobiledevice#729]
how to get ios device cpu, memory, io usage, network traffic

**Comment by LWSSS** [comment]
lao ge. ni zhao dao fang fa le ma? wo Xiang zhi dao de shi, chu le zai zhong duan yun xing , neng bu neng jiang zhe ge ku ji Cheng jin Xcode  dai ma li mian ,yong dai ma zhi xing .

**Comment by chanchifan** [comment]
I also want to know

**Comment by donmezburak** [comment]
is this still not available ?

**Comment by sriteja777** [comment]
@yuzhidi Were you able to get the cpu, memory usage?

**Comment by donmezburak** [comment]
No, i could not @sriteja777
