### ISSUE TITLE
can't compile file c

### ISSUE THREAD

**Issue by MastroGeppetto14** [libimobiledevice/libimobiledevice#732]
i would like use the library with c code, but i can't use any methods:

i installed with: 
./autogen.sh --prefix="$HOME/usr"
make && make install
without errors

i wrote the code:
```
#include "libimobiledevice.h"
#include "afc.h"
#include "lockdown.h"

int main(){
idevice_t device;
const char *uid = "asdf";
idevice_error_t error = idevice_new(&device, uid)
}
```

when i type `gcc hello.c -o hello`
i get this error: 
```
undefined reference to 'idevice_new'
collect2: error: ld returned 1 exit status
```

i'm using ubuntu 16 mate with raspberry pi3

please help me

**Comment by Blefish** [comment]
You need to link the library with -limobiledevice
Please close this as it is not a problem with libimobiledevice.
