### ISSUE TITLE
Why my iphone Xr can not support old version

### ISSUE THREAD

**Issue by Kanong017** [libimobiledevice/libimobiledevice#747]
when I was using the Libi mobile service to connect to my iPhone XR
I found that Libimobiledevice does not support older iTunes versions such as iTunes 12.6

But after I upgraded to iTunes 12.9, libimobiledevice was ready for normal use.
Error code display LOCKDOWN_E_INVALID_CONF

How should I solve it?!

iPhone XS had same question

**Comment by Kanong017** [comment]
@nikias

**Comment by nikias** [comment]
@Kanong017 First, you are talking about Windows? MacOS? What command are you trying to use? Are you using latest code? Build with `--enable-debug-code` and run the command with `-d` so you get more error output.
