### ISSUE TITLE
is it possible read "A" model iDevices ?

### ISSUE THREAD

**Issue by truonggiang0710** [libimobiledevice/libimobiledevice#749]
Libimobiledevice can read model number. Ex: MKT12. But I wonder It can read "A" model, ex: A1688,...
On device, we go to about and touch Model, It will display "A" model.

Thanks a lot.

**Comment by Johnny314** [comment]
yes you can get A Number of device

**Comment by truonggiang0710** [comment]
@Johnny314  how to do that ?

**Comment by nikias** [comment]
```
$ ideviceinfo -k RegulatoryModelNumber
```

**Comment by truonggiang0710** [comment]
Thanks @nikias
