### ISSUE TITLE
Idevicepair validate is working only for older os versions but not for new os versions

### ISSUE THREAD

**Issue by jxm0418** [libimobiledevice/libimobiledevice#752]
I tried to do "idevicepair validate" with new phone(iphone XR , OS -12.1.3) and it is throwing an error. But when I tried to do the same with old phone(iPhone 6s, OS - 10.2) it is working. 

I have provide the logs for your reference.  

M452:~ jxm0418$ idevice_id -l
9f140890c67da761e14a2f15e15c86e354fb3d92
00008020-00150D111AF8002E
M452:~ jxm0418$ idevicepair -u 9f140890c67da761e14a2f15e15c86e354fb3d92 validate
SUCCESS: Validated pairing with device 9f140890c67da761e14a2f15e15c86e354fb3d92
M452:~ jxm0418$ idevicepair -u 00008020-00150D111AF8002E validate
ERROR: Device 00008020-00150D111AF8002E returned unhandled error code -8

**Comment by nikias** [comment]
Are you sure you are using the latest code?

**Comment by jxm0418** [comment]
Yes I am using the latest code

**Comment by nikias** [comment]
Can you run ideviceinfo? Also can you configure with --enable-debug-code and run `idevicepair -d validate` and/or `ideviceinfo -d` ?

**Comment by jxm0418** [comment]
Last login: Thu Feb  7 09:36:03 on ttys000
M452:libimobiledevice jxm0418$ ideviceinfo
ActivationState: Activated
ActivationStateAcknowledged: true
BasebandActivationTicketVersion: V2
BasebandCertId: 165673526
BasebandChipID: 94
BasebandKeyHashInformation: 
 AKeyStatus: 64
 SKeyStatus: 2
BasebandMasterKeyHash: 1B41607650EBF11C6B39F41CB267DC64C121A9BCF44DBA5D28F55ACC86361BBA366554CD57B4C466055803E1EF81C870
BasebandRegionSKU: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
BasebandSerialNumber: QcMtXuc2kikAAAAA
BasebandStatus: BBInfoAvailable
BasebandVersion: 1.03.08
BluetoothAddress: e4:b2:fb:21:5b:94
BoardId: 12
BrickState: false
BuildVersion: 16D40
CPUArchitecture: arm64e
CarrierBundleInfoArray[1]: 
 0: 
  CFBundleIdentifier: com.apple.Verizon_LTE_US
  CFBundleVersion: 35.0.2
  GID1: bae0000000000000
  GID2: ffffffffffffffff
  IntegratedCircuitCardIdentity: 89148000004521204639
  InternationalMobileSubscriberIdentity: 311480451650869
  MCC: 311
  MNC: 480
  MobileEquipmentIdentifier: 35734409230880
  SIMGID1: uuAAAAAAAAA=
  SIMGID2: //////////8=
  Slot: kOne
  kCTPostponementInfoAvailable: SIMCarrierInfo
CertID: 165673526
ChipID: 32800
ChipSerialNo: QcMtXuc2kikAAAAA
DeviceClass: iPhone
DeviceColor: 1
DeviceName: Jagadeesh Marella’s iPhone
DieID: 5925341628989486
EthernetAddress: e4:b2:fb:21:92:6e
FirmwareVersion: iBoot-4513.230.10
FusingStatus: 3
GID1: bae0000000000000
GID2: ffffffffffffffff
HardwareModel: N841AP
HardwarePlatform: t8020
HasSiDP: true
HostAttached: true
IntegratedCircuitCardIdentity: 89148000004521204639
InternationalMobileEquipmentIdentity: 357344092308809
InternationalMobileEquipmentIdentity2: 357344092386227
InternationalMobileSubscriberIdentity: 311480451650869
InternationalMobileSubscriberIdentityOverride: false
MLBSerialNumber: C7H84170TZCL1P145
MobileEquipmentIdentifier: 35734409230880
MobileSubscriberCountryCode: 
MobileSubscriberNetworkCode: 480
ModelNumber: MT312
NonVolatileRAM: 
 auto-boot: dHJ1ZQ==
 backlight-level: MTQxNQ==
 boot-args: 
 bootdelay: MA==
 com.apple.System.tz0-size: MHg4RDAwMDAw
 oblit-begins: T2JsaXRUeXBlOiBPYmxpdGVyYXRlRGF0YVBhcnRpdGlvbi4gUmVhc29uOiB1bmtub3du
 obliteration: aGFuZGxlX21lc3NhZ2U6IE9ibGl0ZXJhdGlvbiBDb21wbGV0ZQo=
PRIVersion_Major: 0
PRIVersion_Minor: 0
PRIVersion_ReleaseNo: 25
PartitionType: GUID_partition_scheme
PasswordProtected: true
PhoneNumber: +1 (619) 928-8714
PkHash: Cd/6NgojZdvFdrua7kmhbhH9801PcduVa9Xn90f53Ro=
ProductName: iPhone OS
ProductType: iPhone11,8
ProductVersion: 12.1.3
ProductionSOC: true
ProtocolVersion: 2
ProximitySensorCalibration: f3oABTIAHgA0VmVBkQ4ZQgAAyEJrdilBB5AgQgAAFkNrdilBB5AgQgAAFkPJNIdCtspWwawPzUR4FM1E28rMRKJdzESjhIJBjS12QbXvhEHwYJRBAAAgQkEjK0OvZs9BAABIQjZo8ENymu9DUdMQRqNgmENWKHohASYIEjwnpEUFC79Dgp9IRQIAAAAAAAAf
RegionInfo: LL/A
SIM1IsEmbedded: false
SIMGID1: uuAAAAAAAAA=
SIMGID2: //////////8=
SIMStatus: kCTSIMSupportSIMStatusReady
SIMTrayStatus: kCTSIMSupportSIMTrayInsertedWithSIM
SerialNumber: F4GXK1Z7KXKP
SoftwareBehavior: EQAAAAAAAAAAAAAAAAAAAA==
SoftwareBundleVersion: 
SupportedDeviceFamilies[1]: 
 0: 1
TelephonyCapability: true
TimeIntervalSince1970: 1549583301.147145
TimeZone: America/Los_Angeles
TimeZoneOffsetFromUTC: -28800.000000
TrustedHostAttached: true
UniqueChipID: 5925341628989486
UniqueDeviceID: 00008020-00150D111AF8002E
UseRaptorCerts: true
Uses24HourClock: false
WiFiAddress: e4:b2:fb:35:b9:ff
WirelessBoardSerialNumber: 8A27C90020
iTunesHasConnected: true
kCTPostponementInfoPRIVersion: 0.0.25
kCTPostponementInfoServiceProvisioningState: true
kCTPostponementStatus: kCTPostponementStatusActivated
M452:libimobiledevice jxm0418$ 
 
Enabled debug mode
 
 
M452:libimobiledevice jxm0418$ idevicepair -d validate
15:50:05 lockdown.c:676 lockdownd_client_new(): device udid: 00008020-00150D111AF8002E
15:50:05 lockdown.c:405 lockdownd_query_type(): called
15:50:05 property_list_service.c:128 internal_plist_send(): sending 284 bytes
15:50:05 service.c:140 service_send(): sending 4 bytes
15:50:05 service.c:140 service_send(): sending 284 bytes
15:50:05 property_list_service.c:133 internal_plist_send(): sent 284 bytes
15:50:05 property_list_service.c:134 internal_plist_send(): printing 284 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>idevicepair</string>
    <key>Request</key>
    <string>QueryType</string>
</dict>
</plist>
15:50:05 property_list_service.c:193 internal_plist_receive_timeout(): initial read=4
15:50:05 property_list_service.c:202 internal_plist_receive_timeout(): 297 bytes following
15:50:05 property_list_service.c:215 internal_plist_receive_timeout(): received 297 bytes
15:50:05 property_list_service.c:241 internal_plist_receive_timeout(): printing 297 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Request</key>
    <string>QueryType</string>
    <key>Type</key>
    <string>com.apple.mobile.lockdown</string>
</dict>
</plist>
15:50:05 lockdown.c:421 lockdownd_query_type(): success with type com.apple.mobile.lockdown
15:50:05 property_list_service.c:128 internal_plist_send(): sending 5035 bytes
15:50:05 service.c:140 service_send(): sending 4 bytes
15:50:05 service.c:140 service_send(): sending 5035 bytes
15:50:05 property_list_service.c:133 internal_plist_send(): sent 5035 bytes
15:50:05 property_list_service.c:134 internal_plist_send(): printing 5035 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>idevicepair</string>
    <key>PairRecord</key>
    <dict>
        <key>DeviceCertificate</key>
        <data>
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN1akNDQWFLZ0F3SUJB
    Z0lCQURBTkJna3Foa2lHOXcwQkFRVUZBREFBTUI0WERURTVNREl3TmpFM01q
    WXcKTVZvWERUSTVNREl3TXpFM01qWXdNVm93QURDQ0FTSXdEUVlKS29aSWh2
    Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQUp5YVhvK1NQbmhhU2w2MlAv
    blIzUFd2OVFHdDNpMXppZmllUVAxN3dEVVpBcmVtemFPNDZNYjBrVzRaCkdk
    Zm9vYnVFZTlNc3BrQVNwNS9LUVN4UlRxempEL3BJcXFoNmNMUmhhMHRUOFpB
    Q1QwOXI5bmpaVjdmTmdWYTEKTm8zZ0hUY00rNzBxZ1FndFRJZ0d0UmVML05k
    WUk4QXFXS3VFZmlJc3A2Vy9RNDNZYVZKMXNVckNBQ0oyQS91aApYUWJmSVNz
    ekZvd3JUM05RaDhlQjV1RUk4ZFZjVzJ3S2JwT0JyTGVnK25COG5keEk4eUZZ
    SDBYcVIrMm84ZXhyCnhJOG5CM2VxZTNmV3ZEd21acVBxa1k2VUlIQ0VuWVNv
    dnVocUczVXV1UWZ0NGlDQXhBTUxSOGJITFlSbU83ZUQKUXVsZU5pRDRtZDBQ
    VzlES1BzMEtUMW9JWTJNQ0F3RUFBYU0vTUQwd0RBWURWUjBUQVFIL0JBSXdB
    REFkQmdOVgpIUTRFRmdRVTNiVG9zclFHbDIwVGlLWFVubENkNFh3Rk80TXdE
    Z1lEVlIwUEFRSC9CQVFEQWdXZ01BMEdDU3FHClNJYjNEUUVCQlFVQUE0SUJB
    UUI5Wk5RVU9ucDlXRUxNdlI1NkNRaUJjVlZzRFFuSkQ5QWNlOVJ4cWFVUGk1
    S2UKbytVa0JHYVdNYTM3YmdJbEU1MWU3YmVBeUtNbEZHUWEvMUxtVnFueGVI
    dDV3a3RqOFI0ZUx6N0M3YVdDQ2d1dgpKSk8wNk0xbUQ0anlrU2pQaWh4d3ZV
    RnZTZ2gzbXZobjdiSEFnWnJML2xHUENqYnNFeTBBUFMrOTRrMzhSazc3CnYy
    a2k5WkdXQUk1SU1CdElnb0hVLzhYdzNmTzNXc2RlMjlOWmJNdkxySVUwYllj
    TjRjVzViTXFobjAwbkdPTXEKZnNmNHBmRXJSTGpaSnhuaUVuUS9kOUZ4VlpO
    eW9rWTcybEtvSWRrWjROUjlMZTR5cmM3RGE4Qk5McUlCd0Z3Rwo1VXJBMnlR
    UWYwcXJlNUFJTEFRTEJObS9jNlZiVXFnTjJIeXN0V0QwCi0tLS0tRU5EIENF
        UlRJRklDQVRFLS0tLS0K
        </data>
        <key>EscrowBag</key>
        <data>
        aOR2e/E/eUJC9mRvl4lw2K2vY+5h8cXLsMl5CTjYiNQ=
        </data>
        <key>HostCertificate</key>
        <data>
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN1akNDQWFLZ0F3SUJB
    Z0lCQURBTkJna3Foa2lHOXcwQkFRVUZBREFBTUI0WERURTVNREl3TmpFM01q
    WXcKTVZvWERUSTVNREl3TXpFM01qWXdNVm93QURDQ0FTSXdEUVlKS29aSWh2
    Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQUx3ZmlWZmZnUGNHTjZ5M0pa
    TEhnZWRpUEdHU3A2UzdIbVFTZWRNejRGZHYvTTY1eFBxbUJTS2tlQUhVClhh
    MHJUUzVkUFlLSGNVVjhoOFVxcVdGb3kvb1FPZFdYRE9KT0hzbWY1YmZPWmo3
    TnljeVhNdnBiQXhIdG42UHEKaVRrK2xsdDhEeEhzUVlBM2ZDTzJSelB5VDBm
    dXkrSmQ1Z0o2ejZ0T0p2T0Qvd2pocm5IVzZoQWtqSCtqTVFKTwp1cy84bUlJ
    Zk1pSUxoNlcwN0pIV0tjVXMvNVBGTThpZW42anRKMzRtTWJSQWh2SEtVOHpy
    SENldm44ZkttaWNJClg2dXMwSVVqT1plL0Zxc2Q1WXd5MFowV3AwcmdrWnV3
    cjUwMGl4VHJyVUpHeEVDNmpsdTJnS0tJUE1tL0JlRkEKWVJLOGRYanJtTnZL
    TVhLa0p3Uy9EYUZkUjBFQ0F3RUFBYU0vTUQwd0RBWURWUjBUQVFIL0JBSXdB
    REFkQmdOVgpIUTRFRmdRVVB3SldYWVlxNG80MXloQkkvUG5VNFpwb3NYd3dE
    Z1lEVlIwUEFRSC9CQVFEQWdXZ01BMEdDU3FHClNJYjNEUUVCQlFVQUE0SUJB
    UUM1SWEwRnhYbjZ2YmY4MzJPa2QyOWR0bzVtdGs0dU81alhudERQMFp2Y3h2
    bHIKY2thZnRNa2R4VFczdE11Z2lxWGREdW5KQW5sRzRRS1FYRVgvdUhEck9s
    SDdQY3BMWUJlRXRYREJubG1uU21OaAowMWpFbVowa00zN1BzeFVTVXZFSlhQ
    cXdUNGtsTjJxWmZiMEw0VXNrSjdsN0xOdWdKVVBCb0hNUzVuRmVPZkNICkgy
    aElpcUhVMmtCdWl4YUhiZ1loWEk2bllGSDQ2VUtBUGo3UUdSVVlqcllzdDMy
    WE1nOHNiMUVGb0hKSkVHRGIKc2lFeWVQNWM4bVB0cWlNenhBQkZJZGRPRGRy
    T1FtNlF5RDFOdTZTRlYrekdrd0hrV3VNQTBmZFl1YmRUVVJJTQptQ0VqMVh0
    UlJXdTJiYy9wajdEVW1zaEZxclkwRUhiWWdXSFdRQ2VvCi0tLS0tRU5EIENF
        UlRJRklDQVRFLS0tLS0K
        </data>
        <key>HostID</key>
        <string>897BC59D-719E-4E09-8CFF-10321A5B3FE8</string>
        <key>RootCertificate</key>
        <data>
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyVENDQVpXZ0F3SUJB
    Z0lCQURBTkJna3Foa2lHOXcwQkFRVUZBREFBTUI0WERURTVNREl3TmpFM01q
    WXcKTVZvWERUSTVNREl3TXpFM01qWXdNVm93QURDQ0FTSXdEUVlKS29aSWh2
    Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQU5XS3U4M3ZWMXpkU1ZTVVlj
    NTNtbFpuWTJMbTY2TXZBNkg5TGdUS2k4c0dFdGRjQm5aODgxMHFkbmN0CnZF
    UVFsbm1hZHZjKyswL3hXeElzVWNuemJFMG1rOURPWVBGNWNkZi9mZzNVR3Q3
    VEZZSm00bjBxNThvSExWcnQKRGRCcWwwbDdpakJYcHhha1VhZWdyamxRMjZX
    anFtRkp0RXUxazhGVnNINmtXM25hNk5jc00rSnMyRkNpOTBXVQpkeFJoM3Fv
    blNCYktrUmtpTVkrV2VFY3l4MkdnU0FSZ0k5d1JOdGRyT0xsL24vdEU2N2VR
    Tk5ONVF4TFo2N0V0CkhNV0cxcjAxYUQ5MjVOQ21mUDM2OTNpVmxTY0pLYU5x
    dnFDOHFmN29iUmgvK2J4c1hFSHgrQi9FWUlCNzVnVEkKelhYZFhVbGRxTkRy
    S2dZV0dHKzBTUlh5djJzQ0F3RUFBYU15TURBd0R3WURWUjBUQVFIL0JBVXdB
    d0VCL3pBZApCZ05WSFE0RUZnUVU2MmhudDdnTmcvdWRFc0RhSGhLS3dZZkpG
    SkF3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCCkFES01idUlmQll0RC9SRk5w
    V2lmV1JLSGpoL1dCbG1jMkJ5eFRHdTBCbytZUGNvU2ZLcS9kTG5td3RjWjFx
    NWoKM0ZsTEdlOG9pYlN2eUZTTXBpWjJkR1RHdnNPMDF3TGpCYmlJK00xbjEz
    bDlGUmlIbHhnL05PclAxUjBqcytaRQpqWjVvTDJZa0djcVZDY0N6WHF5enQ1
    TXpyRTBmTGlvSFQvajZHNGNCcWFGVnNzZ2xHS0RkcmxJeDFydnQ4SWlaCm1W
    a21MTXZxV2Rmek5ZZVB2RWxrTHc1YmlvTUhhLzFHWUVKbEYxUnRTK2RHZjVj
    ZCtrczZrTDlWdnRab3dtcHYKSTJ3ZTYwdDFZUDQzaUUrdW03ME5YRXl5aU5h
    RHUxQkFWanVyRUlFM1NBcXN5WFpCUUx0c1RMeVdzbmYrUi8vbgp0bkY0Mmc5
    aC9GQjNDUjVzdmtzUVA2TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        </data>
        <key>SystemBUID</key>
        <string>6F511C79-3A18-4EF0-B7DF-ACA8EEACF9C3</string>
        <key>WiFiMACAddress</key>
        <string>e4:b2:fb:35:b9:ff</string>
    </dict>
    <key>Request</key>
    <string>ValidatePair</string>
    <key>ProtocolVersion</key>
    <string>2</string>
</dict>
</plist>
15:50:05 idevice.c:398 internal_connection_receive_timeout(): ERROR: usbmuxd_recv_timeout returned -35 (No such file or directory)
15:50:05 service.c:163 service_receive_with_timeout(): could not read data
15:50:05 property_list_service.c:193 internal_plist_receive_timeout(): initial read=0
15:50:05 property_list_service.c:195 internal_plist_receive_timeout(): initial read failed!
ERROR: Device 00008020-00150D111AF8002E returned unhandled error code -8

**Comment by nikias** [comment]
Oh!!! I know. Apple removed the ValidatePair command from lockdownd. See my commit message from  August 13, 2017:
```
commit 5a85432719fb3d18027d528f87d2a44b76fd3e12
Author: Nikias Bassen <nikias@gmx.li>
Date:   Sun Aug 13 00:12:16 2017 +0200

    lockdown: Don't explicitly validate pairing unless we're dealing with an older device

    On newer iOS version, ValidatePair is not mandatory to gain trusted host
    status. Starting with iOS 11, the ValidatePair request has been removed from
    lockdownd and will throw an error. This commit adds a version check so that
    ValidatePair is only called on devices prior iOS 7.
```
Please understand that the tool idevicepair technically is not required anymore since usbmuxd is handling the pairing. Nevertheless I will supply a fix for idevicepair.

**Comment by nikias** [comment]
Fixed with 8ef9e51d8514a441dc9b7d035954691d880a543e.

**Comment by jxm0418** [comment]
hey, This fix is not completely working.

M452:~ jxm0418$ idevicepair validate
ERROR: Device 8a28726f4e641c95e5df4f9c38fb87fe256b8c47 returned unhandled error code -2
M452:~ jxm0418$ idevicepair pair
SUCCESS: Paired with device 8a28726f4e641c95e5df4f9c38fb87fe256b8c47
M452:~ jxm0418$ idevicepair validate
SUCCESS: Validated pairing with device 8a28726f4e641c95e5df4f9c38fb87fe256b8c47
M452:~ jxm0418$ idevicepair unpair
SUCCESS: Unpaired with device 8a28726f4e641c95e5df4f9c38fb87fe256b8c47
M452:~ jxm0418$ idevicepair validate
ERROR: Device 8a28726f4e641c95e5df4f9c38fb87fe256b8c47 returned unhandled error code -2

**Comment by nikias** [comment]
@jxm0418 I noticed your reply that you deleted. Did it work now?

**Comment by jxm0418** [comment]
when the device is trusted it is good.
M452:~ jxm0418$ idevicepair validate
SUCCESS: Validated pairing with device 9f140890c67da761e14a2f15e15c86e354fb3d92

But when the device is not trusted. It is giving unhandled error -2 . I think it should throw error like "not paired" or something meaningful message.

M452:~ jxm0418$ idevicepair validate
ERROR: Device 9f140890c67da761e14a2f15e15c86e354fb3d92 returned unhandled error code -2

**Comment by nikias** [comment]
See 797a9e7e79d86427f40dbb82d271125b8c0b2485.
