### ISSUE TITLE
applications_plist_xml maybe null

### ISSUE THREAD

**Issue by xdeng** [libimobiledevice/libimobiledevice#758]
https://github.com/libimobiledevice/libimobiledevice/blob/0584aa90c93ff6ce46927b8d67887cb987ab9545/tools/idevicebackup2.c#L585
```
if(applications_plist_xml)
		free(applications_plist_xml);
```

**Comment by nikias** [comment]
Did you trigger this as an actual bug? Because calling `free(applications_plist_xml)` when `applications_plist_xml` is NULL is perfectly fine.

**Comment by xdeng** [comment]
@nikias   Sorry, I am wrong.
