### ISSUE TITLE
your ssl cert is expired

### ISSUE THREAD

**Issue by yshuman1** [libimobiledevice/libimobiledevice#768]
fatal: unable to access 'https://git.libimobiledevice.org/libimobiledevice.git/': SSL certificate problem: certificate has expired

**Comment by eQuinox-l** [comment]
Same problem here ...

**Comment by yshuman1** [comment]
> Same problem here ...

hey @eQuinox-l  if you want a temporary work around. you can do something like 
```
git config --global http.sslVerify false
```
and then switch it back to true once youve installed everything. thats what i ended up doing.

**Comment by nikias** [comment]
April fools. Haha. No, the cert refresh script seems to run too late. I bet tomorrow it will work again.

**Comment by nikias** [comment]
Confirmed working again.
