### ISSUE TITLE
iPhone XR UDID not ERROR: Invalid UDID specified

### ISSUE THREAD

**Issue by testerSunshine** [libimobiledevice/libimobiledevice#770]
When I typed the command I was told it was invalid UDID
```
ideviceinstaller -u 00008020-000C78810E2A002E -l 
ERROR: Invalid UDID specified
```
but iPhone is good.
environment： macOs 10.14.3

**Comment by nikias** [comment]
You are not using the latest code. This commit: https://github.com/libimobiledevice/ideviceinstaller/commit/f14def7cd9303a0fe622732fae9830ae702fdd7c fixes the problem.

**Comment by testerSunshine** [comment]
oh! thanks, i am using brew install --HEAD libimobiledevice, Now is the time to install using source code?

**Comment by nikias** [comment]
ideviceinstaller is another project, you have to install it separately.

**Comment by kontownik** [comment]
You need to compile it by yourself from the master branch.
