### ISSUE TITLE
Tests don't like being run in parallel

### ISSUE THREAD

**Issue by Cogitri** [libimobiledevice/libimobiledevice#777]
Running `make check -j8` makes random tests fail like this:

```
FAIL: hugecmp
=============

File does not exists
FAIL hugecmp.test (exit status: 2)
```

Running `make check -j1` makes them pass.

**Comment by nikias** [comment]
This is the wrong project. Should be libplist ;) I think they fail because some tests depend on an input from a previous test. Will isolate that.

**Comment by Cogitri** [comment]
Oops, my bad, worked on both of them at the same time and seems like I've mixed that up :)

**Comment by nikias** [comment]
Should be fixed with commit https://github.com/libimobiledevice/libplist/commit/8e5b802cb93a23bb4b97a0e12ff29d70e2064fe5

**Comment by Cogitri** [comment]
Thanks!
