### ISSUE TITLE
diagnostics_relay_query_ioregistry_entry(diagnostics_client, "ASPStorage", "", &node) return node==NULL

### ISSUE THREAD

**Issue by bugHappy** [libimobiledevice/libimobiledevice#778]
call  diagnostics_relay_query_ioregistry_entry(diagnostics_client, "ASPStorage", "", &node)
this API return DIAGNOSTICS_RELAY_E_SUCCESS but node's value is NULL
my ios ver 9.0.2...

**Comment by Kanong017** [comment]
call diagnostics_relay_query_ioregistry_entry(diagnostics_client, "", "ASPStorage", &node)

**Comment by bugHappy** [comment]
diagnostics_relay_query_ioregistry_entry(diagnostics_client, "", "ASPStorage", &node) 和diagnostics_relay_query_ioregistry_entry(diagnostics_client, "", "", &node) 的结果是一样。。感觉第二个参数根本没用。第二个参数不管写什么都是返回一样的。

**Comment by bugHappy** [comment]
@Kanong017 diagnostics_relay_query_ioregistry_entry(diagnostics_client, "", "ASPStorage", &node) 和diagnostics_relay_query_ioregistry_entry(diagnostics_client, "", "", &node) 的结果是一样。。感觉第二个参数根本没用。第二个参数不管写什么都是返回一样的。
