### ISSUE TITLE
Code issues with libimobiledevice

### ISSUE THREAD

**Issue by sctol** [libimobiledevice/libimobiledevice#780]
A few issues with libimobiledevice/common/socket.c

1. socket_check_fd() initializes a timeval struct outside of a retry loop around a select() statement.   This is non-portable as select() may modify the timeval structure to indicate the amount left on the timer, shrinking the timeout with each retry.  Consider moving initialization of the timeval structure inside the retry loop.

2. socket_receive_timeout() misinforms under  the condition when the socket has been closed by the peer.  In this case the select() from socket_check_fd() will return immediately with a 1 but the recv() call will return 0.  Together, these indicate the socket was closed.  socket_receive_timeout() then returns -EAGAIN.  It should probably return -ECONNRESET as -EAGAIN indicates the caller can try again.

3.  There are two very different implementations of socket.c contained in libusbmuxd and libimobiledevice that use the same function name space.  This may cause problems for code that links against both libraries such as with the applications in the tools directory.

**Comment by nikias** [comment]
Sync'ed with latest fixes from libusbmuxd:  https://github.com/libimobiledevice/libimobiledevice/commit/4727a86940875ab6f55cd0ddb7be99a705686f53
