### ISSUE TITLE
idevicebackup2 can't restore photo

### ISSUE THREAD

**Issue by fcgll520** [libimobiledevice/libimobiledevice#785]
photo can't be restored , why?

**Comment by mexmer** [comment]
it depends if you have cloud photo library enabled or not.
if you have cloud photo library enabled, then photos are stored on icloud, and are not present in backup.

to check, if photos are present in your backup, use some tool for itunes backup browsing.

**Comment by fcgll520** [comment]
it's really strange, i can restore it using itunes, this says that my backup file is right. But i still can't restore it using idevicebackup2.
