### ISSUE TITLE
Restore for the second time? it is failed?why?

### ISSUE THREAD

**Issue by Alisabb** [libimobiledevice/libimobiledevice#787]
ErrorCode 102: Failed to move the incomplete restore directory into place at path "/var/.backup.i" (MBErrorDomain/102). Underlying error: 鈥?backup.i鈥?couldn鈥檛 be moved to 鈥渧ar鈥?because an item with the same name already exists. at path "/var/.backup.i" (NSCocoaErrorDomain/516). Underlying error: The operation couldn鈥檛 be completed. File exists (NSPOSIXErrorDomain/17)..
Restore Failed (Error Code 102).

**Comment by Blefish** [comment]
Did you do a reboot after backup restore?

**Comment by nikias** [comment]
The above happens when you restore a backup without --reboot option, and restore again. I guess it is time to flip the options to make reboot default, and make it  a --no-reboot option instead.

**Comment by nikias** [comment]
Actually I already changed the option to --no-reboot and forgot about it. Are you using an older version maybe?
In any case, make sure to reboot the device after restore.

**Comment by Alisabb** [comment]
ok,thank you very much,and now it works.
