### ISSUE TITLE
problem in updating iOS13

### ISSUE THREAD

**Issue by UniqueLegend** [libimobiledevice/libimobiledevice#794]
I successfully updated my iPad Pro(10.5') yesterday with iPadOS-13 ipsw. Today I try to use the same method  to update my iPhone6s:

`> idevicerestore.exe -d ios13.ipsw`

but it goes repeatedly like 
```
FDR 0000000004CFE910 timeout waiting for command
FDR 0000000004CFE910 waiting for message...
No data to read
```

After it finished, my iphone ran into recovery mode...
Edit: Well after recvery mode it updates successfully. But any side-effect or could you explain what is the problem of `FDR 0000000004CFE910`?
![TIM截图20190605085758](https://user-images.githubusercontent.com/28732981/58922970-0fa3f100-8770-11e9-91b6-294174b546d4.png)

**Comment by Mgaskmg32org** [comment]
Hey, sorry but to say but it needs to be restored. This happened to me too but I had a backup.
I don’t know if it’s going to be the same story for you.
At the end I had to use a Mac with MacOS Catalina. Then I got iOS 13

**Comment by Mgaskmg32org** [comment]
Your ECID was reset too so I can’t fix that...

**Comment by UniqueLegend** [comment]
> Your ECID was reset too so I can’t fix that...
> But the Recovery fixes it
> 
> Does your phone still turn on and work?

Yes it works well. btw thks for developing this tool :)

**Comment by nikias** [comment]
FYI the messages
```
FDR 00000000******** waiting for message...
FDR 00000000******** timeout waiting for command
```
Can be safely ignored, those are not indicating any error at all.
