### ISSUE TITLE
Warning for people who tried restoring with iOS 13 IPSW (Me)

### ISSUE THREAD

**Issue by Mgaskmg32org** [libimobiledevice/libimobiledevice#795]
Welp can't delete this but just going to simplify it:
Never unplug a device when recovering heh

**Comment by mexmer** [comment]
if it's official ipsw, you can upload it to device with itunes.

**Comment by Mgaskmg32org** [comment]
Yes, but I don’t think iTunes with Win or Mac OS Mojave has compatibility with a iOS 13 Restore IPSW

**Comment by mexmer** [comment]
restoring IPSW only does validation of image signature against apple server, process itself is done by phone. itunes uploads ipsw into phone, then it restarts, and rest is done by phone, same way libimobile does it too.

**Comment by nikias** [comment]
I don't really know what is going on there but
a) This ticket was posted in the wrong project
b) Windows is not officially supported and tested (even though it should work but also might horribly fail)
c) ECID is the hardware ID (also called Chip ID) of the device and I am pretty sure it can't be deleted or erased or reset in any way
d) Recovery/DFU Mode restore is also possible with idevicerestore
