### ISSUE TITLE
Possibility to compile it as dynamic library

### ISSUE THREAD

**Issue by MrKris99** [libimobiledevice/libimobiledevice#796]
See subject.

**Comment by mexmer** [comment]
it does compile as dynamic library by default.

libsomething.so is dynamic linux library
libsomething.a is static library

**Comment by MrKris99** [comment]
I want to use ideviceinstaller tool as library in my project. But seems like it does not have API headers and only compiles as executable. @mexmer

**Comment by nikias** [comment]
@MrKris99 first, you posted this ticket under the wrong project, and second, ideviceinstaller is GPL licensed, so your project needs to be published under GPL aswell if you want to use ideviceinstaller's code.
