### ISSUE TITLE
how idevicebackup2 backup AddressBook.sqlitedb only?

### ISSUE THREAD

**Issue by Hiepars** [libimobiledevice/libimobiledevice#797]
i am trying to get AddressBook.sqlitedb by using idevicebackup2.
everything is ok but it takes too long to full backup.
How can i get AddressBook.sqlitedb without full backup. ?
thank you so much.

**Comment by mexmer** [comment]
you can't.
you can only do fullbackup (or partialbackup, if you already did full before).

there is no such functionality in apple backup service, to backup only one file.

**Comment by Hiepars** [comment]
@mexmer 
How iTools can do it?

**Comment by mexmer** [comment]
no, they can't do it either.

they just run backup until they receive that single file they want, then cancel rest of backup.

**Comment by Hiepars** [comment]
@mexmer 
How iTools can do it?
