### ISSUE TITLE
Check restore is done

### ISSUE THREAD

**Issue by Hiepars** [libimobiledevice/libimobiledevice#806]
How to check if restore is done?
thanks

**Comment by nikias** [comment]
Depends on what exactly you want to detect, and how. idevicerestore at some point will receive a success message knowing the restore is finished, while from the outside, e.g. with ideviceinfo, you could maybe tell if the version number changed. Won't help if a restore was performed to the same version though. From a libimobiledevice perspective though the device will disappear from normal mode, and reappear in normal mode. If restore failed it will stay in recovery mode.

**Comment by Hiepars** [comment]
thanks for your answer.
i am trying to restore a full backup package. 
i get message: 
The device should reboot now.
Restore Successful.

But on Iphone screen, restore is still in progressing.
I want to check restore is completely done.

**Comment by Hiepars** [comment]
Restore always in normal mode then i do not have any idea to check restore is done.

**Comment by Hiepars** [comment]
![IMG_0022](https://user-images.githubusercontent.com/28422681/60152092-6d74a780-9809-11e9-882c-ffc8cf7378dc.JPG)
this is iPhone screen when restore is done. how to check iPhone is displaying this screen?

**Comment by mexmer** [comment]
afaik this information is not available trough cable.

**Comment by Blefish** [comment]
I haven't been able to detect this either. But it might be possible to check if device is booted via springboardservices, for example, by querying the icons.

**Comment by Dantee296** [comment]
@Hiepars you can find this info probably in purplebuddy or springboard / backboard 
you gotta need to search for it.

**Comment by Hiepars** [comment]
@Dantee296 
1 - purplebuddy
how can i get this file : Com.apple.purplebuddy.plist ?
this file is in backup package so i can not get it if restore is not finished!

**Comment by sKerry-not-scarry** [comment]
Hi @Hiepars, were you able to find any solution?

**Comment by a-gunter** [comment]
`ideviceinfo -q com.apple.PurpleBuddy` will show information that will only get updated once springboard starts up. You can compare the output during the restore process vs once the "Restore Completed" screen is shown, and most likely there will be a difference somewhere

**Comment by Hiepars** [comment]
> Hi @Hiepars, were you able to find any solution?



> `ideviceinfo -q com.apple.PurpleBuddy` will show information that will only get updated once springboard starts up. You can compare the output during the restore process vs once the "Restore Completed" screen is shown, and most likely there will be a difference somewhere
