### ISSUE TITLE
iOS 13 no data for:  idevicediagnostics ioregentry AppleARMPMUCharger 

### ISSUE THREAD

**Issue by JonGabilondoAngulo** [libimobiledevice/libimobiledevice#823]
No data is returned by the service.
Is it because iOS13 does not want to or the code needs some tweak for 13 ?

**Comment by Orbif** [comment]
Did you try idevicediagnostics ioregentry AppleSmartBattery ?

**Comment by JonGabilondoAngulo** [comment]
It doesn't return any values.
It doesn't work in 12.2 either.
Doe sit work for you ?

**Comment by Orbif** [comment]
It works on iPhone 8 with iOS12. Didn't tried with iOS13 yet.

**Comment by Blefish** [comment]
Yes, AppleSmartBattery should be the key for iPhone 8 and later models. It works for me ever since iPhone 8 came out.

**Comment by JonGabilondoAngulo** [comment]
"idevicediagnostics ioregentry AppleSmartBattery",  does work on ios13 thanks.
