### ISSUE TITLE
If ios device is repaired and replaced with a new part, how to check the previous value

### ISSUE THREAD

**Issue by slin1972** [libimobiledevice/libimobiledevice#842]
Such as
After the repair
WIFI-Address  from  aa:bb:cc:dd:ee change to dd:bb:dd:cc
How do I get previous(old) wifi-address.

Looking forward to your reply

**Comment by nikias** [comment]
You can only get the old WiFi mac address before the repair. Afterwards there's no way to find the old one.

**Comment by slin1972** [comment]
But I have seen some software that can read the information before the phone is repaired. To determine if it has been repaired

so  
I really want to know how does it get the factory value

![image](https://user-images.githubusercontent.com/7867412/65384119-fb9cf300-dd50-11e9-9f01-33c718d727fc.png)

**Comment by nikias** [comment]
If you get me the software I may have a look.

**Comment by slin1972** [comment]
https://www.i4.cn
This is its website. You can download it there.
![image](https://user-images.githubusercontent.com/7867412/65398971-c1812f00-ddec-11e9-8a2d-4f7cb7d3895d.png)

**Comment by slin1972** [comment]
![image](https://user-images.githubusercontent.com/7867412/65399961-1e331880-ddf2-11e9-802e-cc040ee62a86.png)
![image](https://user-images.githubusercontent.com/7867412/65399996-4589e580-ddf2-11e9-8334-d69d832caf2b.png)

**Comment by Blefish** [comment]
The same interface is used by 3uTools, I don't know which one is the original.

**Comment by slin1972** [comment]
![image](https://user-images.githubusercontent.com/7867412/65404885-fac99700-de0c-11e9-9444-f965367b6a64.png)

**Comment by slin1972** [comment]
The data of i4 is more accurate.

**Comment by slin1972** [comment]
Can you see how it got the factory value?

**Comment by mexmer** [comment]
question is, if this are really genuine values. like on first screen, it shows even different model.

**Comment by slin1972** [comment]
The value is correct.

**Comment by slin1972** [comment]
@nikias

**Comment by slin1972** [comment]
I found that it automatically installed a software on my phone
![image](https://user-images.githubusercontent.com/7867412/66362306-c3ceb600-e9b4-11e9-8e66-e39526547e33.png)

**Comment by nikias** [comment]
Well the app can't run if you don't trust the developer. Installing is always possible.

**Comment by tangwanchao** [comment]
@slin1972 @nikias 
So how do you get the factory data?

**Comment by msk521** [comment]
any body can  get the factory data?

**Comment by truonggiang0710** [comment]
@slin1972 @tangwanchao @msk521 did you have any solution to do it?

**Comment by zuodd** [comment]
I dont think this post can be closed. No one give the answer. @mexmer @nikias @slin1972
