### ISSUE TITLE
Compile error with latest changes

### ISSUE THREAD

**Issue by Shankar-mac** [libimobiledevice/libimobiledevice#851]
When I try to compile with latest changes, I am getting below errors -> 

/Library/Developer/CommandLineTools/usr/bin/make  all-am
  CC       imobiledevice_la-imobiledevice.lo
imobiledevice.c:49894:49: error: use of undeclared identifier
      'RESTORE_E_INVALID_CONF'; did you mean 'RESTORE_E_INVALID_ARG'?
  __pyx_t_2 = __Pyx_PyInt_From_restored_error_t(RESTORE_E_INVALID_CONF); i...
                                                ^~~~~~~~~~~~~~~~~~~~~~
                                                RESTORE_E_INVALID_ARG
../include/libimobiledevice/restore.h:37:2: note: 'RESTORE_E_INVALID_ARG'
      declared here
        RESTORE_E_INVALID_ARG          = -1,
        ^
imobiledevice.c:49918:49: error: use of undeclared identifier
      'RESTORE_E_DICT_ERROR'; did you mean 'RESTORE_E_PLIST_ERROR'?
  __pyx_t_2 = __Pyx_PyInt_From_restored_error_t(RESTORE_E_DICT_ERROR); if ...
                                                ^~~~~~~~~~~~~~~~~~~~
                                                RESTORE_E_PLIST_ERROR
../include/libimobiledevice/restore.h:38:2: note: 'RESTORE_E_PLIST_ERROR'
      declared here
        RESTORE_E_PLIST_ERROR          = -2,
        ^
imobiledevice.c:49954:49: error: use of undeclared identifier
      'RESTORE_E_START_RESTORE_FAILED'
  __pyx_t_2 = __Pyx_PyInt_From_restored_error_t(RESTORE_E_START_RESTORE_...
                                                ^
3 errors generated.

Is it related to missing parameters or changing the names should work? Please suggest.

**Comment by nikias** [comment]
Fixed with commit 656b96ca6caac90eb78266bd1fabe7b76bcb8c03.
