### ISSUE TITLE
Unhandled Status Code 133 on iPhone 11 (N104AP)

### ISSUE THREAD

**Issue by iM4CH3T3** [libimobiledevice/libimobiledevice#857]
Getting Unhandled Status Code 133 on iPhone 11 (N104AP) when trying to restore iOS 13.1.2 
![Image](https://i.imgur.com/CUxq0Uj.jpg)

All your tools on latest version , just installed everything today freshly

**Comment by nikias** [comment]
Can you run with -d ? Then I can see the whole request to the TSS.

**Comment by iM4CH3T3** [comment]
That’s with -d 

![Image](https://i.imgur.com/qLanLpV.jpg)

**Comment by nikias** [comment]
Can you please paste the plist output as text and not as an image? You might want to use a gist or attach it as a file since it's probably large.

**Comment by iM4CH3T3** [comment]
I hope u can open it 

https://t.co/J0OGkbZZXk?amp=1

**Comment by nikias** [comment]
You are definitely not using the latest source of idevicerestore. I could tell from `libauthinstall-293.1.16` and the missing tags for `@eUICC,Ticket` etc.

**Comment by nikias** [comment]
Also you posted this ticket in the wrong project, this usually needs to go to idevicerestore :)

**Comment by iM4CH3T3** [comment]
So new version should fix that right ?
Sorry btw

**Comment by nikias** [comment]
That's fine but posting issues when not running the latest version isn't really helpful, since I was going to search for a problem that is probably not there anymore. If this problem persists even with latest code, open a new ticket on https://github.com/libimobiledevice/idevicerestore/issues.

**Comment by iM4CH3T3** [comment]
Thx very much 
Sorry again for wasting your time 🙈
