### ISSUE TITLE
idevicesyslog not showing logs on iOS13

### ISSUE THREAD

**Issue by christopherfujino** [libimobiledevice/libimobiledevice#861]
Using `idevicesyslog` I am not able to see any application logs from an iPhone Xr with iOS 13.1. I am using ToT libimobiledevice [60823f9eeb3f09cd8083f613522d01e21d2f6d2d](https://github.com/libimobiledevice/libimobiledevice/commit/60823f9eeb3f09cd8083f613522d01e21d2f6d2d). The only logs I can see are when I first connect the phone via USB [here](https://gist.github.com/christopherfujino/6e22a26d15c91fadd9feaf8fde97c5b4).

I can see app logs when I run the app via Xcode. This is causing https://github.com/flutter/flutter/issues/41133.

**Comment by nikias** [comment]
If you run the app via Xcode, you get direct stdout and stderr output via debugserver. The output via idevicesyslog is whatever the device sends and cannot be controlled from the client side. Apple decided to silence app log output on iOS 9 or 10 iirc.

**Comment by christopherfujino** [comment]
Hmm, I'm not sure what you mean by "Apple decided to silence app log output on iOS 9 or 10." FWIW I am able to read app logs in `idevicesyslog` from the same app run on iOS 12.4.2.

**Comment by nikias** [comment]
Well then that must be another change in iOS 13, but it doesn't change the fact that the syslog service ("syslog relay") just relays whatever the device has for you. If the app output isn't there idevicesyslog can't change that. Have you checked the console.app output for your device or via Xcode -> Window -> Devices and Simulators -> select device -> system log?

**Comment by christopherfujino** [comment]
Ahh, so I'm not seeing my app logs under console.app either. We will try to address this by switching to using OS log. Thank you for help @nikias!
