### ISSUE TITLE
I use mobileSync service to add contact to my iphone,but get "DLMessageDisconnect" message 

### ISSUE THREAD

**Issue by mroger-tech** [libimobiledevice/libimobiledevice#864]
![image](https://user-images.githubusercontent.com/33676188/67257735-e934e700-f4bf-11e9-8249-3cb797ac1983.png)

**Comment by mexmer** [comment]
did you enable contact sync with desktop?

**Comment by Roger-mazheng** [comment]
@mexmer No,what does "...with desktop" mean?  i can get contacts and delete contacts,but only can not add contacts.

**Comment by mroger-tech** [comment]
> did you enable contact sync with desktop?

thanks for your reply anyway,can you tell me the detail about add contacts to iphone?

thank you very much!!!

**Comment by mexmer** [comment]
you need to check value of com.apple.mobile.tethered_sync
if it contains DisableTethered - false or 0 (value depends on version of ios) under "Contacts", you can sync, if it's True or 1, then you can't sync with PC and need to change it (if it's 1, then set 0, if it's True, set False).

after that, sync should work.

synced contacts should appear in "From my computer" category, or something like that.

**Comment by mroger-tech** [comment]
> you need to check value of com.apple.mobile.tethered_sync
> if it contains DisableTethered - false or 0 (value depends on version of ios) under "Contacts", you can sync, if it's True or 1, then you can't sync with PC and need to change it (if it's 1, then set 0, if it's True, set False).
> 
> after that, sync should work.
> 
> synced contacts should appear in "From my computer" category, or something like that.

Thanks!

I will try your method.

**Comment by mroger-tech** [comment]
> > you need to check value of com.apple.mobile.tethered_sync
> > if it contains DisableTethered - false or 0 (value depends on version of ios) under "Contacts", you can sync, if it's True or 1, then you can't sync with PC and need to change it (if it's 1, then set 0, if it's True, set False).
> > after that, sync should work.
> > synced contacts should appear in "From my computer" category, or something like that.
> 
> Thanks!
> 
> I will try your method.

![image](https://user-images.githubusercontent.com/33676188/67458438-cb56b600-f668-11e9-806f-2ba3e7629467.png)

I use "ideviceinfo.exe -x -q com.apple.mobile.tethered_sync" to check the value, but get nothing(iphone5s,ios12.4.2)

**Comment by mexmer** [comment]
that means, it's on default values, which is disabled sync with desktop

should look like this
![image](https://user-images.githubusercontent.com/5429727/67500215-a96a2d00-f682-11e9-93b8-b7785b62d479.png)

**Comment by mroger-tech** [comment]
> that means, it's on default values, which is disabled sync with desktop
> 
> should look like this
> ![image](https://user-images.githubusercontent.com/5429727/67500215-a96a2d00-f682-11e9-93b8-b7785b62d479.png)

I'm sorry to bother you again,I try to set value of com.apple.mobile.tethered_sync like yours, but the error still exist,when i call "mobilesync_remap_identifiers" ,the error occur,and the return error code is -2.


![image](https://user-images.githubusercontent.com/33676188/69241045-d4d82d00-0bd8-11ea-9bce-8fa7fd0e0527.png)

**Comment by mexmer** [comment]
detailed log will help
-2 is MOBILESYNC_E_PLIST_ERROR, which means response from device is invalid, but it might also mean, there is no remap identifier map in response. for example if you don't change any data, it will not return new map.

**Comment by mroger-tech** [comment]
hello mexmer,detail log bellow:

![image](https://user-images.githubusercontent.com/33676188/69401281-9ef98c80-0d2f-11ea-96ba-38c81e73808e.png)
![image](https://user-images.githubusercontent.com/33676188/69401303-ae78d580-0d2f-11ea-845c-125b7e68041d.png)
![image](https://user-images.githubusercontent.com/33676188/69401320-bb95c480-0d2f-11ea-9b51-69550ab8c6b5.png)
![image](https://user-images.githubusercontent.com/33676188/69401334-c7818680-0d2f-11ea-83a5-b783bf55fd1c.png)
![image](https://user-images.githubusercontent.com/33676188/69401354-d700cf80-0d2f-11ea-9796-ed751f7d271b.png)
![image](https://user-images.githubusercontent.com/33676188/69401380-ea139f80-0d2f-11ea-9ef3-2098af1b8373.png)
![image](https://user-images.githubusercontent.com/33676188/69401389-f1d34400-0d2f-11ea-96f7-b97754382c22.png)

**Comment by mexmer** [comment]
from your log seems you sent only one contact, then disconeccted. you can't call remap after disconnect, remap is always called after sending changes, so it will tell you record was remapped to which id.

although issue might be also, that you using ID 0 for new record, you must specify positive integer value, that is higher than last id of received record. since you get no data, you will use 1, not 0, that's probly why instead of confirming new record, connection was closed.

when i add new entries to phone, i use lastentityindex + 100000, reason is, that cloud synchronized contacts cannot be retrieved with mobilesync, and i don't want to risk overwriting cloud contacts.

**Comment by mroger-tech** [comment]
> from your log seems you sent only one contact, then disconeccted. you can't call remap after disconnect, remap is always called after sending changes, so it will tell you record was remapped to which id.
> 
> although issue might be also, that you using ID 0 for new record, you must specify positive integer value, that is higher than last id of received record. since you get no data, you will use 1, not 0, that's probly why instead of confirming new record, connection was closed.
> 
> when i add new entries to phone, i use lastentityindex + 100000, reason is, that cloud synchronized contacts cannot be retrieved with mobilesync, and i don't want to risk overwriting cloud contacts.

1. In fact, after i sent changes (call mobilesync_send_changes),i call the function mobilesync_remap_identifiers,and the function(mobilesync_remap_identifiers)give me "disconnect"response back.

2.I modify my code, i use  ID 100000  for new record, but still get "disconnect" response back.

Note: I removed all record from my iphone.

**Comment by mexmer** [comment]
when i sync contact i do following, first i query state of sync with computer from lockdown

query
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Domain</key>
<string>com.apple.mobile.tethered_sync</string>
<key>Label</key>
<string>Apple Client version 1.0</string>
<key>Request</key>
<string>GetValue</string>
</dict>
</plist>
```
response
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Contacts</key>
<dict>
<key>DisableTethered</key>
<false/>
<key>SyncingOS</key>
<string>Windows</string>
</dict>
</dict>
</plist>
```
if disablethered is true or not present, you need to set it to false.

then i do following steps

1) start com.apple.mobilesync service, communication over mobilesync link (which needs to be started with SSL as of IOS 13.0) looks as following (mind communication log is from software based on libimobile, so looks somewhat different) and perform version exchange - equivalent to  **mobilesync_client_start_service()**

2) request data sync from device - equivalent to **mobilesync_start()**

3) application receives all contacts from device  - equivalent to **mobilesync_get_all_records_from_device()** after you need to send **mobilesync_acknowledge_changes_from_device()**

4) change direction of changes - equivalent to **mobilesync_ready_to_send_changes_from_computer()**

5) send all changed record to device - equivalent to **mobilesync_send_changes()**

6) receive map of remapped record ids - equivalent to **mobilesync_remap_identifiers()**

7) finish communication - equivalent to **mobilesync_finish()**

**Comment by mroger-tech** [comment]
> when i sync contact i do following, first i query state of sync with computer from lockdown
> 
> query
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> <key>Domain</key>
> <string>com.apple.mobile.tethered_sync</string>
> <key>Label</key>
> <string>Apple Client version 1.0</string>
> <key>Request</key>
> <string>GetValue</string>
> </dict>
> </plist>
> ```
> 
> response
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> <key>Contacts</key>
> <dict>
> <key>DisableTethered</key>
> <false/>
> <key>SyncingOS</key>
> <string>Windows</string>
> </dict>
> </dict>
> </plist>
> ```
> 
> if disablethered is true or not present, you need to set it to false.
> 
> then i do following steps
> 
> 1. start com.apple.mobilesync service, communication over mobilesync link (which needs to be started with SSL as of IOS 13.0) looks as following (mind communication log is from software based on libimobile, so looks somewhat different) and perform version exchange - equivalent to  **mobilesync_client_start_service()**
> 2. request data sync from device - equivalent to **mobilesync_start()**
> 3. application receives all contacts from device  - equivalent to **mobilesync_get_all_records_from_device()** after you need to send **mobilesync_acknowledge_changes_from_device()**
> 4. change direction of changes - equivalent to **mobilesync_ready_to_send_changes_from_computer()**
> 5. send all changed record to device - equivalent to **mobilesync_send_changes()**
> 6. receive map of remapped record ids - equivalent to **mobilesync_remap_identifiers()**
> 7. finish communication - equivalent to **mobilesync_finish()**

As the log i show you before ,when i add contact to iphone , I did the same steps as yours. but i  never get the right response.I have no idea any more, can you show me your detail log when you add contacts?

Thank you very much!

**Comment by mexmer** [comment]
```xml
73.1141 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>DLMessageVersionExchange</string>
<integer>300</integer>
<integer>100</integer>
</array>
</plist>
73.1141 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>DLMessageVersionExchange</string>
<string>DLVersionsOk</string>
<integer>300</integer>
<integer>100</integer>
</array>
</plist>
73.1175 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>DLMessageDeviceReady</string>
</array>
</plist>
73.1176 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageSyncDataClassWithDevice</string>
<string>com.apple.Contacts</string>
<string>---</string>
<string>2019-12-18 12-55-34 +0100</string>
<integer>106</integer>
<string>___EmptyParameterString___</string>
</array>
</plist>
73.1584 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageSyncDataClassWithComputer</string>
<string>com.apple.Contacts</string>
<string>2019-12-18 12-54-55 +0100</string>
<string>Dec 18 2019 12:55:34 +0100</string>
<string>SDSyncTypeSlow</string>
<integer>106</integer>
<string>___EmptyParameterString___</string>
</array>
</plist>
73.1584 [5:link:10292] 13D9AA10 Link timeout for link (1060/49602) set to 10000 (0)
73.1585 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageGetChangesFromDevice</string>
<string>com.apple.Contacts</string>
</array>
</plist>
 73.1627 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageProcessChanges</string>
<string>com.apple.Contacts</string>
<dict/>
<true/>
<string>___EmptyParameterString___</string>
</array>
</plist>
73.1627 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageAcknowledgeChangesFromDevice</string>
<string>com.apple.Contacts</string>
</array>
</plist>
73.1916 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageDeviceReadyToReceiveChanges</string>
<string>com.apple.Contacts</string>
</array>
</plist>
73.1916 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>DLMessagePing</string>
<string>Preparing to get changes for device</string>
</array>
</plist>
 73.1926 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageProcessChanges</string>
<string>com.apple.Contacts</string>
<dict>
<key>16777221</key>
<dict>
<key>com.apple.syncservices.RecordEntityName</key>
<string>com.apple.contacts.Contact</string>
<key>display as company</key>
<string>person</string>
<key>first name</key>
<string>first</string>
<key>last name</key>
<string>last</string>
</dict>
</dict>
<true/>
<string>___EmptyParameterString___</string>
</array>
</plist>
73.2851 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageRemapRecordIdentifiers</string>
<string>com.apple.Contacts</string>
<dict>
<key>16777221</key>
<string>8247</string>
</dict>
</array>
</plist>
73.2852 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageProcessChanges</string>
<string>com.apple.Contacts</string>
<dict>
<key>16777220</key>
<dict>
<key>com.apple.syncservices.RecordEntityName</key>
<string>com.apple.contacts.Phone Number</string>
<key>contact</key>
<array>
<string>16777221</string>
</array>
<key>type</key>
<string>mobile</string>
<key>value</key>
<string>123456789</string>
</dict>
</dict>
<false/>
<string>___EmptyParameterString___</string>
</array>
</plist>
73.2877 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageRemapRecordIdentifiers</string>
<string>com.apple.Contacts</string>
<dict>
<key>16777220</key>
<string>3/8247/0</string>
</dict>
</array>
</plist>
73.2877 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageProcessChanges</string>
<string>com.apple.Contacts</string>
<dict/>
<true/>
<string>___EmptyParameterString___</string>
</array>
</plist>
 73.2893 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageRemapRecordIdentifiers</string>
<string>com.apple.Contacts</string>
<string>___EmptyParameterString___</string>
</array>
</plist>
73.2893 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageFinishSessionOnDevice</string>
<string>com.apple.Contacts</string>
</array>
</plist>
 73.3084 [6:data:10292] Received plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>SDMessageDeviceFinishedSession</string>
<string>com.apple.Contacts</string>
</array>
</plist>
73.8086 [6:data:10292] Sending XML plist: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
<string>DLMessageDisconnect</string>
<string>All done, thanks for the memories</string>
</array>
</plist>
```

**Comment by mroger-tech** [comment]
> ```
> 73.1141 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>DLMessageVersionExchange</string>
> <integer>300</integer>
> <integer>100</integer>
> </array>
> </plist>
> 73.1141 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>DLMessageVersionExchange</string>
> <string>DLVersionsOk</string>
> <integer>300</integer>
> <integer>100</integer>
> </array>
> </plist>
> 73.1175 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>DLMessageDeviceReady</string>
> </array>
> </plist>
> 73.1176 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageSyncDataClassWithDevice</string>
> <string>com.apple.Contacts</string>
> <string>---</string>
> <string>2019-12-18 12-55-34 +0100</string>
> <integer>106</integer>
> <string>___EmptyParameterString___</string>
> </array>
> </plist>
> 73.1584 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageSyncDataClassWithComputer</string>
> <string>com.apple.Contacts</string>
> <string>2019-12-18 12-54-55 +0100</string>
> <string>Dec 18 2019 12:55:34 +0100</string>
> <string>SDSyncTypeSlow</string>
> <integer>106</integer>
> <string>___EmptyParameterString___</string>
> </array>
> </plist>
> 73.1584 [5:link:10292] 13D9AA10 Link timeout for link (1060/49602) set to 10000 (0)
> 73.1585 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageGetChangesFromDevice</string>
> <string>com.apple.Contacts</string>
> </array>
> </plist>
>  73.1627 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageProcessChanges</string>
> <string>com.apple.Contacts</string>
> <dict/>
> <true/>
> <string>___EmptyParameterString___</string>
> </array>
> </plist>
> 73.1627 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageAcknowledgeChangesFromDevice</string>
> <string>com.apple.Contacts</string>
> </array>
> </plist>
> 73.1916 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageDeviceReadyToReceiveChanges</string>
> <string>com.apple.Contacts</string>
> </array>
> </plist>
> 73.1916 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>DLMessagePing</string>
> <string>Preparing to get changes for device</string>
> </array>
> </plist>
>  73.1926 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageProcessChanges</string>
> <string>com.apple.Contacts</string>
> <dict>
> <key>16777221</key>
> <dict>
> <key>com.apple.syncservices.RecordEntityName</key>
> <string>com.apple.contacts.Contact</string>
> <key>display as company</key>
> <string>person</string>
> <key>first name</key>
> <string>first</string>
> <key>last name</key>
> <string>last</string>
> </dict>
> </dict>
> <true/>
> <string>___EmptyParameterString___</string>
> </array>
> </plist>
> 73.2851 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageRemapRecordIdentifiers</string>
> <string>com.apple.Contacts</string>
> <dict>
> <key>16777221</key>
> <string>8247</string>
> </dict>
> </array>
> </plist>
> 73.2852 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageProcessChanges</string>
> <string>com.apple.Contacts</string>
> <dict>
> <key>16777220</key>
> <dict>
> <key>com.apple.syncservices.RecordEntityName</key>
> <string>com.apple.contacts.Phone Number</string>
> <key>contact</key>
> <array>
> <string>16777221</string>
> </array>
> <key>type</key>
> <string>mobile</string>
> <key>value</key>
> <string>123456789</string>
> </dict>
> </dict>
> <false/>
> <string>___EmptyParameterString___</string>
> </array>
> </plist>
> 73.2877 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageRemapRecordIdentifiers</string>
> <string>com.apple.Contacts</string>
> <dict>
> <key>16777220</key>
> <string>3/8247/0</string>
> </dict>
> </array>
> </plist>
> 73.2877 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageProcessChanges</string>
> <string>com.apple.Contacts</string>
> <dict/>
> <true/>
> <string>___EmptyParameterString___</string>
> </array>
> </plist>
>  73.2893 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageRemapRecordIdentifiers</string>
> <string>com.apple.Contacts</string>
> <string>___EmptyParameterString___</string>
> </array>
> </plist>
> 73.2893 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageFinishSessionOnDevice</string>
> <string>com.apple.Contacts</string>
> </array>
> </plist>
>  73.3084 [6:data:10292] Received plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>SDMessageDeviceFinishedSession</string>
> <string>com.apple.Contacts</string>
> </array>
> </plist>
> 73.8086 [6:data:10292] Sending XML plist: 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <array>
> <string>DLMessageDisconnect</string>
> <string>All done, thanks for the memories</string>
> </array>
> </plist>
> ```

Thanks for you reply, I will carefully compare your logs to find out what's wrong with me.

**Comment by mroger-tech** [comment]
I finally found the problem. It was the encoding of my text. I changed the encoding to utf8 and got it right.
It was a stupid mistake.
Finally, thanks for @mexmer's continued help.

**Comment by mexmer** [comment]
good to know there is no issue with library itself. and yes, when you use text (plist) format you must use UTF-8

**Comment by zuodd** [comment]
> good to know there is no issue with library itself. and yes, when you use text (plist) format you must use UTF-8

Hi @mexmer Is there any way to get contacts via imobiledevice binary library without coding?

**Comment by zuodd** [comment]
> good to know there is no issue with library itself. and yes, when you use text (plist) format you must use UTF-8

I mean just use cmd from the terminal but no resource file compile and coding.
