### ISSUE TITLE
Build static?

### ISSUE THREAD

**Issue by LinuxEngr** [libimobiledevice/libimobiledevice#87]
I want to use libimobiledevice on an ARM device without an MMU. So, I have been working on building libplist, libusbmuxd, libxml, and libimobiledevice, with my toolchain, statically.

These are all quite messy. The configure scripts sometimes want Python. Sigh. Has anyone build libimobiledevice and all its required libraries, statically? Any help?

**Comment by dleonard00** [comment]
@LinuxEngr I would like to do something similar and am curious if you were able to find success in building libimobiledevice and all its required libraries statically?

**Comment by avicohn** [comment]
I never did succeed in building libimobiledevice. Sorry.
