### ISSUE TITLE
usb tethering setup

### ISSUE THREAD

**Issue by sancelot** [libimobiledevice/libimobiledevice#875]
What are the minimal packages needed to enable usb tethering ?

I compiled
* libplist
* libusbmuxd
* libimobiledevice

This provide some binaries. When deploying , what needs being launched or setted up ?

**Comment by nikias** [comment]
You need a kernel driver which should already be part of a recent Linux kernel. More than that you might need usbmuxd so it puts the device in the right configuration, and then it will appear as a USB network device.

**Comment by sancelot** [comment]
Fine. 
* usbmuxd  added ..
