### ISSUE TITLE
OpenSSL 1.1.1d  compilation issues

### ISSUE THREAD

**Issue by Dantee296** [libimobiledevice/libimobiledevice#891]
how to fix these issues

Undefined symbols for architecture x86_64:
  "_X509_set1_notAfter", referenced from:
      _pair_record_generate_keys_and_certs in libinternalcommon.a(userpref.o)
  "_X509_set1_notBefore", referenced from:
      _pair_record_generate_keys_and_certs in libinternalcommon.a(userpref.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Parabak** [comment]
Hi @Dantee296 , I have the same issue. Did you find the reason?
Thanks.

**Comment by guyingzhao** [comment]
export openssl_LIBS="-L/usr/local/Cellar/openssl/1.0.2s/lib/ -lssl -lcrypto -lz"
export openssl_CFLAGS=-I/usr/local/Cellar/openssl/1.0.2s/include/

I solved this by export variable above
