### ISSUE TITLE
Is Wifi Sync only supported via iTunes provided usbmuxd?

### ISSUE THREAD

**Issue by sprhawk** [libimobiledevice/libimobiledevice#919]
I cannot find devices via `idevice_id -n`, but I saw some issues related to wifi sync. So I guess it is only supported via Apple provided usbmuxd service?

`ideviceinfo -n -q com.apple.mobile.wireless_lockdown`
will get following:
```
BonjourFullServiceName: dd:1c:79:33:2d:1c@fe80::ec5d:02ce:de16:3ce2._apple-mobdev2._tcp.local.
EnableWifiConnections: true
EnableWifiDebugging: false
SupportsWifi: true
SupportsWifiSyncing: true
```

And I quickly browse source code in usbmuxd, it seems it doesn't have network / wifi sync related code.

Edit:
I enabled wifi with iTunes/Finder(10.15.x), and I see new option (EnableWifiConnections: true), and did discovered service by avahi-discover, but tools inside libimobiledevice cannot retreive list

**Comment by mohammad-ghassemi** [comment]
Try to use https://github.com/tihmstar/usbmuxd2.

**Comment by sprhawk** [comment]
> Try to use https://github.com/tihmstar/usbmuxd2.

Cool, thanks

**Comment by Tkd-Alex** [comment]
Any tutorial or documentation about usbmuxd2 and libimobiledevice ?

**Comment by mohammad-ghassemi** [comment]
Not any that I know of! You can check this Twitter thread:
https://twitter.com/tihmstar/status/1171829247729647616
