### ISSUE TITLE
libimobiledevice should use Secure Transport over libcurl on Apple platforms

### ISSUE THREAD

**Issue by rickmark** [libimobiledevice/libimobiledevice#925]
Because it's difficult to diagnose behavioural differences between libcurl and Apple's secure transport, and because ST supports certificate transparency (in addition to being controlled by the authoritative source for TLS negotiation to Apple endpoints) `download_file` should use the Secure Transport API on macOS.

**Comment by nikias** [comment]
I think this one was supposed to be filed under idevicerestore :)

**Comment by rickmark** [comment]
What about TSS?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexandre-janniaux** [comment]
Hi,

Should it really now that it has been deprecated ? https://developer.apple.com/documentation/security/secure_transport?language=objc

**Comment by rickmark** [comment]
Yeah, gonna just close this as "wont-fix" for now
