### ISSUE TITLE
How can I use this as a dependency

### ISSUE THREAD

**Issue by AirKetchPLAYZ** [libimobiledevice/libimobiledevice#942]
So I `make install`ed it and it said it was installed to /usr/local/lib. SO in eclipse I go to my project settings and add that to the include path, but I get this error  
```
main.cpp:2:10: fatal error: libimobiledevice.h: No such file or directory
    2 | #include "libimobiledevice.h"
      |          ^~~~~~~~~~~~~~~~~~~~
```  
Sorry if this is stupid and im missing something, but how can I use this (its a C++ project)

**Comment by nikias** [comment]
You need to add /usr/local/include to your list of include paths, and then you need to include it this way:
```
#include <libimobiledevice/libimobiledevice.h>
#include <libimobiledevice/lockdownd.h>
// add more includes depending on what you're doing
```
