### ISSUE TITLE
ERROR: No device found!

### ISSUE THREAD

**Issue by leonnfang** [libimobiledevice/libimobiledevice#946]
hi,
i am using win10 as os, and running libimobiledevice in VS code. in the command prompt, i tried to use ''' idevice -l''' i kept getting error  '''Error: No device found!''' 
iphone was unlocked and usb was connected properly.

**Comment by elekven-m** [comment]
Install iTunes. Under Windows' Settings -> Apps & features -> iTunes -> advanced options make sure that iTunes Mobile Device Helper is ON.

**Comment by leonnfang** [comment]
Thank you!
