### ISSUE TITLE
restore.h reboot wont reboot from normal or recovery.

### ISSUE THREAD

**Issue by Adderally** [libimobiledevice/libimobiledevice#969]
`idevice_t           device;`
`restored_client_t   restore_c;`

`idevice_new(&device, NULL);`
`restored_client_new(device, &restore_c, "whatever");`

`restored_reboot(restore_c);`

> Not rebooting device from recovery, or even just a normal reboot in normal mode.

**Comment by nikias** [comment]
This is not a bug. As the name of the function suggest, this function is for devices that are in restore mode. So obviously it won't work for recovery or normal mode devices.
For normal mode use diagnostics_relay API.
For recovery mode see libirecovery.
