### ISSUE TITLE
like #842 

### ISSUE THREAD

**Issue by tangwanchao** [libimobiledevice/libimobiledevice#995]
like #842 How to get factory value?

**Comment by Venhoe** [comment]
+1

**Comment by nikias** [comment]
Why open a new ticket?

**Comment by tangwanchao** [comment]
> Why open a new ticket?

Because there is no answer to that question

**Comment by tangwanchao** [comment]
@nikias 
Because there is no answer to that question

**Comment by nikias** [comment]
But then you don't open a new ticket referencing the old one, instead just comment on the old one.

**Comment by tangwanchao** [comment]
I'm very sorry, thank you for your notification, I already understand what to do.

**Comment by msk521** [comment]
@tangwanchao  Have you solved it？
